/**
 * DEMEANOR — pure authored data, no logic.
 *
 * The words a person is described with. These are not a second personality
 * engine: most of them are an expression of a trait the character already
 * has, or of an attribute sitting unusually high or low. The hidden trait
 * set still decides behaviour; this decides what the player reads.
 */

import type { AttributeKey, TraitKey } from '../engine/types';

export type DemeanorGroup =
  | 'Courage & Fear'
  | 'Honesty & Secrecy'
  | 'Loyalty & Attachment'
  | 'Authority & Control'
  | 'Compassion & Hardness'
  | 'Risk & Reward'
  | 'Social Style'
  | 'Conflict Style'
  | 'Discipline & Routine'
  | 'Ambition & Status'
  | 'Money & Possessions'
  | 'Curiosity & Knowledge'
  | 'Planning & Decision Making'
  | 'Emotional Regulation'
  | 'Trust & Suspicion'
  | 'Responsibility & Guilt'
  | 'Ideals & Principles'
  | 'Work & Competence'
  | 'Exploration & Novelty'
  | 'Violence & Combat Attitude'
  | 'Hope & Outlook'
  | 'Independence & Cooperation'
  | 'Patience & Time'
  | 'Pride & Shame'
  | 'Humor & Demeanor';

export interface DemeanorEntry {
  id: string;
  label: string;
  group: DemeanorGroup;
  /** The hidden trait this word is an expression of, where there is one. */
  expresses?: TraitKey;
  /** Or the attribute leaning it reflects. */
  attribute?: AttributeKey;
  direction?: 'high' | 'low';
}

export const DEMEANOR: DemeanorEntry[] = [
  { id: 'brave', label: 'Brave', group: 'Courage & Fear', expresses: 'brave' },
  { id: 'cautious', label: 'Cautious', group: 'Courage & Fear', expresses: 'cautious' },
  { id: 'fearless', label: 'Fearless', group: 'Courage & Fear', expresses: 'brave' },
  { id: 'anxious', label: 'Anxious', group: 'Courage & Fear', expresses: 'cowardly' },
  { id: 'timid', label: 'Timid', group: 'Courage & Fear', expresses: 'cowardly' },
  { id: 'adrenaline-seeking', label: 'Adrenaline-Seeking', group: 'Courage & Fear', expresses: 'reckless' },
  { id: 'trauma-wary', label: 'Trauma-Wary', group: 'Courage & Fear', expresses: 'cautious' },
  { id: 'steady-under-fire', label: 'Steady Under Fire', group: 'Courage & Fear', expresses: 'brave' },
  { id: 'panic-prone', label: 'Panic-Prone', group: 'Courage & Fear', expresses: 'cowardly' },
  { id: 'protective-courage', label: 'Protective Courage', group: 'Courage & Fear', expresses: 'protective' },
  { id: 'honest', label: 'Honest', group: 'Honesty & Secrecy', expresses: 'honest' },
  { id: 'blunt', label: 'Blunt', group: 'Honesty & Secrecy', expresses: 'honest' },
  { id: 'diplomatic', label: 'Diplomatic', group: 'Honesty & Secrecy', expresses: 'cooperative' },
  { id: 'secretive', label: 'Secretive', group: 'Honesty & Secrecy', expresses: 'suspicious' },
  { id: 'deceptive', label: 'Deceptive', group: 'Honesty & Secrecy', expresses: 'opportunistic' },
  { id: 'confessional', label: 'Confessional', group: 'Honesty & Secrecy', expresses: 'honest' },
  { id: 'guarded', label: 'Guarded', group: 'Honesty & Secrecy', expresses: 'suspicious' },
  { id: 'transparent', label: 'Transparent', group: 'Honesty & Secrecy', expresses: 'honest' },
  { id: 'manipulative', label: 'Manipulative', group: 'Honesty & Secrecy', expresses: 'opportunistic' },
  { id: 'principled-honesty', label: 'Principled Honesty', group: 'Honesty & Secrecy', expresses: 'honest' },
  { id: 'loyal', label: 'Loyal', group: 'Loyalty & Attachment', expresses: 'loyal' },
  { id: 'fiercely-loyal', label: 'Fiercely Loyal', group: 'Loyalty & Attachment', expresses: 'loyal' },
  { id: 'detached', label: 'Detached', group: 'Loyalty & Attachment', expresses: 'selfPreserving' },
  { id: 'family-oriented', label: 'Family-Oriented', group: 'Loyalty & Attachment', expresses: 'loyal' },
  { id: 'crew-oriented', label: 'Crew-Oriented', group: 'Loyalty & Attachment', expresses: 'loyal' },
  { id: 'possessive', label: 'Possessive', group: 'Loyalty & Attachment', expresses: 'protective' },
  { id: 'independent', label: 'Independent', group: 'Loyalty & Attachment', expresses: 'selfPreserving' },
  { id: 'devoted', label: 'Devoted', group: 'Loyalty & Attachment', expresses: 'loyal' },
  { id: 'slow-to-attach', label: 'Slow to Attach', group: 'Loyalty & Attachment', expresses: 'selfPreserving' },
  { id: 'easily-attached', label: 'Easily Attached', group: 'Loyalty & Attachment', expresses: 'loyal' },
  { id: 'authoritarian', label: 'Authoritarian', group: 'Authority & Control', expresses: 'controlling' },
  { id: 'democratic', label: 'Democratic', group: 'Authority & Control', expresses: 'cooperative' },
  { id: 'controlling', label: 'Controlling', group: 'Authority & Control', expresses: 'controlling' },
  { id: 'delegating', label: 'Delegating', group: 'Authority & Control', expresses: 'cooperative' },
  { id: 'rebellious', label: 'Rebellious', group: 'Authority & Control', expresses: 'stubborn' },
  { id: 'rule-following', label: 'Rule-Following', group: 'Authority & Control', expresses: 'dutiful' },
  { id: 'pragmatic-about-rules', label: 'Pragmatic About Rules', group: 'Authority & Control' },
  { id: 'commanding', label: 'Commanding', group: 'Authority & Control', expresses: 'controlling' },
  { id: 'conflict-avoidant-leader', label: 'Conflict-Avoidant Leader', group: 'Authority & Control', attribute: 'leadership', direction: 'low' },
  { id: 'hands-off', label: 'Hands-Off', group: 'Authority & Control', attribute: 'leadership', direction: 'low' },
  { id: 'compassionate', label: 'Compassionate', group: 'Compassion & Hardness', expresses: 'compassionate' },
  { id: 'merciful', label: 'Merciful', group: 'Compassion & Hardness', expresses: 'compassionate' },
  { id: 'hard-hearted', label: 'Hard-Hearted', group: 'Compassion & Hardness', expresses: 'greedy' },
  { id: 'empathetic', label: 'Empathetic', group: 'Compassion & Hardness', expresses: 'compassionate' },
  { id: 'unsympathetic', label: 'Unsympathetic', group: 'Compassion & Hardness', expresses: 'greedy' },
  { id: 'protective-of-the-weak', label: 'Protective of the Weak', group: 'Compassion & Hardness', expresses: 'protective' },
  { id: 'utilitarian', label: 'Utilitarian', group: 'Compassion & Hardness' },
  { id: 'forgiving', label: 'Forgiving', group: 'Compassion & Hardness', expresses: 'compassionate' },
  { id: 'vindictive', label: 'Vindictive', group: 'Compassion & Hardness', expresses: 'vindictive' },
  { id: 'gentle', label: 'Gentle', group: 'Compassion & Hardness', expresses: 'compassionate' },
  { id: 'risk-taker', label: 'Risk-Taker', group: 'Risk & Reward', expresses: 'reckless' },
  { id: 'risk-averse', label: 'Risk-Averse', group: 'Risk & Reward', expresses: 'cautious' },
  { id: 'calculated', label: 'Calculated', group: 'Risk & Reward', attribute: 'evaluation', direction: 'high' },
  { id: 'gambler', label: 'Gambler', group: 'Risk & Reward', expresses: 'reckless' },
  { id: 'conservative', label: 'Conservative', group: 'Risk & Reward', expresses: 'cautious' },
  { id: 'opportunistic', label: 'Opportunistic', group: 'Risk & Reward', expresses: 'opportunistic' },
  { id: 'patient', label: 'Patient', group: 'Risk & Reward', expresses: 'patient' },
  { id: 'impulsive', label: 'Impulsive', group: 'Risk & Reward', expresses: 'impulsive' },
  { id: 'all-in', label: 'All-In', group: 'Risk & Reward', expresses: 'reckless' },
  { id: 'hedging', label: 'Hedging', group: 'Risk & Reward', expresses: 'cautious' },
  { id: 'charismatic', label: 'Charismatic', group: 'Social Style', attribute: 'charisma', direction: 'high' },
  { id: 'reserved', label: 'Reserved', group: 'Social Style', attribute: 'charisma', direction: 'low' },
  { id: 'outgoing', label: 'Outgoing', group: 'Social Style', attribute: 'charisma', direction: 'high' },
  { id: 'introverted', label: 'Introverted', group: 'Social Style', attribute: 'charisma', direction: 'low' },
  { id: 'warm', label: 'Warm', group: 'Social Style', attribute: 'charisma', direction: 'high' },
  { id: 'aloof', label: 'Aloof', group: 'Social Style', attribute: 'charisma', direction: 'low' },
  { id: 'charming', label: 'Charming', group: 'Social Style', attribute: 'charisma', direction: 'high' },
  { id: 'awkward', label: 'Awkward', group: 'Social Style', attribute: 'socialAwareness', direction: 'low' },
  { id: 'formal', label: 'Formal', group: 'Social Style', attribute: 'discipline', direction: 'high' },
  { id: 'casual', label: 'Casual', group: 'Social Style', attribute: 'discipline', direction: 'low' },
  { id: 'confrontational', label: 'Confrontational', group: 'Conflict Style', expresses: 'aggressive' },
  { id: 'avoidant', label: 'Avoidant', group: 'Conflict Style', attribute: 'leadership', direction: 'low' },
  { id: 'mediator', label: 'Mediator', group: 'Conflict Style', expresses: 'cooperative' },
  { id: 'argumentative', label: 'Argumentative', group: 'Conflict Style', expresses: 'stubborn' },
  { id: 'peacemaker', label: 'Peacemaker', group: 'Conflict Style', expresses: 'cooperative' },
  { id: 'intimidating', label: 'Intimidating', group: 'Conflict Style', expresses: 'aggressive' },
  { id: 'passive-aggressive', label: 'Passive-Aggressive', group: 'Conflict Style', expresses: 'vindictive' },
  { id: 'stoic-in-conflict', label: 'Stoic in Conflict', group: 'Conflict Style', attribute: 'composure', direction: 'high' },
  { id: 'hot-tempered', label: 'Hot-Tempered', group: 'Conflict Style', expresses: 'aggressive' },
  { id: 'grudge-holding', label: 'Grudge-Holding', group: 'Conflict Style', expresses: 'vindictive' },
  { id: 'disciplined', label: 'Disciplined', group: 'Discipline & Routine', expresses: 'dutiful' },
  { id: 'chaotic', label: 'Chaotic', group: 'Discipline & Routine', expresses: 'impulsive' },
  { id: 'methodical', label: 'Methodical', group: 'Discipline & Routine', expresses: 'patient' },
  { id: 'procrastinating', label: 'Procrastinating', group: 'Discipline & Routine', attribute: 'discipline', direction: 'low' },
  { id: 'habitual', label: 'Habitual', group: 'Discipline & Routine', expresses: 'dutiful' },
  { id: 'flexible', label: 'Flexible', group: 'Discipline & Routine', attribute: 'discipline', direction: 'low' },
  { id: 'perfectionist', label: 'Perfectionist', group: 'Discipline & Routine', expresses: 'controlling' },
  { id: 'good-enough-pragmatist', label: 'Good-Enough Pragmatist', group: 'Discipline & Routine' },
  { id: 'workaholic', label: 'Workaholic', group: 'Discipline & Routine', expresses: 'dutiful' },
  { id: 'rest-protective', label: 'Rest-Protective', group: 'Discipline & Routine' },
  { id: 'ambitious', label: 'Ambitious', group: 'Ambition & Status', expresses: 'greedy' },
  { id: 'content', label: 'Content', group: 'Ambition & Status' },
  { id: 'competitive', label: 'Competitive', group: 'Ambition & Status', expresses: 'aggressive' },
  { id: 'status-conscious', label: 'Status-Conscious', group: 'Ambition & Status', expresses: 'greedy' },
  { id: 'humble', label: 'Humble', group: 'Ambition & Status', attribute: 'charisma', direction: 'low' },
  { id: 'recognition-seeking', label: 'Recognition-Seeking', group: 'Ambition & Status', expresses: 'greedy' },
  { id: 'legacy-minded', label: 'Legacy-Minded', group: 'Ambition & Status' },
  { id: 'power-seeking', label: 'Power-Seeking', group: 'Ambition & Status', expresses: 'greedy' },
  { id: 'service-minded', label: 'Service-Minded', group: 'Ambition & Status', expresses: 'dutiful' },
  { id: 'achievement-oriented', label: 'Achievement-Oriented', group: 'Ambition & Status', expresses: 'greedy' },
  { id: 'frugal', label: 'Frugal', group: 'Money & Possessions', expresses: 'greedy' },
  { id: 'generous', label: 'Generous', group: 'Money & Possessions', expresses: 'generous' },
  { id: 'materialistic', label: 'Materialistic', group: 'Money & Possessions', expresses: 'greedy' },
  { id: 'ascetic', label: 'Ascetic', group: 'Money & Possessions', expresses: 'generous' },
  { id: 'hoarding', label: 'Hoarding', group: 'Money & Possessions', expresses: 'greedy' },
  { id: 'spendthrift', label: 'Spendthrift', group: 'Money & Possessions', expresses: 'generous' },
  { id: 'debt-averse', label: 'Debt-Averse', group: 'Money & Possessions', expresses: 'cautious' },
  { id: 'speculative', label: 'Speculative', group: 'Money & Possessions', expresses: 'opportunistic' },
  { id: 'security-seeking', label: 'Security-Seeking', group: 'Money & Possessions', expresses: 'cautious' },
  { id: 'possession-light', label: 'Possession-Light', group: 'Money & Possessions', expresses: 'generous' },
  { id: 'curious', label: 'Curious', group: 'Curiosity & Knowledge', expresses: 'curious' },
  { id: 'inquisitive', label: 'Inquisitive', group: 'Curiosity & Knowledge', expresses: 'curious' },
  { id: 'skeptical', label: 'Skeptical', group: 'Curiosity & Knowledge', expresses: 'suspicious' },
  { id: 'credulous', label: 'Credulous', group: 'Curiosity & Knowledge', expresses: 'cooperative' },
  { id: 'scholarly', label: 'Scholarly', group: 'Curiosity & Knowledge', expresses: 'curious' },
  { id: 'hands-on-learner', label: 'Hands-On Learner', group: 'Curiosity & Knowledge', attribute: 'learning', direction: 'low' },
  { id: 'mystery-seeking', label: 'Mystery-Seeking', group: 'Curiosity & Knowledge', expresses: 'curious' },
  { id: 'knowledge-hoarding', label: 'Knowledge-Hoarding', group: 'Curiosity & Knowledge', expresses: 'greedy' },
  { id: 'teacherly', label: 'Teacherly', group: 'Curiosity & Knowledge', attribute: 'socialAwareness', direction: 'high' },
  { id: 'anti-intellectual', label: 'Anti-Intellectual', group: 'Curiosity & Knowledge', attribute: 'learning', direction: 'low' },
  { id: 'planner', label: 'Planner', group: 'Planning & Decision Making', attribute: 'reasoning', direction: 'high' },
  { id: 'improviser', label: 'Improviser', group: 'Planning & Decision Making', expresses: 'impulsive' },
  { id: 'decisive', label: 'Decisive', group: 'Planning & Decision Making', attribute: 'decisionMaking', direction: 'high' },
  { id: 'indecisive', label: 'Indecisive', group: 'Planning & Decision Making', attribute: 'decisionMaking', direction: 'low' },
  { id: 'analytical', label: 'Analytical', group: 'Planning & Decision Making', attribute: 'reasoning', direction: 'high' },
  { id: 'intuitive', label: 'Intuitive', group: 'Planning & Decision Making', attribute: 'reasoning', direction: 'low' },
  { id: 'second-guesser', label: 'Second-Guesser', group: 'Planning & Decision Making', attribute: 'decisionMaking', direction: 'low' },
  { id: 'contingency-minded', label: 'Contingency-Minded', group: 'Planning & Decision Making', expresses: 'cautious' },
  { id: 'simplifier', label: 'Simplifier', group: 'Planning & Decision Making', attribute: 'reasoning', direction: 'low' },
  { id: 'overthinker', label: 'Overthinker', group: 'Planning & Decision Making', attribute: 'reasoning', direction: 'high' },
  { id: 'calm', label: 'Calm', group: 'Emotional Regulation', attribute: 'composure', direction: 'high' },
  { id: 'volatile', label: 'Volatile', group: 'Emotional Regulation', attribute: 'composure', direction: 'low' },
  { id: 'stoic', label: 'Stoic', group: 'Emotional Regulation', attribute: 'composure', direction: 'high' },
  { id: 'expressive', label: 'Expressive', group: 'Emotional Regulation', attribute: 'composure', direction: 'low' },
  { id: 'resentful', label: 'Resentful', group: 'Emotional Regulation', expresses: 'vindictive' },
  { id: 'quick-to-recover', label: 'Quick to Recover', group: 'Emotional Regulation', attribute: 'resilience', direction: 'high' },
  { id: 'sensitive', label: 'Sensitive', group: 'Emotional Regulation', attribute: 'composure', direction: 'low' },
  { id: 'thick-skinned', label: 'Thick-Skinned', group: 'Emotional Regulation', attribute: 'resilience', direction: 'high' },
  { id: 'brooding', label: 'Brooding', group: 'Emotional Regulation', attribute: 'composure', direction: 'low' },
  { id: 'emotionally-compartmentalized', label: 'Emotionally Compartmentalized', group: 'Emotional Regulation', attribute: 'discipline', direction: 'high' },
  { id: 'trusting', label: 'Trusting', group: 'Trust & Suspicion', expresses: 'cooperative' },
  { id: 'suspicious', label: 'Suspicious', group: 'Trust & Suspicion', expresses: 'suspicious' },
  { id: 'paranoid', label: 'Paranoid', group: 'Trust & Suspicion', expresses: 'suspicious' },
  { id: 'open-minded', label: 'Open-Minded', group: 'Trust & Suspicion', expresses: 'cooperative' },
  { id: 'cynical', label: 'Cynical', group: 'Trust & Suspicion', expresses: 'suspicious' },
  { id: 'benefit-of-the-doubt', label: 'Benefit-of-the-Doubt', group: 'Trust & Suspicion', expresses: 'cooperative' },
  { id: 'evidence-driven-trust', label: 'Evidence-Driven Trust', group: 'Trust & Suspicion', attribute: 'evaluation', direction: 'high' },
  { id: 'clan-minded', label: 'Clan-Minded', group: 'Trust & Suspicion', expresses: 'loyal' },
  { id: 'institution-trusting', label: 'Institution-Trusting', group: 'Trust & Suspicion', expresses: 'cooperative' },
  { id: 'institution-skeptical', label: 'Institution-Skeptical', group: 'Trust & Suspicion', expresses: 'suspicious' },
  { id: 'responsible', label: 'Responsible', group: 'Responsibility & Guilt', expresses: 'dutiful' },
  { id: 'duty-bound', label: 'Duty-Bound', group: 'Responsibility & Guilt', expresses: 'dutiful' },
  { id: 'guilt-prone', label: 'Guilt-Prone', group: 'Responsibility & Guilt', attribute: 'composure', direction: 'low' },
  { id: 'blame-shifting', label: 'Blame-Shifting', group: 'Responsibility & Guilt' },
  { id: 'accountable', label: 'Accountable', group: 'Responsibility & Guilt', expresses: 'dutiful' },
  { id: 'martyring', label: 'Martyring', group: 'Responsibility & Guilt' },
  { id: 'boundary-conscious', label: 'Boundary-Conscious', group: 'Responsibility & Guilt' },
  { id: 'promise-keeping', label: 'Promise-Keeping', group: 'Responsibility & Guilt', expresses: 'dutiful' },
  { id: 'outcome-focused', label: 'Outcome-Focused', group: 'Responsibility & Guilt' },
  { id: 'protective-of-dependents', label: 'Protective of Dependents', group: 'Responsibility & Guilt', expresses: 'protective' },
  { id: 'principled', label: 'Principled', group: 'Ideals & Principles' },
  { id: 'pragmatic', label: 'Pragmatic', group: 'Ideals & Principles' },
  { id: 'idealistic', label: 'Idealistic', group: 'Ideals & Principles' },
  { id: 'fatalistic', label: 'Fatalistic', group: 'Ideals & Principles' },
  { id: 'humanistic', label: 'Humanistic', group: 'Ideals & Principles', expresses: 'compassionate' },
  { id: 'traditionalist', label: 'Traditionalist', group: 'Ideals & Principles', expresses: 'stubborn' },
  { id: 'iconoclastic', label: 'Iconoclastic', group: 'Ideals & Principles', expresses: 'stubborn' },
  { id: 'pacifistic', label: 'Pacifistic', group: 'Ideals & Principles' },
  { id: 'retributive', label: 'Retributive', group: 'Ideals & Principles', expresses: 'vindictive' },
  { id: 'consequentialist', label: 'Consequentialist', group: 'Ideals & Principles' },
  { id: 'proud-craftsperson', label: 'Proud Craftsperson', group: 'Work & Competence', attribute: 'discipline', direction: 'high' },
  { id: 'efficiency-minded', label: 'Efficiency-Minded', group: 'Work & Competence', attribute: 'reasoning', direction: 'high' },
  { id: 'thorough', label: 'Thorough', group: 'Work & Competence', expresses: 'patient' },
  { id: 'sloppy', label: 'Sloppy', group: 'Work & Competence', attribute: 'discipline', direction: 'low' },
  { id: 'mentor', label: 'Mentor', group: 'Work & Competence', attribute: 'leadership', direction: 'high' },
  { id: 'self-reliant', label: 'Self-Reliant', group: 'Work & Competence', expresses: 'selfPreserving' },
  { id: 'help-seeking', label: 'Help-Seeking', group: 'Work & Competence' },
  { id: 'competence-insecure', label: 'Competence-Insecure', group: 'Work & Competence', attribute: 'composure', direction: 'low' },
  { id: 'prideful', label: 'Prideful', group: 'Work & Competence', expresses: 'greedy' },
  { id: 'professional', label: 'Professional', group: 'Work & Competence', expresses: 'dutiful' },
  { id: 'adventurous', label: 'Adventurous', group: 'Exploration & Novelty', expresses: 'curious' },
  { id: 'homebody', label: 'Homebody', group: 'Exploration & Novelty', expresses: 'selfPreserving' },
  { id: 'wanderlust', label: 'Wanderlust', group: 'Exploration & Novelty', expresses: 'curious' },
  { id: 'routine-seeking', label: 'Routine-Seeking', group: 'Exploration & Novelty', expresses: 'stubborn' },
  { id: 'frontier-minded', label: 'Frontier-Minded', group: 'Exploration & Novelty', expresses: 'curious' },
  { id: 'comfort-seeking', label: 'Comfort-Seeking', group: 'Exploration & Novelty', expresses: 'selfPreserving' },
  { id: 'collector', label: 'Collector', group: 'Exploration & Novelty' },
  { id: 'naturalist', label: 'Naturalist', group: 'Exploration & Novelty', expresses: 'curious' },
  { id: 'ruin-obsessed', label: 'Ruin-Obsessed', group: 'Exploration & Novelty', expresses: 'curious' },
  { id: 'cautious-explorer', label: 'Cautious Explorer', group: 'Exploration & Novelty', expresses: 'cautious' },
  { id: 'aggressive', label: 'Aggressive', group: 'Violence & Combat Attitude', expresses: 'aggressive' },
  { id: 'defensive', label: 'Defensive', group: 'Violence & Combat Attitude' },
  { id: 'combat-confident', label: 'Combat-Confident', group: 'Violence & Combat Attitude', expresses: 'aggressive' },
  { id: 'combat-averse', label: 'Combat-Averse', group: 'Violence & Combat Attitude', expresses: 'cowardly' },
  { id: 'predatory', label: 'Predatory', group: 'Violence & Combat Attitude', expresses: 'reckless' },
  { id: 'protective-fighter', label: 'Protective Fighter', group: 'Violence & Combat Attitude', expresses: 'protective' },
  { id: 'mercenary', label: 'Mercenary', group: 'Violence & Combat Attitude', expresses: 'opportunistic' },
  { id: 'honor-bound-fighter', label: 'Honor-Bound Fighter', group: 'Violence & Combat Attitude', expresses: 'dutiful' },
  { id: 'dirty-fighter', label: 'Dirty Fighter', group: 'Violence & Combat Attitude', expresses: 'aggressive' },
  { id: 'weapon-shy', label: 'Weapon-Shy', group: 'Violence & Combat Attitude', expresses: 'cowardly' },
  { id: 'optimistic', label: 'Optimistic', group: 'Hope & Outlook' },
  { id: 'pessimistic', label: 'Pessimistic', group: 'Hope & Outlook' },
  { id: 'hopeful', label: 'Hopeful', group: 'Hope & Outlook' },
  { id: 'doomer', label: 'Doomer', group: 'Hope & Outlook' },
  { id: 'realistic', label: 'Realistic', group: 'Hope & Outlook', attribute: 'evaluation', direction: 'high' },
  { id: 'romantic', label: 'Romantic', group: 'Hope & Outlook' },
  { id: 'world-weary', label: 'World-Weary', group: 'Hope & Outlook' },
  { id: 'future-oriented', label: 'Future-Oriented', group: 'Hope & Outlook' },
  { id: 'present-oriented', label: 'Present-Oriented', group: 'Hope & Outlook' },
  { id: 'nostalgic', label: 'Nostalgic', group: 'Hope & Outlook' },
  { id: 'cooperative', label: 'Cooperative', group: 'Independence & Cooperation', expresses: 'cooperative' },
  { id: 'solo-minded', label: 'Solo-Minded', group: 'Independence & Cooperation', expresses: 'selfPreserving' },
  { id: 'consensus-seeking', label: 'Consensus-Seeking', group: 'Independence & Cooperation', expresses: 'cooperative' },
  { id: 'self-directed', label: 'Self-Directed', group: 'Independence & Cooperation', attribute: 'discipline', direction: 'high' },
  { id: 'mutual-aid-oriented', label: 'Mutual-Aid Oriented', group: 'Independence & Cooperation', expresses: 'compassionate' },
  { id: 'transactional', label: 'Transactional', group: 'Independence & Cooperation', expresses: 'opportunistic' },
  { id: 'dependent', label: 'Dependent', group: 'Independence & Cooperation', attribute: 'leadership', direction: 'low' },
  { id: 'autonomous', label: 'Autonomous', group: 'Independence & Cooperation', expresses: 'selfPreserving' },
  { id: 'team-builder', label: 'Team-Builder', group: 'Independence & Cooperation', expresses: 'cooperative' },
  { id: 'factional', label: 'Factional', group: 'Independence & Cooperation' },
  { id: 'impatient', label: 'Impatient', group: 'Patience & Time', expresses: 'impulsive' },
  { id: 'deadline-driven', label: 'Deadline-Driven', group: 'Patience & Time', attribute: 'discipline', direction: 'high' },
  { id: 'leisurely', label: 'Leisurely', group: 'Patience & Time', expresses: 'patient' },
  { id: 'time-anxious', label: 'Time-Anxious', group: 'Patience & Time', attribute: 'composure', direction: 'low' },
  { id: 'long-horizon-thinker', label: 'Long-Horizon Thinker', group: 'Patience & Time', expresses: 'patient' },
  { id: 'short-horizon-thinker', label: 'Short-Horizon Thinker', group: 'Patience & Time' },
  { id: 'waiting-averse', label: 'Waiting-Averse', group: 'Patience & Time', expresses: 'impulsive' },
  { id: 'deliberate', label: 'Deliberate', group: 'Patience & Time', expresses: 'patient' },
  { id: 'snap-decider', label: 'Snap-Decider', group: 'Patience & Time', expresses: 'impulsive' },
  { id: 'proud', label: 'Proud', group: 'Pride & Shame', expresses: 'greedy' },
  { id: 'shame-prone', label: 'Shame-Prone', group: 'Pride & Shame', attribute: 'composure', direction: 'low' },
  { id: 'boastful', label: 'Boastful', group: 'Pride & Shame', expresses: 'greedy' },
  { id: 'modest', label: 'Modest', group: 'Pride & Shame', attribute: 'charisma', direction: 'low' },
  { id: 'honor-conscious', label: 'Honor-Conscious', group: 'Pride & Shame', expresses: 'dutiful' },
  { id: 'reputation-indifferent', label: 'Reputation-Indifferent', group: 'Pride & Shame' },
  { id: 'face-saving', label: 'Face-Saving', group: 'Pride & Shame' },
  { id: 'self-deprecating', label: 'Self-Deprecating', group: 'Pride & Shame', attribute: 'charisma', direction: 'low' },
  { id: 'dry-humored', label: 'Dry-Humored', group: 'Humor & Demeanor' },
  { id: 'playful', label: 'Playful', group: 'Humor & Demeanor', attribute: 'charisma', direction: 'high' },
  { id: 'serious', label: 'Serious', group: 'Humor & Demeanor' },
  { id: 'sarcastic', label: 'Sarcastic', group: 'Humor & Demeanor' },
  { id: 'earnest', label: 'Earnest', group: 'Humor & Demeanor' },
  { id: 'morbidly-funny', label: 'Morbidly Funny', group: 'Humor & Demeanor' },
  { id: 'cheerful', label: 'Cheerful', group: 'Humor & Demeanor', attribute: 'charisma', direction: 'high' },
  { id: 'grim', label: 'Grim', group: 'Humor & Demeanor' },
  { id: 'deadpan', label: 'Deadpan', group: 'Humor & Demeanor' },
  { id: 'theatrical', label: 'Theatrical', group: 'Humor & Demeanor', attribute: 'charisma', direction: 'high' },
];
