/**
 * ITEM CATALOGUE — pure authored data, no logic.
 *
 * Calibration notes (see engine/tuning.ts):
 * - `power` feeds the wound severity score. WOUNDS.thresholds: 20 none / 40 minor /
 *   60 serious / 80 critical / 95 mortal. Armor and Resilience subtract from the
 *   score and the check outcome swings it by roughly -20..+18. So an unarmed hit
 *   sits near 20, a knife near 35, a service pistol near 48, a service rifle near
 *   62, a marksman rifle near 74, and the plasma lance tops the catalogue at 84.
 * - `protection` is the listed value at 100% condition. Effective protection is
 *   listed * (ARMOR.conditionBase + ARMOR.conditionSpan * condition/100) and each
 *   effective point removes ARMOR.protectionToSeverity (0.55) from the score.
 * - Anything heavier than INVENTORY.bulkyWeight (12) is marked `bulky`.
 * - Ammo is counted in single shots, so ammo weight and price are per round.
 */

import type { ItemDef } from '../engine/types';

export const ITEM_DEFS: ItemDef[] = [
  // -------------------------------------------------------------------------
  // Food — restores crew-days against FOOD.perCrewPerDay
  // -------------------------------------------------------------------------
  {
    id: 'ration_pack',
    name: 'Ration Pack',
    category: 'food',
    basePrice: 8,
    weight: 1,
    stackable: true,
    description:
      'A sealed brick of compressed grain, fat and salt rated for a decade in unheated storage.',
    foodDays: 2,
  },
  {
    id: 'preserved_meal',
    name: 'Preserved Meal',
    category: 'food',
    basePrice: 14,
    weight: 2,
    stackable: true,
    description:
      'A retort pouch of stew that heats on a cell and holds its nutrition for years.',
    foodDays: 3,
  },
  {
    id: 'fresh_produce',
    name: 'Fresh Produce',
    category: 'food',
    basePrice: 26,
    weight: 3,
    stackable: true,
    description:
      'Crated greens and roots from a station farm; better eating than rations, but it spoils within weeks.',
    foodDays: 3,
  },
  {
    id: 'protein_culture',
    name: 'Protein Culture',
    category: 'food',
    basePrice: 48,
    weight: 5,
    stackable: true,
    description:
      'A slab of vat-grown protein cake cut from a hydroponics culture and portioned by weight.',
    foodDays: 9,
  },
  {
    id: 'stim_coffee',
    name: 'Stim Coffee',
    category: 'food',
    basePrice: 12,
    weight: 1,
    stackable: true,
    description:
      'A tin of bitter concentrate that crews drink to stretch a watch past where it should end.',
    foodDays: 0.5,
  },

  // -------------------------------------------------------------------------
  // Medicine — units consumed per MEDICINE.usage by wound severity
  // -------------------------------------------------------------------------
  {
    id: 'medkit_basic',
    name: 'Basic Medkit',
    category: 'medicine',
    basePrice: 45,
    weight: 2,
    stackable: true,
    description:
      'A hard case of gauze, clamps, sealant and clean water for treating wounds outside a med bay.',
    medicineUnits: 4,
  },
  {
    id: 'medkit_field',
    name: 'Field Medkit',
    category: 'medicine',
    basePrice: 110,
    weight: 3,
    stackable: true,
    description:
      'A deep-stocked trauma bag with tourniquets, a plasma line and a monitor that still works.',
    medicineUnits: 9,
  },
  {
    id: 'antibiotics',
    name: 'Antibiotics',
    category: 'medicine',
    basePrice: 30,
    weight: 1,
    stackable: true,
    description:
      'Broad-spectrum ampoules that hold back infection in a wound nobody could clean properly.',
    medicineUnits: 2,
  },
  {
    id: 'painkillers',
    name: 'Painkillers',
    category: 'medicine',
    basePrice: 18,
    weight: 1,
    stackable: true,
    description:
      'Blister strips of analgesic that let a wounded crew member keep working, at a cost.',
    medicineUnits: 1,
  },
  {
    id: 'surgical_kit',
    name: 'Surgical Kit',
    category: 'medicine',
    basePrice: 260,
    weight: 5,
    stackable: false,
    description:
      'A rolled tray of clamps, retractors and suture stock, useless without someone who can use it.',
    toolBonus: [
      { skill: 'surgery', value: 12 },
      { skill: 'firstAid', value: 5 },
    ],
    medicineUnits: 6,
  },
  {
    id: 'blood_substitute',
    name: 'Blood Substitute',
    category: 'medicine',
    basePrice: 75,
    weight: 1,
    stackable: true,
    description:
      'Bagged oxygen-carrier fluid that buys hours for a crew member who is bleeding out.',
    medicineUnits: 5,
  },
  {
    id: 'stim_shot',
    name: 'Stim Shot',
    category: 'medicine',
    basePrice: 34,
    weight: 1,
    stackable: true,
    description:
      'A single-use injector that pushes a body past exhaustion and leaves it worse afterward.',
    medicineUnits: 2,
  },

  // -------------------------------------------------------------------------
  // Ship parts — break down into repair parts for REPAIR costs
  // -------------------------------------------------------------------------
  {
    id: 'repair_kit',
    name: 'Repair Kit',
    category: 'shipPart',
    basePrice: 120,
    weight: 6,
    stackable: true,
    description:
      'A general spares case of fasteners, gasket stock, sealant and patch plate for shipboard work.',
    repairParts: 12,
  },
  {
    id: 'hull_patch',
    name: 'Hull Patch',
    category: 'shipPart',
    basePrice: 55,
    weight: 4,
    stackable: true,
    description:
      'A pre-cut plate and adhesive charge for closing a breach without a proper yard.',
    repairParts: 6,
  },
  {
    id: 'power_cell',
    name: 'Power Cell',
    category: 'shipPart',
    basePrice: 90,
    weight: 3,
    stackable: true,
    description:
      'A rechargeable bus cell that keeps a system alive while its feed is being rebuilt.',
    repairParts: 5,
  },
  {
    id: 'coolant_flask',
    name: 'Coolant Flask',
    category: 'shipPart',
    basePrice: 40,
    weight: 2,
    stackable: true,
    description:
      'Pressurised coolant for topping up a loop that has been venting since the last hard burn.',
    repairParts: 3,
  },
  {
    id: 'engine_coupling',
    name: 'Engine Coupling',
    category: 'shipPart',
    basePrice: 210,
    weight: 8,
    stackable: true,
    description:
      'A machined drive coupling, the part that fails first and strands ships when it does.',
    repairParts: 14,
  },
  {
    id: 'sensor_module',
    name: 'Sensor Module',
    category: 'shipPart',
    basePrice: 340,
    weight: 5,
    stackable: false,
    description:
      'A replacement receiver array for a sensor suite that has stopped seeing what is ahead.',
    repairParts: 10,
  },
  {
    id: 'shield_emitter',
    name: 'Shield Emitter',
    category: 'shipPart',
    basePrice: 480,
    weight: 9,
    stackable: false,
    description:
      'An emitter head for a deflector ring, salvaged far more often than it is bought new.',
    repairParts: 12,
  },
  {
    id: 'life_support_filter',
    name: 'Life Support Filter',
    category: 'shipPart',
    basePrice: 65,
    weight: 3,
    stackable: true,
    description:
      'A stacked scrubber cartridge that pulls carbon and particulates out of recycled air.',
    repairParts: 4,
  },
  {
    id: 'fuel_canister',
    name: 'Fuel Canister',
    category: 'shipPart',
    basePrice: 160,
    weight: 14,
    bulky: true,
    stackable: true,
    description:
      'A pressurised canister holding twenty units of drive fuel, heavy enough that it rides in the hold.',
  },

  // -------------------------------------------------------------------------
  // Tools — bonuses apply while equipped in the tool slot
  // -------------------------------------------------------------------------
  {
    id: 'multitool',
    name: 'Multitool',
    category: 'tool',
    basePrice: 85,
    weight: 2,
    stackable: false,
    description:
      'A folding set of drivers, cutters and probes that covers most of what goes wrong day to day.',
    toolBonus: [
      { skill: 'mechanicalEngineering', value: 6 },
      { skill: 'electricalEngineering', value: 4 },
    ],
  },
  {
    id: 'plasma_cutter',
    name: 'Plasma Cutter',
    category: 'tool',
    basePrice: 340,
    weight: 7,
    stackable: false,
    description:
      'A two-handed torch that burns through plate steel and welded hatches on a drawn energy cell.',
    attacks: [
      {
        name: 'Cut',
        damageType: 'burn',
        power: 56,
        skill: 'meleeWeapons',
        handling: 'slow',
        ranges: ['engaged'],
        ammoId: 'energy_cell',
        ammoPerShot: 2,
      },
    ],
    toolBonus: [
      { skill: 'mechanicalEngineering', value: 8 },
      { skill: 'scavenging', value: 5 },
    ],
    properties: ['Two-handed', 'Cuts through bulkheads'],
  },
  {
    id: 'diagnostic_scanner',
    name: 'Diagnostic Scanner',
    category: 'tool',
    basePrice: 260,
    weight: 2,
    stackable: false,
    description:
      'A handheld sensor package that reads vitals and traces faults along a circuit run.',
    toolBonus: [
      { skill: 'medicalDiagnostics', value: 10 },
      { skill: 'electricalEngineering', value: 5 },
    ],
  },
  {
    id: 'lockpick_set',
    name: 'Lockpick Set',
    category: 'tool',
    basePrice: 140,
    weight: 1,
    stackable: false,
    description:
      'Tension bars, rakes and a bypass shim in a flat roll that fits inside a sleeve.',
    toolBonus: [{ skill: 'lockpicking', value: 12 }],
  },
  {
    id: 'welding_rig',
    name: 'Welding Rig',
    category: 'tool',
    basePrice: 190,
    weight: 13,
    bulky: true,
    stackable: false,
    description:
      'A wheeled welder with feed spool and mask, awkward to move but capable of a permanent repair.',
    toolBonus: [
      { skill: 'mechanicalEngineering', value: 10 },
      { skill: 'weaponsmithing', value: 5 },
    ],
    properties: ['Two-handed'],
  },
  {
    id: 'portable_terminal',
    name: 'Portable Terminal',
    category: 'tool',
    basePrice: 300,
    weight: 3,
    stackable: false,
    description:
      'A ruggedised terminal with a hardline port for reading systems that no longer talk to anything.',
    toolBonus: [
      { skill: 'computers', value: 10 },
      { skill: 'navigation', value: 4 },
    ],
  },

  // -------------------------------------------------------------------------
  // Exploration gear
  // -------------------------------------------------------------------------
  {
    id: 'handheld_scanner',
    name: 'Handheld Scanner',
    category: 'explorationGear',
    basePrice: 180,
    weight: 2,
    stackable: false,
    description:
      'A survey unit that flags dense metal and cavities behind a wall before anyone starts cutting.',
    toolBonus: [
      { skill: 'scavenging', value: 8 },
      { skill: 'exploration', value: 4 },
    ],
  },
  {
    id: 'rope_line',
    name: 'Rope Line',
    category: 'explorationGear',
    basePrice: 45,
    weight: 4,
    stackable: false,
    description:
      'Fifty metres of woven line with anchors, the standard answer to a shaft with no ladder.',
    toolBonus: [{ skill: 'exploration', value: 6 }],
  },
  {
    id: 'glow_rods',
    name: 'Glow Rods',
    category: 'explorationGear',
    basePrice: 12,
    weight: 1,
    stackable: true,
    description:
      'Chemical light sticks that burn for hours and do not care whether the power is on.',
    toolBonus: [{ skill: 'exploration', value: 4 }],
  },
  {
    id: 'rebreather',
    name: 'Rebreather',
    category: 'explorationGear',
    basePrice: 220,
    weight: 3,
    stackable: false,
    description:
      'A half-mask and scrubber cartridge that makes a fouled compartment survivable for a while.',
    toolBonus: [{ skill: 'exploration', value: 5 }],
    properties: ['Sealed'],
  },
  {
    id: 'climbing_rig',
    name: 'Climbing Rig',
    category: 'explorationGear',
    basePrice: 130,
    weight: 6,
    stackable: false,
    description:
      'Harness, descender and hardware for working a vertical shaft without trusting the structure.',
    toolBonus: [{ skill: 'exploration', value: 9 }],
  },
  {
    id: 'emergency_beacon',
    name: 'Emergency Beacon',
    category: 'explorationGear',
    basePrice: 90,
    weight: 2,
    stackable: false,
    description:
      'A hardened transmitter that broadcasts a fixed distress position until its cell runs out.',
    properties: ['Loud'],
  },
  {
    id: 'thermal_blanket',
    name: 'Thermal Blanket',
    category: 'explorationGear',
    basePrice: 25,
    weight: 1,
    stackable: true,
    description:
      'A foil sheet that holds body heat in an unheated compartment or on a casualty in shock.',
    toolBonus: [{ skill: 'firstAid', value: 4 }],
  },

  // -------------------------------------------------------------------------
  // Weapons — slug throwers
  // -------------------------------------------------------------------------
  {
    id: 'pistol_service',
    name: 'Service Pistol',
    category: 'weapon',
    basePrice: 320,
    weight: 2,
    stackable: false,
    description:
      'The standard sidearm of station security, common enough that ammunition is never the problem.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 48,
        skill: 'firearms',
        handling: 'fast',
        ranges: ['engaged', 'close', 'medium'],
        ammoId: 'ammo_pistol',
        ammoPerShot: 1,
      },
      {
        name: 'Pistol-Whip',
        damageType: 'blunt',
        power: 24,
        skill: 'striking',
        handling: 'fast',
        ranges: ['engaged'],
      },
    ],
    properties: ['Loud'],
  },
  {
    id: 'pistol_holdout',
    name: 'Holdout Pistol',
    category: 'weapon',
    basePrice: 150,
    weight: 1,
    stackable: false,
    description:
      'A two-shot frame small enough to ride in a boot, accurate to about the length of a corridor.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 38,
        skill: 'firearms',
        handling: 'veryFast',
        ranges: ['engaged', 'close'],
        ammoId: 'ammo_pistol',
        ammoPerShot: 1,
      },
    ],
    properties: ['Concealable', 'Loud'],
  },
  {
    id: 'revolver_heavy',
    name: 'Heavy Revolver',
    category: 'weapon',
    basePrice: 460,
    weight: 3,
    stackable: false,
    description:
      'A heavy-frame revolver built for gloved hands, with recoil that punishes a loose grip.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 58,
        skill: 'firearms',
        handling: 'normal',
        ranges: ['engaged', 'close', 'medium'],
        ammoId: 'ammo_pistol',
        ammoPerShot: 1,
      },
    ],
    properties: ['Loud'],
  },
  {
    id: 'rifle_hunting',
    name: 'Hunting Rifle',
    category: 'weapon',
    basePrice: 520,
    weight: 6,
    stackable: false,
    description:
      'A bolt-action rifle sold to colonists for large game, still the hardest single shot most crews own.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 66,
        skill: 'firearms',
        handling: 'slow',
        ranges: ['close', 'medium', 'long'],
        ammoId: 'ammo_rifle',
        ammoPerShot: 1,
      },
      {
        name: 'Buttstroke',
        damageType: 'blunt',
        power: 26,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    properties: ['Two-handed', 'Single shot', 'Awkward when engaged'],
  },
  {
    id: 'rifle_service',
    name: 'Service Rifle',
    category: 'weapon',
    basePrice: 700,
    weight: 7,
    stackable: false,
    description: 'A military pattern rifle with a selector, worn but maintained to a standard.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 62,
        skill: 'firearms',
        handling: 'normal',
        ranges: ['close', 'medium', 'long'],
        ammoId: 'ammo_rifle',
        ammoPerShot: 1,
      },
      {
        name: 'Burst',
        damageType: 'pierce',
        power: 70,
        skill: 'firearms',
        handling: 'slow',
        ranges: ['close', 'medium'],
        ammoId: 'ammo_rifle',
        ammoPerShot: 3,
      },
      {
        name: 'Buttstroke',
        damageType: 'blunt',
        power: 27,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    properties: ['Two-handed', 'Loud'],
  },
  {
    id: 'rifle_marksman',
    name: 'Marksman Rifle',
    category: 'weapon',
    basePrice: 1250,
    weight: 8,
    stackable: false,
    description:
      'A long-barrelled rifle with an optic, useless in a corridor and decisive across a landing field.',
    attacks: [
      {
        name: 'Aimed Shot',
        damageType: 'pierce',
        power: 74,
        skill: 'firearms',
        handling: 'slow',
        ranges: ['medium', 'long'],
        ammoId: 'ammo_rifle',
        ammoPerShot: 1,
      },
      {
        name: 'Snap Shot',
        damageType: 'pierce',
        power: 58,
        skill: 'firearms',
        handling: 'normal',
        ranges: ['close', 'medium'],
        ammoId: 'ammo_rifle',
        ammoPerShot: 1,
      },
    ],
    properties: ['Two-handed', 'Loud', 'Awkward when engaged'],
  },
  {
    id: 'shotgun_breaching',
    name: 'Breaching Shotgun',
    category: 'weapon',
    basePrice: 540,
    weight: 7,
    stackable: false,
    description:
      'A short shotgun issued for opening hatches, chambered for frangible rounds and buckshot alike.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 64,
        skill: 'firearms',
        handling: 'slow',
        ranges: ['engaged', 'close'],
        ammoId: 'ammo_shotgun',
        ammoPerShot: 1,
      },
      {
        name: 'Breaching Round',
        damageType: 'blunt',
        power: 44,
        skill: 'firearms',
        handling: 'verySlow',
        ranges: ['engaged'],
        ammoId: 'ammo_shotgun',
        ammoPerShot: 1,
      },
    ],
    properties: ['Two-handed', 'Breaching', 'Loud'],
  },
  {
    id: 'shotgun_field',
    name: 'Field Shotgun',
    category: 'weapon',
    basePrice: 380,
    weight: 6,
    stackable: false,
    description: 'A pump shotgun kept near the cargo hatches, loaded for whatever comes through them.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 60,
        skill: 'firearms',
        handling: 'normal',
        ranges: ['engaged', 'close', 'medium'],
        ammoId: 'ammo_shotgun',
        ammoPerShot: 1,
      },
      {
        name: 'Buttstroke',
        damageType: 'blunt',
        power: 28,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    properties: ['Two-handed', 'Loud'],
  },
  {
    id: 'smg_compact',
    name: 'Compact SMG',
    category: 'weapon',
    basePrice: 610,
    weight: 4,
    stackable: false,
    description:
      'A compact automatic firing pistol rounds, meant for holding a corridor rather than a field.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 46,
        skill: 'firearms',
        handling: 'fast',
        ranges: ['engaged', 'close', 'medium'],
        ammoId: 'ammo_pistol',
        ammoPerShot: 1,
      },
      {
        name: 'Burst',
        damageType: 'pierce',
        power: 56,
        skill: 'firearms',
        handling: 'normal',
        ranges: ['engaged', 'close'],
        ammoId: 'ammo_pistol',
        ammoPerShot: 4,
      },
    ],
    properties: ['Loud'],
  },
  {
    id: 'carbine_worn',
    name: 'Worn Carbine',
    category: 'weapon',
    basePrice: 240,
    weight: 5,
    stackable: false,
    description:
      'A shortened rifle with a pitted bore and mismatched furniture, sold cheap for good reason.',
    attacks: [
      {
        name: 'Fire',
        damageType: 'pierce',
        power: 54,
        skill: 'firearms',
        handling: 'normal',
        ranges: ['close', 'medium'],
        ammoId: 'ammo_rifle',
        ammoPerShot: 1,
      },
      {
        name: 'Buttstroke',
        damageType: 'blunt',
        power: 25,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    properties: ['Two-handed', 'Loud'],
  },

  // -------------------------------------------------------------------------
  // Weapons — energy
  // -------------------------------------------------------------------------
  {
    id: 'laser_pistol',
    name: 'Laser Pistol',
    category: 'weapon',
    basePrice: 480,
    weight: 2,
    stackable: false,
    description: 'A cell-fed beam sidearm that makes almost no noise and leaves a cauterised hole.',
    attacks: [
      {
        name: 'Beam',
        damageType: 'burn',
        power: 46,
        skill: 'energyWeapons',
        handling: 'fast',
        ranges: ['engaged', 'close', 'medium'],
        ammoId: 'energy_cell',
        ammoPerShot: 1,
      },
    ],
    properties: ['Silent'],
  },
  {
    id: 'laser_carbine',
    name: 'Laser Carbine',
    category: 'weapon',
    basePrice: 980,
    weight: 6,
    stackable: false,
    description: 'A two-handed beam weapon with a heat sink deep enough to hold a shot on target.',
    attacks: [
      {
        name: 'Beam',
        damageType: 'burn',
        power: 62,
        skill: 'energyWeapons',
        handling: 'normal',
        ranges: ['close', 'medium', 'long'],
        ammoId: 'energy_cell',
        ammoPerShot: 2,
      },
      {
        name: 'Sustained Beam',
        damageType: 'burn',
        power: 72,
        skill: 'energyWeapons',
        handling: 'slow',
        ranges: ['medium', 'long'],
        ammoId: 'energy_cell',
        ammoPerShot: 5,
      },
    ],
    properties: ['Two-handed', 'Silent'],
  },
  {
    id: 'plasma_lance',
    name: 'Plasma Lance',
    category: 'weapon',
    basePrice: 2100,
    weight: 13,
    bulky: true,
    stackable: false,
    description:
      'A mining lance repurposed for boarding, throwing a contained bolt that opens armour and bulkhead alike.',
    attacks: [
      {
        name: 'Lance',
        damageType: 'burn',
        power: 84,
        skill: 'energyWeapons',
        handling: 'verySlow',
        ranges: ['close', 'medium'],
        ammoId: 'plasma_charge',
        ammoPerShot: 1,
      },
      {
        name: 'Vent Wash',
        damageType: 'burn',
        power: 58,
        skill: 'energyWeapons',
        handling: 'slow',
        ranges: ['engaged', 'close'],
        ammoId: 'plasma_charge',
        ammoPerShot: 1,
      },
    ],
    properties: ['Two-handed', 'Cuts through bulkheads'],
  },
  {
    id: 'arc_projector',
    name: 'Arc Projector',
    category: 'weapon',
    basePrice: 760,
    weight: 5,
    stackable: false,
    description:
      'A shoulder-braced coil that throws a disabling arc at anything conductive within a few metres.',
    attacks: [
      {
        name: 'Arc',
        damageType: 'stun',
        power: 58,
        skill: 'energyWeapons',
        handling: 'normal',
        ranges: ['engaged', 'close'],
        ammoId: 'energy_cell',
        ammoPerShot: 3,
      },
      {
        name: 'Overload Discharge',
        damageType: 'burn',
        power: 50,
        skill: 'energyWeapons',
        handling: 'slow',
        ranges: ['engaged'],
        ammoId: 'energy_cell',
        ammoPerShot: 6,
      },
    ],
    properties: ['Two-handed', 'Non-lethal'],
  },
  {
    id: 'stun_baton',
    name: 'Stun Baton',
    category: 'weapon',
    basePrice: 210,
    weight: 2,
    stackable: false,
    description:
      'A weighted baton with a discharge head, standard issue where killing a prisoner is a problem.',
    attacks: [
      {
        name: 'Jolt',
        damageType: 'stun',
        power: 44,
        skill: 'meleeWeapons',
        handling: 'fast',
        ranges: ['engaged'],
        ammoId: 'energy_cell',
        ammoPerShot: 1,
      },
      {
        name: 'Strike',
        damageType: 'blunt',
        power: 26,
        skill: 'meleeWeapons',
        handling: 'fast',
        ranges: ['engaged'],
      },
    ],
    properties: ['Non-lethal'],
  },
  {
    id: 'shock_prod',
    name: 'Shock Prod',
    category: 'weapon',
    basePrice: 130,
    weight: 3,
    stackable: false,
    description: 'A livestock prod rewired for people, unpleasant rather than genuinely dangerous.',
    attacks: [
      {
        name: 'Prod',
        damageType: 'stun',
        power: 38,
        skill: 'meleeWeapons',
        handling: 'normal',
        ranges: ['engaged'],
        ammoId: 'energy_cell',
        ammoPerShot: 1,
      },
    ],
    properties: ['Non-lethal'],
  },

  // -------------------------------------------------------------------------
  // Weapons — melee and improvised
  // -------------------------------------------------------------------------
  {
    id: 'combat_knife',
    name: 'Combat Knife',
    category: 'weapon',
    basePrice: 95,
    weight: 1,
    stackable: false,
    description: 'A full-tang fighting knife with a blackened blade and a grip that works in gloves.',
    attacks: [
      {
        name: 'Slash',
        damageType: 'slash',
        power: 38,
        skill: 'meleeWeapons',
        handling: 'veryFast',
        ranges: ['engaged'],
      },
      {
        name: 'Thrust',
        damageType: 'pierce',
        power: 40,
        skill: 'meleeWeapons',
        handling: 'fast',
        ranges: ['engaged'],
      },
    ],
    properties: ['Silent'],
  },
  {
    id: 'utility_knife',
    name: 'Utility Knife',
    category: 'weapon',
    basePrice: 25,
    weight: 1,
    stackable: false,
    description: 'A short work knife for cutting strapping, insulation and packing seal.',
    attacks: [
      {
        name: 'Cut',
        damageType: 'slash',
        power: 32,
        skill: 'meleeWeapons',
        handling: 'veryFast',
        ranges: ['engaged'],
      },
    ],
    toolBonus: [{ skill: 'scavenging', value: 4 }],
    properties: ['Silent'],
  },
  {
    id: 'machete',
    name: 'Machete',
    category: 'weapon',
    basePrice: 70,
    weight: 3,
    stackable: false,
    description:
      'A heavy chopping blade carried on green worlds for clearing growth, and kept for other reasons.',
    attacks: [
      {
        name: 'Chop',
        damageType: 'slash',
        power: 48,
        skill: 'meleeWeapons',
        handling: 'fast',
        ranges: ['engaged'],
      },
    ],
    toolBonus: [{ skill: 'exploration', value: 4 }],
    properties: ['Silent'],
  },
  {
    id: 'pipe_wrench',
    name: 'Pipe Wrench',
    category: 'weapon',
    basePrice: 30,
    weight: 5,
    stackable: false,
    description: 'A long steel wrench sized for pipe unions, heavy enough at the head to matter.',
    attacks: [
      {
        name: 'Swing',
        damageType: 'blunt',
        power: 44,
        skill: 'striking',
        handling: 'slow',
        ranges: ['engaged'],
      },
    ],
    toolBonus: [{ skill: 'mechanicalEngineering', value: 4 }],
    properties: ['Improvised'],
  },
  {
    id: 'crowbar',
    name: 'Crowbar',
    category: 'weapon',
    basePrice: 22,
    weight: 4,
    stackable: false,
    description: 'A forged pry bar for crates, jammed hatches and stubborn access panels.',
    attacks: [
      {
        name: 'Pry Strike',
        damageType: 'blunt',
        power: 42,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
      {
        name: 'Hook',
        damageType: 'pierce',
        power: 34,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    toolBonus: [
      { skill: 'lockpicking', value: 4 },
      { skill: 'scavenging', value: 4 },
    ],
    properties: ['Improvised'],
  },
  {
    id: 'mining_pick',
    name: 'Mining Pick',
    category: 'weapon',
    basePrice: 60,
    weight: 6,
    stackable: false,
    description: 'A hafted pick with a hardened point, made for breaking rock and thin plate.',
    attacks: [
      {
        name: 'Pick',
        damageType: 'pierce',
        power: 56,
        skill: 'meleeWeapons',
        handling: 'slow',
        ranges: ['engaged'],
      },
      {
        name: 'Haft Strike',
        damageType: 'blunt',
        power: 30,
        skill: 'meleeWeapons',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    toolBonus: [{ skill: 'scavenging', value: 5 }],
    properties: ['Two-handed'],
  },
  {
    id: 'riot_baton',
    name: 'Riot Baton',
    category: 'weapon',
    basePrice: 55,
    weight: 2,
    stackable: false,
    description:
      'A polymer baton with a side handle, meant to control a crowd without killing anyone in it.',
    attacks: [
      {
        name: 'Strike',
        damageType: 'blunt',
        power: 34,
        skill: 'meleeWeapons',
        handling: 'fast',
        ranges: ['engaged'],
      },
    ],
    properties: ['Non-lethal'],
  },
  {
    id: 'boarding_axe',
    name: 'Boarding Axe',
    category: 'weapon',
    basePrice: 185,
    weight: 5,
    stackable: false,
    description: 'A long-hafted axe with a back spike, carried by dock crews for hatches and hoses.',
    attacks: [
      {
        name: 'Chop',
        damageType: 'slash',
        power: 58,
        skill: 'meleeWeapons',
        handling: 'slow',
        ranges: ['engaged'],
      },
      {
        name: 'Hook',
        damageType: 'pierce',
        power: 44,
        skill: 'meleeWeapons',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    properties: ['Two-handed'],
  },
  {
    id: 'cutting_spear',
    name: 'Cutting Spear',
    category: 'weapon',
    basePrice: 240,
    weight: 5,
    stackable: false,
    description: 'A long-hafted blade for keeping boarders at arm’s length in a narrow corridor.',
    attacks: [
      {
        name: 'Thrust',
        damageType: 'pierce',
        power: 60,
        skill: 'meleeWeapons',
        handling: 'normal',
        ranges: ['engaged'],
      },
      {
        name: 'Sweep',
        damageType: 'slash',
        power: 42,
        skill: 'meleeWeapons',
        handling: 'slow',
        ranges: ['engaged'],
      },
    ],
    properties: ['Two-handed'],
  },
  {
    id: 'improvised_club',
    name: 'Improvised Club',
    category: 'weapon',
    basePrice: 4,
    weight: 3,
    stackable: false,
    description: 'A length of conduit wrapped in tape, made in ten minutes by someone who needed it.',
    attacks: [
      {
        name: 'Swing',
        damageType: 'blunt',
        power: 30,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    properties: ['Improvised'],
  },
  {
    id: 'flare_gun',
    name: 'Flare Gun',
    category: 'weapon',
    basePrice: 65,
    weight: 2,
    stackable: false,
    description:
      'A single-shot signal pistol whose cartridge burns hot enough to be used in anger.',
    attacks: [
      {
        name: 'Fire Flare',
        damageType: 'burn',
        power: 40,
        skill: 'firearms',
        handling: 'normal',
        ranges: ['close', 'medium'],
        ammoId: 'flare_cartridge',
        ammoPerShot: 1,
      },
    ],
    properties: ['Single shot', 'Loud'],
  },
  {
    id: 'nail_driver',
    name: 'Nail Driver',
    category: 'weapon',
    basePrice: 110,
    weight: 4,
    stackable: false,
    description:
      'A charge-fired fastener tool that drives a steel nail through plate at very short range.',
    attacks: [
      {
        name: 'Drive',
        damageType: 'pierce',
        power: 44,
        skill: 'firearms',
        handling: 'fast',
        ranges: ['engaged', 'close'],
        ammoId: 'ammo_pistol',
        ammoPerShot: 1,
      },
      {
        name: 'Hammer',
        damageType: 'blunt',
        power: 24,
        skill: 'striking',
        handling: 'normal',
        ranges: ['engaged'],
      },
    ],
    toolBonus: [{ skill: 'mechanicalEngineering', value: 4 }],
    properties: ['Improvised', 'Loud'],
  },
  {
    id: 'grenade_frag',
    name: 'Fragmentation Grenade',
    category: 'weapon',
    basePrice: 140,
    weight: 1,
    stackable: true,
    description:
      'A fragmentation charge with a short fuse, effective in the open and reckless indoors.',
    attacks: [
      {
        name: 'Throw',
        damageType: 'pierce',
        power: 76,
        skill: 'explosives',
        handling: 'slow',
        ranges: ['close', 'medium'],
        ammoId: 'grenade_frag',
        ammoPerShot: 1,
      },
    ],
    properties: ['Thrown', 'Loud', 'Single shot'],
  },
  {
    id: 'grenade_smoke',
    name: 'Smoke Grenade',
    category: 'weapon',
    basePrice: 70,
    weight: 1,
    stackable: true,
    description:
      'A smoke canister that fills a compartment fast and covers a withdrawal or a boarding.',
    attacks: [
      {
        name: 'Throw',
        damageType: 'stun',
        power: 22,
        skill: 'explosives',
        handling: 'slow',
        ranges: ['close', 'medium'],
        ammoId: 'grenade_smoke',
        ammoPerShot: 1,
      },
    ],
    properties: ['Thrown', 'Non-lethal', 'Single shot'],
  },

  // -------------------------------------------------------------------------
  // Ammunition — one unit is one shot, so weight and price are per round
  // -------------------------------------------------------------------------
  {
    id: 'ammo_pistol',
    name: 'Pistol Rounds',
    category: 'ammo',
    basePrice: 3,
    weight: 0.05,
    stackable: true,
    description: 'Loose pistol cartridges, the most common round anywhere people are still shooting.',
  },
  {
    id: 'ammo_rifle',
    name: 'Rifle Rounds',
    category: 'ammo',
    basePrice: 5,
    weight: 0.08,
    stackable: true,
    description: 'Full-power rifle cartridges, sold by the box and hoarded by the case.',
  },
  {
    id: 'ammo_shotgun',
    name: 'Shotgun Shells',
    category: 'ammo',
    basePrice: 4,
    weight: 0.07,
    stackable: true,
    description: 'Mixed shotgun shells, buckshot and slug, the standard load for shipboard work.',
  },
  {
    id: 'energy_cell',
    name: 'Energy Cell',
    category: 'ammo',
    basePrice: 14,
    weight: 0.3,
    stackable: true,
    description: 'A charged cell that drives one discharge from a beam weapon or a cutting tool.',
  },
  {
    id: 'plasma_charge',
    name: 'Plasma Charge',
    category: 'ammo',
    basePrice: 85,
    weight: 1.2,
    stackable: true,
    description:
      'A sealed containment charge for a plasma weapon, expensive and unsafe to store carelessly.',
  },
  {
    id: 'flare_cartridge',
    name: 'Flare Cartridge',
    category: 'ammo',
    basePrice: 8,
    weight: 0.15,
    stackable: true,
    description: 'A signal cartridge that burns bright red for close to a minute.',
  },

  // -------------------------------------------------------------------------
  // Armor — listed protection is the value at 100% condition
  // -------------------------------------------------------------------------
  {
    id: 'vest_padded',
    name: 'Padded Vest',
    category: 'armor',
    basePrice: 90,
    weight: 4,
    stackable: false,
    description: 'A quilted work vest that spreads impact well and does nothing against a blade point.',
    protection: { blunt: 26, stun: 10, slash: 12, pierce: 6 },
  },
  {
    id: 'vest_ballistic',
    name: 'Ballistic Vest',
    category: 'armor',
    basePrice: 420,
    weight: 7,
    stackable: false,
    description: 'A layered ballistic vest with front and back panels, the standard answer to gunfire.',
    protection: { pierce: 38, slash: 22, blunt: 16, burn: 6 },
  },
  {
    id: 'vest_riot',
    name: 'Riot Vest',
    category: 'armor',
    basePrice: 330,
    weight: 8,
    stackable: false,
    description: 'A segmented riot vest with impact shells and an insulating liner over the torso.',
    protection: { blunt: 40, stun: 34, slash: 24, pierce: 12, burn: 8 },
  },
  {
    id: 'hardsuit_work',
    name: 'Work Hardsuit',
    category: 'armor',
    basePrice: 900,
    weight: 14,
    bulky: true,
    stackable: false,
    description:
      'A sealed industrial hardsuit built for hot work, slow to move in but hard to hurt through.',
    protection: { burn: 34, blunt: 26, slash: 24, pierce: 20, stun: 18 },
    properties: ['Sealed'],
  },
  {
    id: 'hardsuit_void',
    name: 'Void Hardsuit',
    category: 'armor',
    basePrice: 2400,
    weight: 15,
    bulky: true,
    stackable: false,
    description:
      'A rated void hardsuit with sealed joints and a full life support harness, the best protection most crews will ever wear.',
    protection: { burn: 44, slash: 36, blunt: 34, pierce: 32, stun: 26 },
    properties: ['Sealed', 'Vacuum rated'],
  },
  {
    id: 'helmet_industrial',
    name: 'Industrial Helmet',
    category: 'armor',
    basePrice: 70,
    weight: 2,
    stackable: false,
    description:
      'A hard hat with a face shield and hearing seal, made for falling tools rather than gunfire.',
    protection: { blunt: 20, burn: 10, slash: 8, stun: 6 },
  },
  {
    id: 'helmet_combat',
    name: 'Combat Helmet',
    category: 'armor',
    basePrice: 260,
    weight: 3,
    stackable: false,
    description: 'A ballistic helmet with a mandible guard and a comm set that still works.',
    protection: { pierce: 24, blunt: 22, slash: 16, stun: 10 },
  },
  {
    id: 'jacket_reinforced',
    name: 'Reinforced Jacket',
    category: 'armor',
    basePrice: 130,
    weight: 3,
    stackable: false,
    description: 'A work jacket with woven cut-resistant panels sewn into the arms and chest.',
    protection: { slash: 22, blunt: 12, pierce: 8, burn: 6 },
  },
  {
    id: 'plate_carrier',
    name: 'Plate Carrier',
    category: 'armor',
    basePrice: 780,
    weight: 11,
    stackable: false,
    description:
      'A carrier holding hard rifle plates front and back, heavy across the shoulders after an hour.',
    protection: { pierce: 48, slash: 32, blunt: 30, burn: 12 },
  },
  {
    id: 'shield_slab',
    name: 'Shield Slab',
    category: 'armor',
    basePrice: 240,
    weight: 13,
    bulky: true,
    stackable: false,
    description:
      'A cut section of bulkhead with a welded handle, carried by people expecting a corridor fight.',
    protection: { blunt: 44, slash: 42, pierce: 26, stun: 20 },
    properties: ['Two-handed'],
  },

  // -------------------------------------------------------------------------
  // Trade goods — bulk cargo, priced against ECONOMY scarcity multipliers
  // -------------------------------------------------------------------------
  {
    id: 'trade_ore_crate',
    name: 'Ore Crate',
    category: 'tradeGood',
    basePrice: 220,
    weight: 30,
    bulky: true,
    stackable: true,
    description:
      'A sealed crate of unrefined ore, priced by mass and worth carrying only to where refining still happens.',
  },
  {
    id: 'trade_rare_minerals',
    name: 'Rare Minerals',
    category: 'tradeGood',
    basePrice: 900,
    weight: 14,
    bulky: true,
    stackable: true,
    description: 'A shielded case of rare-earth concentrate, valuable enough that the case is locked.',
  },
  {
    id: 'trade_volatiles',
    name: 'Volatiles',
    category: 'tradeGood',
    basePrice: 340,
    weight: 18,
    bulky: true,
    stackable: true,
    description:
      'Pressurised volatiles drawn from ice, needed anywhere a refinery is still running.',
  },
  {
    id: 'trade_chemicals',
    name: 'Industrial Chemicals',
    category: 'tradeGood',
    basePrice: 280,
    weight: 16,
    bulky: true,
    stackable: true,
    description: 'Drummed industrial chemicals, in demand wherever manufacturing has not stopped.',
  },
  {
    id: 'trade_produce',
    name: 'Produce Crate',
    category: 'tradeGood',
    basePrice: 160,
    weight: 20,
    bulky: true,
    stackable: true,
    description:
      'A refrigerated crate of station-grown food, sellable at a hungry port or opened when the galley runs dry.',
    foodDays: 12,
  },
  {
    id: 'trade_machine_parts',
    name: 'Machine Parts',
    category: 'tradeGood',
    basePrice: 400,
    weight: 22,
    bulky: true,
    stackable: true,
    description:
      'A pallet of machined components that can be traded whole or broken down for shipboard repairs.',
    repairParts: 24,
  },
  {
    id: 'trade_ice_block',
    name: 'Ice Block',
    category: 'tradeGood',
    basePrice: 90,
    weight: 26,
    bulky: true,
    stackable: true,
    description:
      'A cut block of dirty water ice, processed at the far end into drinking water and reaction mass.',
  },
  {
    id: 'trade_textiles',
    name: 'Textile Bale',
    category: 'tradeGood',
    basePrice: 190,
    weight: 10,
    stackable: true,
    description:
      'Baled synthetic cloth, light for its value and always wanted where nothing is manufactured.',
  },

  // -------------------------------------------------------------------------
  // Valuables
  // -------------------------------------------------------------------------
  {
    id: 'data_core',
    name: 'Data Core',
    category: 'valuable',
    basePrice: 600,
    weight: 1,
    stackable: false,
    description:
      'A sealed archive core holding survey data, records, or something the last owner did not want read.',
  },
  {
    id: 'salvage_scrap',
    name: 'Salvage Scrap',
    category: 'valuable',
    basePrice: 12,
    weight: 3,
    stackable: true,
    description: 'Sorted scrap and stripped fittings, worth little each but always worth something.',
    repairParts: 1,
  },
  {
    id: 'heirloom_watch',
    name: 'Heirloom Watch',
    category: 'valuable',
    basePrice: 350,
    weight: 1,
    stackable: false,
    description:
      'A mechanical watch that still keeps time, carried out of a house that no longer exists.',
  },
  {
    id: 'antique_navcomp',
    name: 'Antique Navcomp',
    category: 'valuable',
    basePrice: 820,
    weight: 6,
    stackable: false,
    description:
      'An old navigation computer with its tables intact, slower than a modern unit but never wrong.',
    toolBonus: [{ skill: 'navigation', value: 6 }],
  },
  {
    id: 'personal_effects',
    name: 'Personal Effects',
    category: 'valuable',
    basePrice: 40,
    weight: 2,
    stackable: false,
    description:
      'A bundle of somebody’s belongings, worth little except to whoever is still looking for them.',
  },
];
