/**
 * NAMES AND LIFE PATHS — pure authored data, no logic.
 *
 * Names are a single undifferentiated pool. The generator assigns pronouns
 * independently, so nothing here is tagged or grouped by gender.
 *
 * Life paths do not set stats. They nudge generation:
 * - `skillBias` (+4..+18) shifts exposure bands. Careers are the strongest signal.
 * - `attributeBias` (-2..+3) is carried mostly by origins and upbringings.
 * - `traitBias` (+1..+4) is carried mostly by formative events.
 * - `weight` defaults to 10; 4-8 marks an unusual path, 12-16 a common one.
 *
 * Biases are tendencies, not verdicts. A hard path is allowed to leave someone
 * steadier, and a comfortable one is allowed to leave someone brittle.
 */

import type { NameTables, LifePathTables } from './contentTypes';

export const NAME_TABLES: NameTables = {
  given: [
    'Abeni', 'Ada', 'Adaeze', 'Aki', 'Altan', 'Amani', 'Amira', 'Anahita',
    'Anaya', 'Anong', 'Anya', 'Aroha', 'Arun', 'Asha', 'Aselya', 'Aygul',
    'Ayu', 'Bao', 'Baraka', 'Bayani', 'Beatriz', 'Bekzat', 'Bess', 'Bilal',
    'Bjorn', 'Bohdan', 'Bram', 'Camila', 'Carmo', 'Chen', 'Chidi', 'Colm',
    'Dara', 'Darya', 'Dawit', 'Devi', 'Diego', 'Dragan', 'Duarte', 'Eirik',
    'Emeka', 'Emre', 'Farid', 'Femi', 'Freya', 'Gwen', 'Halima', 'Halvor',
    'Hana', 'Haruki', 'Hoang', 'Iker', 'Indra', 'Ines', 'Ingrid', 'Intan',
    'Jelani', 'Jin', 'Joaquim', 'Kaito', 'Kalani', 'Kanat', 'Karim', 'Katya',
    'Kaveh', 'Kiran', 'Kofi', 'Kwabena', 'Kwame', 'Layla', 'Leif', 'Ling',
    'Linh', 'Malee', 'Malia', 'Marisol', 'Marlow', 'Mateo', 'Meera', 'Mei',
    'Milena', 'Minjun', 'Moana', 'Nadia', 'Nara', 'Nasrin', 'Nell', 'Ngozi',
    'Nikhil', 'Nikolai', 'Nuno', 'Nuru', 'Nurul', 'Obi', 'Paloma', 'Parviz',
    'Priya', 'Radek', 'Rangi', 'Rashid', 'Ravi', 'Rhodri', 'Rhys', 'Rizal',
    'Rosario', 'Roshan', 'Runa', 'Ryo', 'Sade', 'Sahil', 'Sam', 'Samir',
    'Santiago', 'Sefa', 'Selam', 'Seo', 'Shirin', 'Sigrid', 'Solveig', 'Somchai',
    'Sora', 'Sten', 'Tane', 'Tara', 'Tesfaye', 'Tess', 'Thanh', 'Timur',
    'Tomasz', 'Tove', 'Tui', 'Vaea', 'Vesna', 'Vikram', 'Wei', 'Wren',
    'Ximena', 'Yaw', 'Yuna', 'Yusuf', 'Zahra', 'Zarina', 'Zora', 'Zuri',
  ],

  surnames: [
    'Abara', 'Adeyemi', 'Akhtar', 'Almeida', 'Andersen', 'Aoki', 'Arslan',
    'Baptiste', 'Bekele', 'Berhane', 'Bhatt', 'Bonifacio', 'Cabrera',
    'Castellanos', 'Chatterjee', 'Cheng', 'Costa', 'Dagher', 'Danielsen',
    'Dlamini', 'Duarte', 'Eriksen', 'Espinoza', 'Farrokh', 'Ferreira',
    'Ghorbani', 'Gutierrez', 'Haddad', 'Hassan', 'Havlik', 'Herrera',
    'Hidalgo', 'Hoxha', 'Ibarra', 'Ishikawa', 'Iyer', 'Jansen', 'Jimenez',
    'Kahale', 'Kamau', 'Karimov', 'Kasprzak', 'Khan', 'Kirov', 'Kobayashi',
    'Kouadio', 'Kovac', 'Krishnan', 'Kurniawan', 'Laghari', 'Larsen',
    'Lindqvist', 'Machado', 'Magalhaes', 'Mansour', 'Marchetti', 'Mendoza',
    'Mensah', 'Mihaylov', 'Moreno', 'Mwangi', 'Nakamura', 'Navarro', 'Nguyen',
    'Nomura', 'Novak', 'Nurlanov', 'Obeng', 'Okafor', 'Okonkwo', 'Oliveira',
    'Osei', 'Parsa', 'Pereira', 'Petrov', 'Phan', 'Pillai', 'Prasetyo',
    'Quintero', 'Rahimi', 'Ramaswamy', 'Rasmussen', 'Reyes', 'Rios', 'Sadiq',
    'Salazar', 'Sandoval', 'Santos', 'Sarr', 'Sato', 'Sepulveda', 'Shevchenko',
    'Silva', 'Sinclair', 'Solberg', 'Sultanov', 'Suzuki', 'Tadesse', 'Tahir',
    'Takahashi', 'Tran', 'Vasquez', 'Vidal', 'Vukovic', 'Wachira', 'Wanjiru',
    'Whitlock', 'Yamada', 'Yildiz', 'Zaman', 'Zhao', 'Zielinski',
  ],

  shipPrefixes: [
    'Long', 'Second', 'Patient', 'Quiet', 'Stubborn', 'Salt', 'Iron', 'Bright',
    'Old', 'Little', 'Steady', 'Cold', 'Grey', 'Slow', 'Honest', 'Lucky',
    'Blue', 'Deep', 'Far', 'Half', 'Last', 'Low', 'New', 'Plain',
    'Red', 'Rough', 'Sure', 'Tall', 'Third', 'True', 'Wide', 'Winter',
    'Dry', 'Fair', 'Hard', 'Kind', 'Near', 'Open', 'Small', 'Still',
    'Thin', 'Warm', 'Brass', 'Copper', 'Broad', 'Even',
  ],

  shipNouns: [
    'Furrow', 'Marrow', 'Anchor', 'Lantern', 'Crossing', 'Harbour', 'Threshold',
    'Kettle', 'Ladder', 'Bellows', 'Hearth', 'Ferry', 'Barrow', 'Tiller',
    'Cradle', 'Coil', 'Handhold', 'Fathom', 'Beacon', 'Grain', 'Errand',
    'Hinge', 'Ledger', 'Keel', 'Almanac', 'Reckoning', 'Sparrow', 'Tinder',
    'Winch', 'Yoke', 'Bushel', 'Compass', 'Gate', 'Kindling', 'Loom',
    'Mooring', 'Notch', 'Orchard', 'Shuttle', 'Trestle', 'Waypoint',
    'Whetstone', 'Kiln', 'Millstone', 'Ration', 'Shepherd', 'Stanchion', 'Lamp',
  ],
};

export const LIFE_PATHS: LifePathTables = {
  // -------------------------------------------------------------------------
  // ORIGINS — where they are from. Mostly attribute pressure, light on skills.
  // -------------------------------------------------------------------------
  origins: [
    {
      id: 'orbital-creche',
      label: 'Orbital Creche',
      text: 'raised in an orbital creche where the lights never fully went down and forty children shared one corridor',
      skillBias: { computers: 6, persuasion: 5, stealth: 4 },
      attributeBias: { socialAwareness: 2, composure: 1, strength: -1 },
      traitBias: { cooperative: 2 },
      weight: 10,
    },
    {
      id: 'moon-rotation',
      label: 'Moon Rotation',
      text: 'grew up on a moon rotation, three months on and one month home',
      skillBias: { mechanicalEngineering: 6, scavenging: 5, exploration: 4 },
      attributeBias: { endurance: 2, discipline: 1, socialAwareness: -1 },
      traitBias: { patient: 2, dutiful: 1 },
      weight: 14,
    },
    {
      id: 'agricultural-belt',
      label: 'Agricultural Belt',
      text: 'from the homeworld agricultural belt, where the season decided everything and nobody argued with it',
      skillBias: { cooking: 7, exploration: 5, mechanicalEngineering: 4 },
      attributeBias: { endurance: 2, strength: 1, reasoning: -1 },
      traitBias: { patient: 3, stubborn: 1 },
      weight: 14,
    },
    {
      id: 'arcology-district',
      label: 'Arcology District',
      text: 'raised in a dense arcology district, eleven thousand people to a floor and every one of them known by sight',
      skillBias: { persuasion: 6, stealth: 5, negotiation: 4 },
      attributeBias: { socialAwareness: 2, perception: 1, endurance: -1 },
      traitBias: { cooperative: 1, opportunistic: 1 },
      weight: 14,
    },
    {
      id: 'freight-family',
      label: 'Freight Family',
      text: 'born into a freight family, schooled between ports and never in one classroom twice',
      skillBias: { piloting: 7, navigation: 6, negotiation: 5 },
      attributeBias: { handEye: 1, evaluation: 1, discipline: -1 },
      traitBias: { curious: 1, loyal: 1 },
      weight: 12,
    },
    {
      id: 'coastal-fishing-town',
      label: 'Coastal Fishing Town',
      text: 'out of a coastal fishing town that read weather better than it read anything else',
      skillBias: { exploration: 6, cooking: 5, mechanicalEngineering: 4 },
      attributeBias: { endurance: 2, perception: 2, learning: -1 },
      traitBias: { stubborn: 2, patient: 1 },
      weight: 10,
    },
    {
      id: 'research-enclave',
      label: 'Research Enclave',
      text: 'from a research enclave where the adults spoke in citations and the children were expected to keep up',
      skillBias: { medicalResearch: 7, computers: 6, medicalDiagnostics: 4 },
      attributeBias: { learning: 3, reasoning: 2, strength: -2 },
      traitBias: { curious: 3 },
      weight: 6,
    },
    {
      id: 'mining-settlement',
      label: 'Mining Settlement',
      text: 'grew up in a mining settlement built around a shaft head and abandoned when the seam ran out',
      skillBias: { explosives: 6, scavenging: 6, mechanicalEngineering: 5 },
      attributeBias: { strength: 2, endurance: 2, charisma: -1 },
      traitBias: { stubborn: 2, loyal: 1 },
      weight: 12,
    },
    {
      id: 'resettlement-block',
      label: 'Resettlement Block',
      text: 'spent childhood in a refugee resettlement block, on a list, waiting for a number to be called',
      skillBias: { scavenging: 6, persuasion: 5, cooking: 4 },
      attributeBias: { resilience: 2, perception: 1, charisma: -1 },
      traitBias: { suspicious: 2, selfPreserving: 1, cooperative: 1 },
      weight: 10,
    },
    {
      id: 'transit-born',
      label: 'Transit-Station Born',
      text: 'born on a transit station between two places, belonging properly to neither',
      skillBias: { negotiation: 6, navigation: 5, persuasion: 4 },
      attributeBias: { socialAwareness: 2, evaluation: 1, strength: -1 },
      traitBias: { opportunistic: 2, curious: 1 },
      weight: 10,
    },
    {
      id: 'isolated-homestead',
      label: 'Isolated Homestead',
      text: 'from an isolated homestead where the nearest neighbour was four hours out and help was a theory',
      skillBias: { firstAid: 6, mechanicalEngineering: 5, exploration: 5 },
      attributeBias: { endurance: 2, resilience: 2, socialAwareness: -2 },
      traitBias: { stubborn: 2, suspicious: 1, brave: 1 },
      weight: 8,
    },
    {
      id: 'industrial-arcology',
      label: 'Industrial Arcology',
      text: 'raised under the shift horns of an industrial arcology, where the air tasted of flux and everyone the same age worked the same floor',
      skillBias: { electricalEngineering: 6, mechanicalEngineering: 6, weaponsmithing: 4 },
      attributeBias: { endurance: 2, discipline: 2, learning: -1 },
      traitBias: { dutiful: 2, cooperative: 1 },
      weight: 14,
    },
    {
      id: 'seasonal-labour',
      label: 'Seasonal Labour Circuit',
      text: 'followed the seasonal labour circuit as a child, six addresses a year and none of them permanent',
      skillBias: { exploration: 6, negotiation: 5, scavenging: 5 },
      attributeBias: { endurance: 2, agility: 1, memory: -1 },
      traitBias: { cooperative: 2, opportunistic: 1 },
      weight: 10,
    },
    {
      id: 'hospital-district',
      label: 'Hospital District',
      text: 'grew up in a hospital district where sirens were background noise and everybody knew a nurse',
      skillBias: { firstAid: 7, medicalDiagnostics: 5, persuasion: 4 },
      attributeBias: { composure: 2, socialAwareness: 1 },
      traitBias: { compassionate: 2, dutiful: 1 },
      weight: 10,
    },
    {
      id: 'shipbreaking-yard',
      label: 'Shipbreaking Yard',
      text: 'raised at the edge of a shipbreaking yard, where most of the furniture in town came out of dead hulls',
      skillBias: { scavenging: 7, mechanicalEngineering: 5, weaponsmithing: 4 },
      attributeBias: { strength: 2, evaluation: 1, discipline: -1 },
      traitBias: { opportunistic: 2, curious: 1 },
      weight: 10,
    },
    {
      id: 'dock-ring',
      label: 'Dock Ring',
      text: 'grew up on a dock ring, doing schoolwork on a gantry while the loaders worked below',
      skillBias: { mechanicalEngineering: 5, piloting: 5, negotiation: 4 },
      attributeBias: { agility: 2, handEye: 1, endurance: 1 },
      traitBias: { cooperative: 1, brave: 1 },
      weight: 12,
    },
  ],

  // -------------------------------------------------------------------------
  // UPBRINGINGS — how they were raised. Attributes plus real trait pressure.
  // -------------------------------------------------------------------------
  upbringings: [
    {
      id: 'large-extended-family',
      label: 'Large Extended Family',
      text: 'raised in a large extended family where nine people shared four rooms and no argument stayed private',
      skillBias: { cooking: 5, persuasion: 5, firstAid: 4 },
      attributeBias: { socialAwareness: 2, composure: 1 },
      traitBias: { cooperative: 2, loyal: 2, generous: 1 },
      weight: 14,
    },
    {
      id: 'orphaned-young',
      label: 'Orphaned Young',
      text: 'orphaned young and passed between the households that could take a child that season',
      skillBias: { scavenging: 6, stealth: 5, cooking: 4 },
      attributeBias: { resilience: 3, composure: 1, socialAwareness: -1 },
      traitBias: { selfPreserving: 2, suspicious: 2, cautious: 1 },
      weight: 10,
    },
    {
      id: 'single-parent-double-shifts',
      label: 'Single Parent, Double Shifts',
      text: 'brought up by one parent working double rotations, with a key on a cord and dinner left in the warmer',
      skillBias: { cooking: 6, firstAid: 5, mechanicalEngineering: 4 },
      attributeBias: { discipline: 2, resilience: 1 },
      traitBias: { dutiful: 2, patient: 1, protective: 1 },
      weight: 14,
    },
    {
      id: 'apprenticed-early',
      label: 'Apprenticed Early',
      text: 'apprenticed at thirteen to a trade that took a childhood and gave back a skill',
      skillBias: { mechanicalEngineering: 8, weaponsmithing: 5, electricalEngineering: 4 },
      attributeBias: { proprioception: 2, discipline: 2, learning: -1 },
      traitBias: { dutiful: 2, patient: 2 },
      weight: 12,
    },
    {
      id: 'institutional-schooling',
      label: 'Institutional Schooling',
      text: 'raised in institutional schooling, uniform issued, bed number assigned, a bell for everything',
      skillBias: { computers: 5, firearms: 5, persuasion: 4 },
      attributeBias: { discipline: 3, memory: 1, charisma: -1 },
      traitBias: { dutiful: 2, cautious: 1, stubborn: 1 },
      weight: 12,
    },
    {
      id: 'raised-aboard-ship',
      label: 'Raised Aboard Ship',
      text: 'grew up aboard a working ship, doing sums in the cockpit jump seat',
      skillBias: { piloting: 8, navigation: 6, mechanicalEngineering: 5 },
      attributeBias: { handEye: 2, proprioception: 1, socialAwareness: -1 },
      traitBias: { cooperative: 2, curious: 1 },
      weight: 10,
    },
    {
      id: 'street-raised',
      label: 'Raised on the Walkways',
      text: 'street-raised in a district the authorities had stopped bothering to police',
      skillBias: { stealth: 7, lockpicking: 7, brawling: 5 },
      attributeBias: { agility: 2, perception: 2, discipline: -2 },
      traitBias: { opportunistic: 2, suspicious: 2, reckless: 1 },
      weight: 8,
    },
    {
      id: 'strict-observance',
      label: 'Strict Observance',
      text: 'raised under a strict observance, with a schedule of duties and a very clear account of what a person owes',
      skillBias: { persuasion: 5, firstAid: 5, cooking: 4 },
      attributeBias: { discipline: 3, composure: 2, evaluation: -1 },
      traitBias: { honest: 3, dutiful: 2, stubborn: 1 },
      weight: 10,
    },
    {
      id: 'academically-pushed',
      label: 'Academically Pushed',
      text: 'pushed academically from the first year, with results posted on the kitchen wall',
      skillBias: { computers: 7, medicalResearch: 6, navigation: 4 },
      attributeBias: { learning: 3, reasoning: 2, resilience: -1 },
      traitBias: { curious: 2, controlling: 2, jealous: 1 },
      weight: 8,
    },
    {
      id: 'neglected-self-taught',
      label: 'Neglected, Self-Taught',
      text: 'left to raise themselves, learning everything from manuals and from other people mishandling the job first',
      skillBias: { electricalEngineering: 6, computers: 6, scavenging: 5 },
      attributeBias: { learning: 2, resilience: 2, socialAwareness: -2 },
      traitBias: { curious: 2, stubborn: 2, suspicious: 1 },
      weight: 8,
    },
    {
      id: 'raised-among-strangers',
      label: 'Raised Among Strangers',
      text: 'raised among strangers in a rotating billet system, learning a new set of house rules every year',
      skillBias: { persuasion: 6, negotiation: 5, stealth: 4 },
      attributeBias: { socialAwareness: 3, evaluation: 1, resilience: 1 },
      traitBias: { cautious: 2, cooperative: 1, suspicious: 1 },
      weight: 8,
    },
    {
      id: 'worker-collective',
      label: 'Worker Collective',
      text: 'brought up in a tight worker collective where the shift looked after its own and expected the same back',
      skillBias: { mechanicalEngineering: 5, persuasion: 5, firstAid: 4 },
      attributeBias: { leadership: 1, composure: 1, endurance: 1 },
      traitBias: { loyal: 3, cooperative: 2, dutiful: 1 },
      weight: 14,
    },
    {
      id: 'raised-by-grandparent',
      label: 'Raised by a Grandparent',
      text: 'raised by a grandparent two generations out of step, on stories from a world that no longer existed',
      skillBias: { cooking: 6, firstAid: 5, mechanicalEngineering: 4 },
      attributeBias: { memory: 2, composure: 2, agility: -1 },
      traitBias: { patient: 3, generous: 1, stubborn: 1 },
      weight: 12,
    },
    {
      id: 'moved-constantly',
      label: 'Moved Constantly',
      text: 'moved constantly as a child, never unpacking the second bag',
      skillBias: { negotiation: 5, exploration: 5, persuasion: 4 },
      attributeBias: { socialAwareness: 2, resilience: 1, memory: -1 },
      traitBias: { cautious: 1, opportunistic: 1, selfPreserving: 1 },
      weight: 12,
    },
    {
      id: 'back-room-clinic',
      label: 'Back-Room Clinic',
      text: 'grew up in the back room of an unlicensed clinic, handing over instruments before being old enough to read the labels',
      skillBias: { firstAid: 8, surgery: 5, medicalDiagnostics: 5 },
      attributeBias: { steadiness: 2, composure: 2 },
      traitBias: { compassionate: 2, cautious: 2, dutiful: 1 },
      weight: 6,
    },
    {
      id: 'minded-younger-ones',
      label: 'Minded the Younger Ones',
      text: 'eldest of many, minding younger siblings before being old enough to be minded themselves',
      skillBias: { cooking: 6, firstAid: 5, persuasion: 4 },
      attributeBias: { leadership: 2, composure: 1, resilience: 1 },
      traitBias: { protective: 3, dutiful: 2, patient: 1 },
      weight: 14,
    },
  ],

  // -------------------------------------------------------------------------
  // CAREERS — the strongest skill signal. 3-6 skills each, plus role and venues.
  // -------------------------------------------------------------------------
  careers: [
    {
      id: 'ship-mechanic',
      label: 'Ship Mechanic',
      role: 'engineer',
      venues: ['freightYard', 'workerCamp', 'bar'],
      text: 'spent a decade under deck plating with a torch and a hand light, keeping tired engines honest',
      skillBias: {
        mechanicalEngineering: 18,
        electricalEngineering: 12,
        scavenging: 7,
        weaponsmithing: 5,
        explosives: 4,
      },
      attributeBias: { proprioception: 2, reasoning: 1, endurance: 1 },
      traitBias: { patient: 2, stubborn: 1 },
      weight: 16,
    },
    {
      id: 'hull-welder',
      label: 'Hull Welder',
      role: 'technician',
      venues: ['freightYard', 'workerCamp'],
      text: 'welded hull seam in a suit for eight-hour stretches, watching the bead and nothing else',
      skillBias: {
        mechanicalEngineering: 14,
        weaponsmithing: 8,
        exploration: 6,
        closeQuarters: 4,
      },
      attributeBias: { steadiness: 3, endurance: 2, proprioception: 2 },
      traitBias: { patient: 3, dutiful: 1 },
      weight: 14,
    },
    {
      id: 'freight-pilot',
      label: 'Freight Pilot',
      role: 'pilot',
      venues: ['freightYard', 'bar'],
      text: 'flew freight on unglamorous routes, judged entirely on cargo mass and margins',
      skillBias: { piloting: 18, navigation: 11, negotiation: 6, computers: 5 },
      attributeBias: { handEye: 3, decisionMaking: 2, composure: 1 },
      traitBias: { cautious: 2, patient: 1 },
      weight: 16,
    },
    {
      id: 'orbital-navigator',
      label: 'Orbital Navigator',
      role: 'navigator',
      venues: ['freightYard', 'university'],
      text: 'plotted orbital transfers for a line that fined the crew for every wasted kilo of fuel',
      skillBias: { navigation: 18, computers: 11, piloting: 7, exploration: 5 },
      attributeBias: { reasoning: 3, memory: 2, perception: 2 },
      traitBias: { patient: 2, cautious: 1 },
      weight: 12,
    },
    {
      id: 'field-medic',
      label: 'Field Medic',
      role: 'medic',
      venues: ['clinic', 'refugeeArea', 'securityOffice'],
      text: 'worked trauma in the field, where the light was bad and the decision had to come fast',
      skillBias: {
        firstAid: 18,
        surgery: 9,
        medicalDiagnostics: 8,
        firearms: 5,
        exploration: 4,
      },
      attributeBias: { composure: 3, steadiness: 2, decisionMaking: 2 },
      traitBias: { brave: 2, compassionate: 2 },
      weight: 12,
    },
    {
      id: 'hospital-nurse',
      label: 'Hospital Nurse',
      role: 'medic',
      venues: ['clinic', 'shelter'],
      text: 'ran a ward through night shifts, doing the work that never appears in a case file',
      skillBias: {
        firstAid: 16,
        medicalDiagnostics: 11,
        surgery: 6,
        persuasion: 6,
        cooking: 4,
      },
      attributeBias: { composure: 2, endurance: 2, socialAwareness: 2 },
      traitBias: { compassionate: 3, dutiful: 2, patient: 1 },
      weight: 14,
    },
    {
      id: 'hospital-surgeon',
      label: 'Hospital Surgeon',
      role: 'medic',
      venues: ['clinic', 'university'],
      text: 'cut for a living, and learned to hold a steady conversation while doing it',
      skillBias: { surgery: 18, medicalDiagnostics: 13, firstAid: 10, medicalResearch: 8 },
      attributeBias: { steadiness: 3, proprioception: 2, composure: 2 },
      traitBias: { controlling: 2, dutiful: 1 },
      weight: 6,
    },
    {
      id: 'mine-foreman',
      label: 'Mine Foreman',
      role: 'crew',
      venues: ['mine', 'workerCamp', 'bar'],
      text: 'ran a shift underground and signed for every body that went down and came back up',
      skillBias: {
        explosives: 12,
        mechanicalEngineering: 9,
        exploration: 8,
        persuasion: 7,
        firstAid: 5,
      },
      attributeBias: { leadership: 3, decisionMaking: 2, endurance: 2 },
      traitBias: { dutiful: 2, protective: 2, controlling: 1 },
      weight: 10,
    },
    {
      id: 'drill-operator',
      label: 'Drill Operator',
      role: 'crew',
      venues: ['mine', 'workerCamp'],
      text: 'ran a rig face for years, reading rock by the sound the bit made going in',
      skillBias: { explosives: 13, mechanicalEngineering: 10, exploration: 8, scavenging: 6 },
      attributeBias: { endurance: 3, strength: 2, perception: 2 },
      traitBias: { stubborn: 2, patient: 1 },
      weight: 14,
    },
    {
      id: 'salvage-diver',
      label: 'Salvage Diver',
      role: 'scavenger',
      venues: ['freightYard', 'bar', 'workerCamp'],
      text: 'went into dead hulls on a tether for whatever was still worth pulling out',
      skillBias: {
        scavenging: 18,
        exploration: 11,
        mechanicalEngineering: 7,
        lockpicking: 6,
        stealth: 5,
      },
      attributeBias: { perception: 3, agility: 2, composure: 2 },
      traitBias: { brave: 2, opportunistic: 2, greedy: 1 },
      weight: 12,
    },
    {
      id: 'dock-security',
      label: 'Dock Security',
      role: 'gunner',
      venues: ['securityOffice', 'freightYard', 'bar'],
      text: 'stood dock security on a night gate, mostly boredom and occasionally not',
      skillBias: {
        firearms: 14,
        closeQuarters: 9,
        brawling: 8,
        persuasion: 6,
        stealth: 4,
      },
      attributeBias: { perception: 2, steadiness: 2, discipline: 2 },
      traitBias: { cautious: 2, suspicious: 2, dutiful: 1 },
      weight: 14,
    },
    {
      id: 'militia-rifleman',
      label: 'Militia Rifleman',
      role: 'gunner',
      venues: ['securityOffice', 'workerCamp', 'bar'],
      text: 'carried a rifle for a local militia in a dispute nobody outside the district remembers',
      skillBias: {
        firearms: 16,
        closeQuarters: 10,
        explosives: 7,
        firstAid: 6,
        stealth: 5,
      },
      attributeBias: { steadiness: 2, endurance: 2, discipline: 1 },
      traitBias: { brave: 2, loyal: 2, aggressive: 1 },
      weight: 12,
    },
    {
      id: 'cargo-broker',
      label: 'Cargo Broker',
      role: 'crew',
      venues: ['freightYard', 'bar'],
      text: 'brokered cargo lots on a thin margin, where the whole job was knowing what a thing was actually worth',
      skillBias: { negotiation: 18, persuasion: 12, computers: 7, scavenging: 5 },
      attributeBias: { evaluation: 3, socialAwareness: 2, charisma: 1 },
      traitBias: { opportunistic: 2, greedy: 2 },
      weight: 12,
    },
    {
      id: 'market-trader',
      label: 'Market Trader',
      role: 'crew',
      venues: ['bar', 'refugeeArea', 'freightYard'],
      text: 'worked a market stall where the day\'s takings depended entirely on reading the person in front of them',
      skillBias: { negotiation: 15, persuasion: 13, cooking: 6, scavenging: 5 },
      attributeBias: { charisma: 3, socialAwareness: 2, evaluation: 2 },
      traitBias: { opportunistic: 2, generous: 1 },
      weight: 14,
    },
    {
      id: 'comms-technician',
      label: 'Comms Technician',
      role: 'technician',
      venues: ['freightYard', 'university', 'securityOffice'],
      text: 'kept a relay stack running, patching hardware two decades past its documentation',
      skillBias: {
        electricalEngineering: 16,
        computers: 14,
        mechanicalEngineering: 8,
        navigation: 5,
      },
      attributeBias: { reasoning: 2, memory: 2, steadiness: 1 },
      traitBias: { curious: 2, patient: 1 },
      weight: 14,
    },
    {
      id: 'greenhouse-agronomist',
      label: 'Greenhouse Agronomist',
      role: 'crew',
      venues: ['workerCamp', 'university', 'shelter'],
      text: 'ran hydroponic decks, coaxing yield out of tired substrate and rationed light',
      skillBias: {
        cooking: 12,
        medicalResearch: 9,
        medicalDiagnostics: 6,
        exploration: 6,
        electricalEngineering: 5,
      },
      attributeBias: { perception: 2, learning: 2, discipline: 2 },
      traitBias: { patient: 3, generous: 1 },
      weight: 12,
    },
    {
      id: 'process-operator',
      label: 'Process Operator',
      role: 'technician',
      venues: ['workerCamp', 'mine', 'freightYard'],
      text: 'watched a chemical process line where the whole job was noticing the one number that had drifted',
      skillBias: {
        explosives: 12,
        electricalEngineering: 10,
        medicalResearch: 7,
        mechanicalEngineering: 7,
        firstAid: 5,
      },
      attributeBias: { perception: 3, discipline: 2, composure: 1 },
      traitBias: { cautious: 3, patient: 1 },
      weight: 12,
    },
    {
      id: 'ships-cook',
      label: 'Ship\'s Cook',
      role: 'crew',
      venues: ['freightYard', 'bar', 'shelter'],
      text: 'fed a crew of nine on a stores budget for six, and heard everything said at that table',
      skillBias: {
        cooking: 18,
        persuasion: 9,
        negotiation: 7,
        firstAid: 5,
        medicalDiagnostics: 4,
      },
      attributeBias: { socialAwareness: 3, memory: 2, evaluation: 1 },
      traitBias: { generous: 3, cooperative: 2, patient: 1 },
      weight: 14,
    },
    {
      id: 'district-teacher',
      label: 'District Teacher',
      role: 'crew',
      venues: ['university', 'shelter', 'refugeeArea'],
      text: 'taught a classroom of thirty in a district that kept cutting the budget',
      skillBias: {
        persuasion: 14,
        computers: 8,
        firstAid: 6,
        medicalResearch: 5,
        negotiation: 5,
      },
      attributeBias: { charisma: 2, leadership: 2, memory: 2, composure: 2 },
      traitBias: { patient: 3, compassionate: 2, dutiful: 1 },
      weight: 12,
    },
    {
      id: 'lab-researcher',
      label: 'Lab Researcher',
      role: 'technician',
      venues: ['university', 'clinic'],
      text: 'worked a lab bench on grant cycles, chasing a result somebody else would publish',
      skillBias: {
        medicalResearch: 18,
        computers: 12,
        medicalDiagnostics: 9,
        electricalEngineering: 6,
      },
      attributeBias: { learning: 3, reasoning: 3, endurance: -1 },
      traitBias: { curious: 3, patient: 2, jealous: 1 },
      weight: 8,
    },
    {
      id: 'shop-machinist',
      label: 'Shop Machinist',
      role: 'engineer',
      venues: ['workerCamp', 'freightYard', 'mine'],
      text: 'ran a machine shop to a tolerance nobody inspected but them',
      skillBias: {
        mechanicalEngineering: 16,
        weaponsmithing: 13,
        electricalEngineering: 7,
        scavenging: 5,
      },
      attributeBias: { proprioception: 3, steadiness: 2, evaluation: 1 },
      traitBias: { patient: 2, stubborn: 2, controlling: 1 },
      weight: 12,
    },
    {
      id: 'longshore-loader',
      label: 'Longshore Loader',
      role: 'crew',
      venues: ['freightYard', 'workerCamp', 'bar'],
      text: 'loaded holds by hand and by crane, twelve hours at a time, for most of a working life',
      skillBias: {
        scavenging: 9,
        mechanicalEngineering: 8,
        brawling: 7,
        negotiation: 5,
        striking: 4,
      },
      attributeBias: { strength: 3, endurance: 3, proprioception: 1 },
      traitBias: { cooperative: 2, stubborn: 1 },
      weight: 16,
    },
    {
      id: 'small-freighter-captain',
      label: 'Small-Freighter Captain',
      role: 'captain',
      venues: ['bar', 'freightYard'],
      text: 'captained a small freighter that never quite cleared its debts',
      skillBias: {
        negotiation: 12,
        piloting: 11,
        navigation: 9,
        persuasion: 9,
        mechanicalEngineering: 6,
      },
      attributeBias: { leadership: 3, decisionMaking: 3, evaluation: 2 },
      traitBias: { dutiful: 2, stubborn: 2, controlling: 1 },
      weight: 6,
    },
    {
      id: 'ships-gun-crew',
      label: 'Ship\'s Gun Crew',
      role: 'gunner',
      venues: ['freightYard', 'securityOffice', 'bar'],
      text: 'crewed a defensive turret on a convoy run, mostly drilling for something that happened twice',
      skillBias: {
        shipWeapons: 18,
        firearms: 10,
        weaponsmithing: 8,
        mechanicalEngineering: 6,
        computers: 5,
      },
      attributeBias: { handEye: 3, perception: 2, composure: 2 },
      traitBias: { dutiful: 2, cautious: 1 },
      weight: 10,
    },
    {
      id: 'relief-worker',
      label: 'Relief Worker',
      role: 'crew',
      venues: ['refugeeArea', 'shelter', 'clinic'],
      text: 'handed out rations and registration numbers in a resettlement queue that never got shorter',
      skillBias: {
        firstAid: 11,
        persuasion: 11,
        negotiation: 8,
        cooking: 7,
        medicalDiagnostics: 5,
      },
      attributeBias: { socialAwareness: 3, composure: 2, resilience: 2 },
      traitBias: { compassionate: 3, patient: 2, generous: 1 },
      weight: 12,
    },
    {
      id: 'survey-prospector',
      label: 'Survey Prospector',
      role: 'scavenger',
      venues: ['mine', 'workerCamp', 'bar'],
      text: 'walked survey lines for a prospecting outfit, weeks alone with a sampler and a beacon',
      skillBias: {
        exploration: 16,
        scavenging: 12,
        navigation: 8,
        firstAid: 6,
        explosives: 5,
      },
      attributeBias: { endurance: 3, perception: 2, resilience: 2 },
      traitBias: { patient: 2, curious: 2, stubborn: 1 },
      weight: 10,
    },
  ],

  // -------------------------------------------------------------------------
  // FORMATIVE EVENTS — the heaviest trait pressure, modest skill echo.
  // -------------------------------------------------------------------------
  formativeEvents: [
    {
      id: 'survived-decompression',
      label: 'Survived a Decompression',
      text: 'was in the compartment when it blew, and remembers the sound of it more than the cold',
      skillBias: { firstAid: 5, exploration: 4 },
      attributeBias: { composure: 2, resilience: 2 },
      traitBias: { cautious: 3, selfPreserving: 2, brave: 1 },
      weight: 10,
    },
    {
      id: 'lost-a-sibling',
      label: 'Lost a Sibling',
      text: 'lost a sibling to an industrial accident that the report afterwards called unavoidable',
      skillBias: { mechanicalEngineering: 5, firstAid: 4 },
      attributeBias: { resilience: 2, composure: 1 },
      traitBias: { protective: 3, suspicious: 2, vindictive: 1 },
      weight: 10,
    },
    {
      id: 'held-the-reactor',
      label: 'Held the Reactor',
      text: 'held a failing reactor together for six hours with two people and a manual',
      skillBias: { electricalEngineering: 8, mechanicalEngineering: 7 },
      attributeBias: { composure: 3, discipline: 2, steadiness: 1 },
      traitBias: { brave: 3, dutiful: 2, stubborn: 1 },
      weight: 8,
    },
    {
      id: 'blamed-for-it',
      label: 'Blamed for It',
      text: 'carried the blame for something they did not do, and watched the one who did it get promoted',
      skillBias: { negotiation: 5, computers: 4 },
      attributeBias: { socialAwareness: 2, composure: 1 },
      traitBias: { suspicious: 3, stubborn: 2, vindictive: 2 },
      weight: 10,
    },
    {
      id: 'saved-a-stranger',
      label: 'Saved a Stranger',
      text: 'pulled a stranger out of something without stopping to think first, and has never entirely explained why',
      skillBias: { firstAid: 7, exploration: 4 },
      attributeBias: { decisionMaking: 2, resilience: 1 },
      traitBias: { brave: 3, compassionate: 3, impulsive: 1 },
      weight: 10,
    },
    {
      id: 'was-left-behind',
      label: 'Was Left Behind',
      text: 'was left behind once, on a dock, watching a ship they held a berth on clear the ring',
      skillBias: { negotiation: 6, scavenging: 5 },
      attributeBias: { resilience: 2, socialAwareness: 1 },
      traitBias: { selfPreserving: 3, suspicious: 2, cautious: 1 },
      weight: 10,
    },
    {
      id: 'buried-a-parent',
      label: 'Buried a Parent',
      text: 'buried a parent during the worst of the collapse, in a queue, with a number instead of a service',
      skillBias: { firstAid: 5, persuasion: 4 },
      attributeBias: { resilience: 3, composure: 2 },
      traitBias: { dutiful: 2, protective: 2, patient: 1 },
      weight: 12,
    },
    {
      id: 'walked-away-from-it',
      label: 'Walked Away From It',
      text: 'walked away from a fight they should probably have taken, and has thought about it since',
      skillBias: { negotiation: 6, stealth: 5 },
      attributeBias: { evaluation: 2, composure: 1 },
      traitBias: { cautious: 3, selfPreserving: 2, patient: 1 },
      weight: 12,
    },
    {
      id: 'walked-into-it',
      label: 'Walked Into It',
      text: 'walked into a fight they should have stayed well out of, and did not walk out of it whole',
      skillBias: { brawling: 8, closeQuarters: 6, striking: 5 },
      attributeBias: { resilience: 2, strength: 1, decisionMaking: -1 },
      traitBias: { aggressive: 2, brave: 2, reckless: 2 },
      weight: 10,
    },
    {
      id: 'promoted-past-depth',
      label: 'Promoted Past Their Depth',
      text: 'was promoted past what they actually knew how to do, and never once admitted it out loud',
      skillBias: { persuasion: 7, computers: 5 },
      attributeBias: { leadership: 2, charisma: 1, composure: -1 },
      traitBias: { controlling: 3, stubborn: 2, jealous: 1 },
      weight: 8,
    },
    {
      id: 'demoted-unfairly',
      label: 'Demoted Unfairly',
      text: 'was put back a grade to cover somebody else\'s shortfall, and stayed on anyway because the work was there',
      skillBias: { mechanicalEngineering: 6, negotiation: 4 },
      attributeBias: { resilience: 2, discipline: 2 },
      traitBias: { stubborn: 3, dutiful: 2, vindictive: 1 },
      weight: 10,
    },
    {
      id: 'kept-a-costly-secret',
      label: 'Kept a Costly Secret',
      text: 'kept a secret that was not theirs to keep, and someone else paid the whole cost of it',
      skillBias: { stealth: 6, persuasion: 5 },
      attributeBias: { composure: 2, socialAwareness: 2 },
      traitBias: { loyal: 3, cautious: 2, suspicious: 1 },
      weight: 8,
    },
    {
      id: 'gave-it-back',
      label: 'Gave It Back',
      text: 'found something worth more than a year of wages and handed it in, and has never fully settled whether that was right',
      skillBias: { scavenging: 6, negotiation: 4 },
      attributeBias: { evaluation: 2, discipline: 1 },
      traitBias: { honest: 3, generous: 2, dutiful: 1 },
      weight: 10,
    },
    {
      id: 'year-off-work',
      label: 'A Year Off Work',
      text: 'spent a year unable to work after an injury, learning exactly how fast a life closes up behind you',
      skillBias: { computers: 6, firstAid: 5, medicalDiagnostics: 4 },
      attributeBias: { learning: 2, resilience: 2, endurance: -1 },
      traitBias: { patient: 2, cautious: 2, alcoholic: 1 },
      weight: 10,
    },
    {
      id: 'talked-down-a-crowd',
      label: 'Talked Down a Crowd',
      text: 'talked four hundred angry people back from a gate they were about to go through',
      skillBias: { persuasion: 12, negotiation: 8 },
      attributeBias: { charisma: 2, leadership: 2, composure: 2 },
      traitBias: { brave: 2, cooperative: 2, honest: 1 },
      weight: 6,
    },
    {
      id: 'only-one-back',
      label: 'The Only One Back',
      text: 'was the only one who came back, and gave the same flat account to every board that asked',
      skillBias: { exploration: 7, firstAid: 5, scavenging: 4 },
      attributeBias: { composure: 3, resilience: 2, socialAwareness: -1 },
      traitBias: { loyal: 3, dutiful: 3, protective: 1 },
      weight: 6,
    },
    {
      id: 'lost-the-ship',
      label: 'Lost the Ship',
      text: 'signed off on a hull that did not come back, and has read the same maintenance log a hundred times since',
      skillBias: { mechanicalEngineering: 7, navigation: 5 },
      attributeBias: { discipline: 3, evaluation: 2, composure: 1 },
      traitBias: { cautious: 3, dutiful: 2, controlling: 1 },
      weight: 8,
    },
    {
      id: 'paid-anothers-debt',
      label: 'Paid Another\'s Debt',
      text: 'cleared somebody else\'s debt out of their own account and never mentioned it again',
      skillBias: { negotiation: 7, persuasion: 5 },
      attributeBias: { socialAwareness: 2, evaluation: 1, composure: 1 },
      traitBias: { generous: 3, loyal: 2, patient: 1 },
      weight: 10,
    },
    {
      id: 'taught-someone-everything',
      label: 'Taught Someone Everything',
      text: 'trained up an apprentice who turned out better than them, and was glad about it',
      skillBias: { persuasion: 7, mechanicalEngineering: 5 },
      attributeBias: { leadership: 2, memory: 2, socialAwareness: 1 },
      traitBias: { patient: 3, generous: 2, cooperative: 1 },
      weight: 10,
    },
    {
      id: 'stayed-down',
      label: 'Stayed Down',
      text: 'stayed down and quiet through something they could hear happening on the other side of a wall',
      skillBias: { stealth: 8, lockpicking: 5 },
      attributeBias: { perception: 2, composure: 1, resilience: 1 },
      traitBias: { cowardly: 2, selfPreserving: 2, cautious: 2 },
      weight: 8,
    },
  ],
};
