/**
 * NAMES — pure authored data, no logic.
 *
 * Drawn from a wide spread of real-world naming traditions, split by sex so a
 * generated person's name matches how the game describes them. Surnames are
 * shared: most traditions do not inflect them, and the ones that do would need
 * per-culture rules the generator does not have.
 *
 * Earth names are for humans. The alien pools use different sound shapes, so a
 * non-human never reads as a human with an odd spelling.
 *
 * Names are not tied to origin, so a family can carry names from different
 * traditions. That is deliberate for now — the homeworld is a mixed population
 * — and can be tightened later by grouping these pools and drawing from the
 * group a character's origin implies.
 */

/** 1000 entries. */
export const EARTH_MALE_GIVEN: string[] = [
  "Ahmed", "Mohammed", "Omar", "Ali", "Hassan", "Hussein",
  "Khalid", "Tariq", "Samir", "Karim", "Zaid", "Hamza",
  "Youssef", "Mustafa", "Nabil", "Rami", "Fadi", "Bilal",
  "Adnan", "Mazen", "Tamer", "Bashir", "Farid", "Jamal",
  "Nasser", "Walid", "Amin", "Imran", "Salim", "Anwar",
  "Arash", "Kaveh", "Dariush", "Farhad", "Reza", "Navid",
  "Payam", "Shahram", "Behzad", "Kamran", "Mehrdad", "Soroush",
  "Babak", "Pouya", "Amirhossein", "Keyvan", "Omid", "Saeed",
  "Hossein", "Masoud", "Noam", "Eitan", "Avi", "Yonatan",
  "Omer", "Lior", "Itai", "Gil", "Nadav", "Ron",
  "Shai", "Yair", "Asaf", "Ori", "Tomer", "Moshe",
  "Ariel", "Elad", "Erez", "Boaz", "Arjun", "Raj",
  "Rahul", "Vikram", "Amit", "Sanjay", "Rohan", "Karan",
  "Nikhil", "Deepak", "Ajay", "Vijay", "Anand", "Aditya",
  "Dev", "Sameer", "Pranav", "Siddharth", "Varun", "Manish",
  "Suresh", "Ravi", "Akash", "Rohit", "Naveen", "Harish",
  "Kunal", "Vivek", "Anil", "Neeraj", "Wei", "Jun",
  "Hao", "Jian", "Ming", "Tao", "Bo", "Lei",
  "Yichen", "Zhihao", "Junjie", "Haoran", "Yifan", "Zixuan",
  "Cheng", "Guowei", "Jiahao", "Xiaobo", "Zhen", "Qiang",
  "Haruto", "Yuto", "Ren", "Sota", "Kaito", "Daiki",
  "Takumi", "Riku", "Haruki", "Naoki", "Kenji", "Hiroshi",
  "Akira", "Tatsuya", "Shota", "Ryota", "Koji", "Masato",
  "Kazuki", "Daisuke", "Minjun", "Seojun", "Jihoon", "Hyunwoo",
  "Jisung", "Donghyun", "Taeyang", "Sungmin", "Junho", "Jaehyun",
  "Minho", "Seungwoo", "Youngho", "Joon", "Kyungsoo", "Woobin",
  "Taehyun", "Jongho", "Seongho", "Gunwoo", "Aleksandr", "Dmitri",
  "Ivan", "Mikhail", "Nikolai", "Sergei", "Andrei", "Pavel",
  "Viktor", "Yuri", "Alexei", "Kirill", "Roman", "Maksim",
  "Oleg", "Vladimir", "Ilya", "Artem", "Denis", "Anton",
  "Boris", "Yaroslav", "Mykola", "Taras", "Oleksii", "Bohdan",
  "Giorgos", "Nikos", "Kostas", "Dimitris", "Panagiotis", "Stavros",
  "Vasilis", "Theodoros", "Christos", "Manolis", "Spyros", "Antonis",
  "Petros", "Sotiris", "Lefteris", "Stephen", "Frédéric", "Gustavo",
  "Gael", "Miguel Angel", "Juan", "Camilo", "Mark", "Thierry",
  "Muzaffer", "Philip", "Emilio", "Felix", "Fábio", "Åke",
  "Svein", "Paul", "Sakari", "Vilbergur", "Radvilė", "Viesturs",
  "Stanisław", "Marian", "Radúz", "Zoltán", "Octavian", "Martin",
  "Branko", "Eldar", "Bican", "Tú", "Ozy", "Jason",
  "Aliyu", "Emeka", "Adeyi", "Kijani", "Langalibalele", "Arthur",
  "William", "Gregory", "Eric", "Stéphane", "Gabino", "Marcelo",
  "Thiago Agustin", "Amaro", "Miguel", "Justin", "Olivier", "Rene",
  "Mees", "Lando", "Nico", "Brian", "Morten", "Torben",
  "Otto", "Leó", "Siim", "Arnas", "Aldis", "Marek",
  "Dominik", "Edmund", "Imre", "Arian", "Rudolf", "Radovan",
  "Elton", "Açıkel", "Trọng", "Banawi", "Edwin", "Ifeanyi",
  "Adeolu", "Ëakumbu", "Siyabonga", "Benjamin", "Anthony", "Graeme",
  "Kevin", "Henri", "Daniela", "José", "Matias", "Garry",
  "Théodore", "Kamil", "Chris", "Ignazio", "Josep", "Tomé",
  "Carl", "Anders", "Laus", "Samuli", "Vorm", "Juri",
  "Dominykas", "Krišs", "Ryszard", "Milan", "Štefan", "Zsolt",
  "Aristide", "Alen", "Željko", "Novruz", "Çağlasın", "Nam",
  "Satya", "Jonathan", "Nnamdi", "Ekundayo", "Kijana", "Mthokozisi",
  "Joojo", "Andrew", "Xavier", "Eloy", "João Lucas", "Santino",
  "Ángel", "Yesid", "Marc", "Stanislaw", "Arie", "Giampaolo",
  "Simón", "Lucas", "Waldemar", "Thor", "Sebastian", "Petri",
  "Játgeir", "Sander", "Simona", "Lauris", "Emil", "Erik",
  "Leopold", "Tibor", "Adonis", "Pavao", "Igor", "Sadiq",
  "Sıla", "Mulya", "Musa", "Ifechukwu", "Adeleke", "Kondo",
  "Mzamo", "Lawrence", "Michael", "Brett", "Benoît", "Noemí",
  "Cauê", "Juan Ignacio", "Héctor", "Abdul", "Timothée", "Kornelius",
  "Calogero", "Jerónimo", "Rodrigo", "Per", "Tobias", "Bent",
  "Mikael", "Hróar", "Jüri", "Ariana", "Mihels", "Ksawery",
  "Dušan", "Hugo", "Róbert", "Emilian", "Mladen", "Danijel",
  "Dirican", "Jumadi", "Dan", "Uche", "Oluwagbemiga", "Angalia",
  "Luyanda", "Kyle", "Étienne", "Miguel Ángel", "Heitor", "Thiago",
  "Carlos", "Sebastián", "Marcus", "Thibault", "Arne", "Ayoub",
  "Romolo", "Bautista", "Alf", "Robert", "Kjeld", "Tero",
  "Maron", "Vello", "Aivaras", "Roberts", "Miłosz", "Richard",
  "Sergej", "Ákos", "Antim", "Darko", "Klemen", "Ənvər",
  "Sayrak", "Quang", "Lukman", "Daniel", "Ismail", "Chukwuemeka",
  "Ikeoluwa", "Zuhri", "Vusumuzi", "David", "Adam", "Carla",
  "Mathias", "Francisco", "Armando", "Bryan", "Jacques", "Fedor",
  "Baldassare", "Chucho", "Vítor", "Ulf", "Petter", "Leif",
  "Petteri", "Bjarki", "Aivar", "Tautvydas", "Hanss", "Hubert",
  "Lukáš", "Šimon", "Bálint", "Bănel", "Adolf", "Ergönül",
  "Hưng", "Jagaraga", "Cole", "Ahmad", "Chijioke", "Akinkunmi",
  "Jalia", "Mandla", "Shane", "Reginald", "Jérôme", "Ian",
  "Juan Pablo", "Pablo", "Edinson", "Isaac", "Steven", "Bradley",
  "Dionisio", "Dinis", "Bertil", "Tore", "Johannes", "Hængur",
  "Jaan", "Milana", "Gatis", "Olgierd", "Kryštof", "Frederik",
  "János", "Cristobal", "Mato", "Tomaž", "Cahangir", "Uluman",
  "Vũ", "Elon", "Caleb", "Nasiru", "Somtochukwu", "Inioluwa",
  "Sadaka", "Fiifi", "Charles", "Timothy", "André", "María Luisa",
  "Juan Cruz", "Alfred", "Gerolf", "Bastiaan", "Guglielmo", "Jorge",
  "Timmy", "Elias", "Reyr", "Aurelija", "Reinis", "Maurycy",
  "Svatoslav", "Milán", "Adelin", "Lovre", "Goran", "Osman",
  "Vedat", "Châu", "Baktiadi", "Raymond", "Sani", "Abiona",
  "Sandile", "Jack", "John", "Craig", "Grégoire", "Abel",
  "Raul", "Jairo", "Christopher", "Maurice", "Hans-Helmut", "Seth",
  "Gianluigi", "Karl", "Sondre", "Mogens", "Ilmari", "Max",
  "Arnoldas", "Igors", "Kazimierz", "Miloslav", "Tomáš", "Antal",
  "Timotei", "Šime", "Jasmin", "Ağahadi", "Cavit", "Anh",
  "Eko", "Keith", "Nonso", "Omobobola", "Siku", "Bhekani",
  "Ben", "Hayden", "Scott", "Laurent", "Amalia", "Alexandre",
  "Santiago", "Alonso", "Víctor", "Gilles", "Günter", "Bas",
  "Augusto", "Cornelio", "Bernardo", "Sven", "Jens", "George",
  "Kauko", "Ívar", "Raivo", "Perla", "Arnolds", "Fryderyk",
  "Jiří", "Jozef", "István", "Jenel", "İsa", "Alattin",
  "Galiono", "Henry", "Okechukwu", "Esupofo", "Kiapo", "Thabani",
  "Spencer", "James", "Nicolas", "Nelly", "Matheus", "Adolfo",
  "Louis", "Willem", "Rembrandt", "Joan", "Benjamim", "Mohamed",
  "Rolf", "Danny", "Erkki", "Adíel", "Tiit", "Šarūnas",
  "Ziedonis", "Przemysław", "Aurică", "Matija", "İxtiyar", "Durmuşali",
  "Huy", "Harja", "Jeffrey", "Tanimu", "Adekitan", "Yohane",
  "Christian", "Nicholas", "Elijah", "Fernando", "Lorenzo", "Tristan",
  "Hans-Friedrich", "Jim", "Leopoldo", "Berto", "Keld", "Pentti",
  "Lindberg", "Viktorija", "Mikels", "Lumír", "Bernard", "Şirzad",
  "Gençay", "Bảo", "Vino", "Usman", "Demilade", "Joseph",
  "Caridad", "Marcos Vinicius", "Ricardo", "Wilson", "Ryan", "Ricciotti",
  "Saturnino", "Manuel", "Geir", "Ragner", "Aleksanteri", "Tími",
  "Andrius", "Normunds", "Bruno", "Bohuslav", "Vladislav", "Edgar",
  "Rafael", "Aliabbas", "Reksa", "Alex", "Bello", "Ekene",
  "Alamu", "Daudi", "Thando", "Dennis", "Kenneth", "Samuel",
  "Indira", "Otávio", "Fausto", "Antonio", "Edelbert", "Maxim",
  "Gianpietro", "Dimas", "Leandro", "Björn", "Jonas", "Ove",
  "Ilari", "Hólmbert", "Artur", "Jovita", "Kristaps", "Cezary",
  "Eduard", "Teofil", "Mislav", "Valter", "Nurşən", "Vaysal",
  "Budi", "Shehu", "Durodola", "Usiku", "Bandile", "Julian",
  "Nathan", "Éric", "Eloisa", "Ignacio", "Luis", "Dario",
  "Bernfried", "Enrico", "Baldomero", "Duarte", "Torsten", "Palle",
  "Juhani", "Bjarnharður", "Romualdas", "Edvīns", "Jędrzej", "Filip",
  "Sándor", "Pero", "Grega", "Yamən", "Necmettin", "Galuh",
  "Mahmud", "Ebuka", "Akinlabi", "Jua", "SimphiweyiNkosi", "Alexander",
  "Manawa", "Joaquín", "Eugène", "Egon", "Sem", "Gianni",
  "Ale", "Gabriel", "Einar", "Valtteri", "Friðgeir", "Aleksei",
  "Raminta", "Konstanty", "Alexandru", "Petar", "Ruslan", "Kahir",
  "Umar", "Jeremiah", "Haruna", "Akinwale", "Agustín", "Joaquim",
  "Santiago Benjamin", "Alfonso", "Gerardo", "Javier", "Diogo", "Sten",
  "Frode", "Väinö", "Aðalsteinn", "Erikas", "Indriķis", "Antoni",
  "Konštantín", "Barnabás", "Romeo", "Ivo", "Üzeyir", "Timurtaş",
  "Khoa", "Rudi", "Ronnie", "Kolawole", "Ekundu", "Darren",
  "Patrick", "Laura", "Ravi Lucca", "Agustin", "Diego", "Jamie",
  "Klaus-Ulrich", "Salvi", "Custodio", "César", "Tom", "Tommi",
  "Valdi", "Peeter", "Ernestas", "Raivis", "Ernest", "Bystrík",
  "Csaba", "Brăduț", "Dražen", "Zdenko", "Gündüz", "Özdal",
  "Jake", "Austin", "Guillaume", "Pim", "Stefano", "Teobaldo",
  "Carmen", "Cristian", "Sergio", "Mário", "Kurt", "Thomas",
  "Tapio", "Funi", "Jevgeni", "Naglis", "Laimonis", "Václav",
  "Károly", "Ieremia", "Davor", "Slobodan", "Vahittin", "Dũng",
  "Cawuk", "Ajani", "Gordon", "Nigel", "Roland", "Michel",
  "Heini", "Joshua", "Marcos", "Pilar", "Lautaro", "Cristiano",
  "Mattias", "Ivar", "Noah", "Veikko", "Arnald", "Ants",
  "Jolanta", "Aleks", "Ignác", "Norbert", "Costel", "Mirsad",
  "Gülşahin", "Viman", "Kabiru", "Mohamedi", "Josh", "Constantin",
  "Leon", "Lamberto", "Victoria", "Lautaro Ezequiel", "Vicente", "Raúl",
  "Pedro", "Laust", "Matti", "Viggó", "Indrek", "Gytis",
  "Janis", "Ferdinand", "Áron", "László", "Eustațiu", "Mile",
  "Yertan", "Adiarja", "Travis", "Adesoji", "Ruhiu", "Andile",
  "Roger", "Grant", "Heribert", "Lex", "Ciro", "Jose",
  "Yeni", "Mateo", "Fredy", "Lars", "Svenning", "Jóann",
  "Aurėja", "Kārlis", "Bedřich", "Aurel", "Péter", "Axinte",
  "Çerçi", "Eja", "Afolarin", "Kiburi", "Levi", "Matthew",
  "Jean", "Theo", "Michelotto", "Irene", "Nicolás", "Mohammad",
  "Eirik", "Villads", "Moli", "Leila", "Andrejs", "Łukasz",
  "Dávid", "Iulian", "Jaka", "Seda", "Minh", "Jayeng",
  "Chibuzo", "Oladimeji", "Sabari", "Gerald", "Antoine", "Luka",
  "Florencio", "Catalina", "Alejandro", "Mateus", "Antero", "Eivind",
  "Øivind", "Eemeli", "Gunnar", "Valeri", "Titas", "Marcel",
  "Slavomír", "Lajos", "Ivica", "Vincenc", "Yolal", "Kawaca",
  "Jacob", "Kelechi", "Faraja", "Nhlanhla", "Frank", "Blake",
  "Édouard", "Leonhard", "Mart", "Cipriano", "Eduardo", "Jhon",
  "Lisandro", "Lennart", "Robin", "Antti", "Amos", "Mati",
  "Vakris", "Osvalds", "Vlastimil", "Félix", "Theodor", "Juraj",
  "Nik", "Mutasım", "Thành", "Candrakanta", "Tyler", "Ibrahim",
  "Chukwudi", "Toki", "Ronald", "Curtis", "Luigi", "Albano",
  "Silvano", "João", "Luiz Henrique", "Magne",
];

/** 1000 entries. */
export const EARTH_FEMALE_GIVEN: string[] = [
  "Aisha", "Fatima", "Layla", "Noor", "Mariam", "Hana",
  "Salma", "Yasmin", "Amal", "Rania", "Dalia", "Huda",
  "Nadia", "Reem", "Farah", "Lina", "Samira", "Noura",
  "Zainab", "Iman", "Leila", "Sanaa", "Maha", "Dina",
  "Rasha", "Hala", "Lamia", "Safiya", "Malak", "Soraya",
  "Parisa", "Shirin", "Neda", "Sahar", "Mina", "Nazanin",
  "Roya", "Arezoo", "Sepideh", "Mahsa", "Niloofar", "Yasaman",
  "Setareh", "Taraneh", "Shadi", "Azadeh", "Mitra", "Elham",
  "Pegah", "Yael", "Noa", "Tamar", "Shira", "Talia",
  "Roni", "Gal", "Liat", "Michal", "Hila", "Adi",
  "Neta", "Orly", "Avital", "Sigal", "Moran", "Rotem",
  "Efrat", "Anat", "Tal", "Priya", "Ananya", "Aditi",
  "Neha", "Kavya", "Meera", "Nisha", "Riya", "Pooja",
  "Isha", "Divya", "Sneha", "Anjali", "Shreya", "Naina",
  "Ritu", "Kiran", "Deepa", "Sonali", "Tanvi", "Lakshmi",
  "Ishita", "Diya", "Aarohi", "Sanya", "Radhika", "Pallavi",
  "Simran", "Preeti", "Asha", "Mei", "Jing", "Xinyi",
  "Yuting", "Fang", "Yan", "Hui", "Xia", "Lili",
  "Yue", "Qian", "Ruoxi", "Mengyao", "Jiaqi", "Xiaoyu",
  "Wen", "Lan", "Min", "Xue", "Ying", "Yui",
  "Aoi", "Sakura", "Hina", "Rin", "Akari", "Nanami",
  "Rina", "Ayaka", "Yuna", "Misaki", "Haruka", "Natsuki",
  "Emi", "Kaori", "Yoko", "Keiko", "Mika", "Reina",
  "Seoyeon", "Jiwon", "Minseo", "Hyejin", "Soyeon", "Eunji",
  "Sujin", "Jiwoo", "Chaewon", "Nayeon", "Hyeri", "Somin",
  "Yeji", "Jisoo", "Seulgi", "Ara", "Bora", "Sena",
  "Dahyun", "Anastasia", "Natalia", "Elena", "Olga", "Irina",
  "Svetlana", "Tatiana", "Ekaterina", "Marina", "Yulia", "Daria",
  "Alina", "Polina", "Ksenia", "Viktoria", "Nadezhda", "Galina",
  "Vera", "Larisa", "Oksana", "Kateryna", "Iryna", "Olena",
  "Svitlana", "Yana", "Eleni", "Katerina", "Dimitra", "Vasiliki",
  "Georgia", "Sofia", "Despina", "Ioanna", "Athina", "Chrysa",
  "Niki", "Eirini", "Fotini", "Antonia", "Stephanie", "Hélène",
  "Julio César", "Ana", "Valentina", "Fresia", "Blanca", "Kirsty",
  "Odette", "Edeltraud", "Lara", "Felipa", "Carminho", "Britt",
  "Åse", "Gerda", "Hanna", "Vibeka", "Ignė", "Edīte",
  "Roksana", "Patricie", "Alžbeta", "Eszter", "Carina", "Jasna",
  "Stanka", "Aynurə", "Özdeş", "Thảo", "Elisa", "Catherine",
  "Hafsat", "Ujunwa", "Asake", "Almasi", "Nothando", "Wendy",
  "Crystal", "Tui", "Michelle", "Paulette", "Cecilia", "Júlia",
  "Lola", "Brenda", "Inés", "Sian", "Marine", "Lisanne",
  "Romina", "Haydée", "Carlota", "Inga", "Vilde", "Hanne",
  "Maria", "Signa", "Triin", "Artūras", "Santa", "Blanka",
  "Alice", "Žaneta", "Borbála", "Vasilica", "Nada", "Marijana",
  "Səadət", "Gülmisal", "Hồng", "Melissa", "Asma'u", "Ngozi",
  "Segilola", "Asali", "Londiwe", "Felicia", "Amber", "Claire",
  "Angela", "Nathalie", "Vanesa", "Sabrina", "Agustina", "Evelyn",
  "María", "Kimberley", "Laurence", "Rosl", "Bente", "Eugenia",
  "Jordana", "Marie", "Gunn", "Sini", "Lilja", "Niina",
  "Dovydas", "Annija", "Sonia", "Sára", "Sláva", "Anna",
  "Ivona", "Zdenka", "Ülviyyə", "Tangül", "Mai", "Kartika",
  "Kimberly", "Ogechi", "Fadekemi", "Kipenzi", "Nomthandazo", "Roselyn",
  "Cynthia", "Sandra", "Deanna", "Geneviève", "Pascual", "Jade",
  "Mireya", "Rocío", "Gemma", "Simone", "Florence", "Diana",
  "Abigaíl", "Elsa", "Ragnhild", "Justina", "Kaarina", "Rúna",
  "Nina", "Jokūbas", "Vilma", "Aneta", "Drahomíra", "Veronika",
  "Caterina", "Petra", "Ajda", "Şövkət", "Yazgül", "Paramita",
  "Karen", "Gambo", "Adaeze", "Morayo", "Nigesa", "Nomusa",
  "Rosemary", "Isla", "Miranda", "Rubén", "Ana Clara", "Jazmin",
  "Jayne", "Arnaude", "Nisa", "Matilda", "Sara", "Mariana",
  "Elisabet", "Susanne", "Inkeri", "Tíbrá", "Arūnas", "Ruta",
  "Natasza", "Otýlie", "Karina", "Éva", "Paula", "Anita",
  "Zöhrə", "Yasemen", "Vân", "Christine", "Ruqayya", "Nkiruka",
  "Motunrayo", "Abigaili", "Nomvula", "Afua", "Margaret", "Rebecca",
  "Amy", "Louise", "Rosa", "Isabelly", "Catalina", "Flor",
  "Francesca", "Valentine", "Hülya", "Angelina", "Melania", "Isaura",
  "Karin", "Anneli", "Úna", "Kristiina", "Vilius", "Emma",
  "Bianka", "Dana", "Viktória", "Zsuzsanna", "Teodosia", "Antonija",
  "Manca", "Ceyran", "Tutkucan", "Dương", "Fathonah", "Jennifer",
  "Habiba", "Onyinye", "Omolara", "Udeera", "Dumisani", "Eunice",
  "Sophie", "Katherine", "Audrey", "María Cristina", "Maria Vitória", "Mora",
  "Alondra", "Milena", "Diane", "Nath", "Alwina", "Lynn",
  "Ludovica", "Montserrat", "Débora", "Evelina", "Malin", "Inger",
  "Eija", "Friðborg", "Indra", "Klara", "Lýdie", "Petrana",
  "Gabriella", "Tiberia", "Gordana", "Neja", "Selcan", "Eşim",
  "Hesti", "Rabi", "Madini", "Nana Ama", "Leanne", "Chelsea",
  "Martine", "Citlali", "Maria Sophia", "Malena", "Paola", "Nicole",
  "Claudine", "Bruni", "Victoria", "Livia", "Nélida", "Camilla",
  "Stina", "Maija", "Yrsa", "Eidvilė", "Elvīra", "Anastazja",
  "Renáta", "Miriama", "Valéria", "Viorela", "Zora", "Nüşabə",
  "Melûl", "Ngọc", "Aurora", "Hauwa", "Oluchi", "Mojisoluwa",
  "Nyota", "Thembeka", "Ruth", "Monica", "Holly", "Renée",
  "Hilda", "Letícia", "Josefina", "Anouk", "Magdalene", "Zoë",
  "Rosalia", "Valeria", "Juliana", "Rita", "Jacqueline", "Raili",
  "Kamma", "Grēta", "Gabriela", "Ivica", "Mária", "Anișoara",
  "Lea", "Irma", "Alabezek", "Gina", "Cheryl", "Halima",
  "Busisiwe", "Megan", "Sarah", "Danielle", "Oswaldo", "Lívia",
  "Luz", "Beverley", "Thérèse", "Yinthe", "Nicoletta", "Elvira",
  "Íris", "Pernilla", "Mette", "Katri", "Tala", "Ülle",
  "Markas", "Tola", "Miloslava", "Henrieta", "Irén", "Božena",
  "Milica", "Aidə", "Üçgül", "Gasti", "Nneka", "Omotola",
  "Asanti", "Thuthukile", "Eliabeth", "Christina", "Michele", "Georgina",
  "Antonella", "Julieta", "Carmen", "Mery", "Frédérique", "Linda",
  "Amira", "Bianca", "Patricia", "Luna", "Torill", "Bitten",
  "Elina", "Heiðbjörg", "Sirje", "Mantė", "Velta", "Renata",
  "Marcela", "Gyöngyi", "Tea", "Meyransa", "Aycagül", "Diah",
  "Barbara", "Doyinsola", "Faisa", "Nonjabulo", "Janet", "Leslie",
  "Tina", "Mathilde", "Tania", "Esther", "Esperanza", "Mónica",
  "Alla", "Janne", "Silvia", "Sigrid", "Mimi", "Aune",
  "Birtna", "Tamara", "Arijus", "Ewa", "Libuše", "Martina",
  "Mariann", "Betina", "Anica", "Balaxanım", "Hasgül", "Oni",
  "Hadiza", "Chinelo", "Bolatito", "Makini", "Thabisa", "Dorothée",
  "Roberto", "Stella", "Adriana", "Margarita", "Joyce", "Viola",
  "Griselda", "Constanza", "Yara", "Tove", "Freja", "Mirja",
  "Agneta", "Laurita", "Miroslava", "Edit", "Antonela", "Jana",
  "Xalidə", "Vildane", "Usyi", "Sumayya", "Tolulope", "Tuere",
  "Nozizwe", "Abigail", "Tracey", "Joséphine", "Maysa", "Leidy",
  "Josette", "Irmgard", "Elise", "Pierina", "Ofelia", "Maren",
  "Tía", "Reda", "Sintija", "Eliza", "Michaela", "Lujza",
  "Andrea", "Veronica", "Branka", "Jadranka", "Rəxşəndə", "Semine",
  "Cici", "Mofifoluwa", "Niara", "Emily", "Suzanne", "Stacey",
  "Célina", "Susana", "Delfina", "Verónica", "Yaneth", "Lisa",
  "Dorota", "Giorgia", "Águeda", "Annika", "Jenny", "Winni",
  "Anja", "Henrika", "Kipras", "Ināra", "Marika", "Leona",
  "Xénia", "Rozália", "Manuela", "Sanja", "Mədinə", "Rümeysa",
  "Yani", "Courtney", "Kosisochukwu", "Folashade", "Skolastika", "Nobuhle",
  "Jasmine", "Frances", "Kristen", "Béatrice", "Paloma", "Angélica",
  "Mercedes", "Lucy", "Gabriele", "Azucena", "Iara", "Linnéa",
  "Hilde", "Pauliina", "Draumey", "Solvita", "Alana", "Krisztina",
  "Mateja", "Bənövşə", "Nazlihan", "Endah", "Gloria", "Aminatu",
  "Obianuju", "Olajumoke", "Londisizwe", "Ann", "Chloe", "Vicki",
  "Eduardo", "Camila", "Kim", "Mara", "Annunziata", "Teresa",
  "Naiara", "Ingrid", "Pia", "Manúela", "Lukas", "Julianna",
  "Anghelina", "Vlasta", "Aliyə", "Nezengül", "Salimah", "Bilkisu",
  "Ololade", "Kuchanua", "Nokulunga", "Olivia", "Theresa", "Aurélie",
  "Araceli", "Luciana", "Julia", "Claudia", "Lotte", "Sole",
  "Mafalda", "Margaretha", "Karoline", "Pirjo", "Svana", "Lavīze",
  "Anna Maria", "Denisa", "Justína", "Ildikó", "Violeta", "Qaratel",
  "Sehel", "Yến", "Loretta", "Sa'adatu", "Hodari", "Siphesihle",
  "Marilyn", "Caitlin", "Rachael", "Jorge Luis", "Viviana", "Marcelle",
  "Aylin", "Custodia", "Annica", "Gerd", "Mie", "Sari",
  "Mía", "Kristina", "Povilas", "Berta", "Nela", "Judit",
  "Maja", "Maša", "Eriş", "Kathleen", "Chinyere", "Yejide",
  "Adwoa", "Vanessa", "Pauline", "Gilberto", "Heloisa", "Maite",
  "Mirta", "Monique", "Helga", "Beth", "Maree", "Alexandria",
  "Rose-Marie", "Clarisa", "Pamela", "Felicitas", "Fernanda", "Gertrud",
  "Móna", "Malle", "Žemyna", "Vineta", "Ladislava", "Mónika",
  "Clementina", "Karla", "Damjana", "Samahat", "Dewi", "Julie",
  "Ozioma", "Kijana", "Olwethu", "Lawrencia", "Angelica", "Inès",
  "Marianne", "Tirza", "Lidia", "Alta Gracia", "Maria Victoria", "Jessica",
  "Liliana", "Miriam", "Regitse", "Minna", "Dainius", "Elizabete",
  "Aniela", "Pavlína", "Magdolna", "Malvina", "Aynımah", "Hương",
  "Almira", "Wuraola", "Kweli", "Thandeka", "Erika", "Rachel",
  "Sinaida", "Zeynep", "Michela", "Luisa", "Luis", "Isabel",
  "Núria", "Melina", "Madelene", "Herdis", "Míra", "Ljudmila",
  "Arminas", "Maža", "Růžena", "Iolanda", "Mira", "Lana",
  "Cemiyle", "Dian", "Toni", "Omotara", "Rua", "Ruby",
  "Isabelle", "Laurie", "Wibke", "Lise", "Pina", "Sofia Belen",
  "Karol", "Ana Carolina", "Astrid", "Emilia", "Sigfríður", "Enrika",
  "Kristiāna", "Kaja", "Silvie", "Olympia", "Daniela", "Laura",
  "Magda", "Ayyaruk", "Vi", "Gilda", "Chiamaka", "Amope",
  "Safiri", "Nomagugu", "Deborah", "Regina", "Lucie", "Centa",
  "Aria", "Magdalena", "Guadalupe", "Larissa", "Liv", "Ragna",
  "Katriina", "Kotryna", "Dace", "Julita", "Radoslava", "Erzsébet",
  "Matea", "Sidar", "Xuân", "Nadine", "Abosede", "Najuma",
  "Noxolo", "COmfort", "Rhonda", "Heather", "Corinne", "Caroline",
  "Irene", "Mirthe", "Bettina", "Rafaél", "Raquel", "Fabiana",
  "Beatriz", "Helena", "Tellervo", "Drífa", "Mare", "Inese",
  "Saskia", "Katalin", "Zaharia", "Zülbiye", "Tiara", "Jamila",
  "Moyosore", "Misuli", "Nonhlanhla", "Manon", "Gertrude", "Nynke",
  "Vittoria", "Nayara", "Leonor", "Maya", "Ingela", "Emilie",
  "Naja", "Jóríður", "Vaida", "Diāna", "Ida", "Monika",
  "Hermína", "Ane", "Hezniye", "Lauren", "Ndumiso", "Aba",
  "Alexis", "Christiane", "Evamaria", "Patrizia", "Esparta", "Mia Jazmin",
  "Eva", "Cristina", "Birthe", "Jaana", "Svanfríður", "Maie",
  "Mindaugas", "Rozalia", "Jitka", "Bohumila", "Isabela", "Mirjana",
  "Nadja", "Ayasun", "Zulfa", "Maryam",
];

/** 1000 entries. */
export const EARTH_SURNAMES: string[] = [
  "Haddad", "Khoury", "Mansour", "Nassar", "Farhat", "Rahman",
  "Saleh", "Khalil", "Hamdan", "Hariri", "Darwish", "Najjar",
  "Saad", "Habib", "Abboud", "Bakri", "Shami", "Qureshi",
  "Masri", "Zayed", "Khatib", "Barakat", "Jaber", "Taha",
  "Yasin", "Rashid", "Fakhoury", "Nader", "Azmi", "Husseini",
  "Ahmadi", "Hosseini", "Karimi", "Rahimi", "Moradi", "Jafari",
  "Ebrahimi", "Ghasemi", "Rostami", "Kazemi", "Mahmoudi", "Nouri",
  "Farhadi", "Shirazi", "Tabrizi", "Tehrani", "Sadeghi", "Mousavi",
  "Hashemi", "Azimi", "Cohen", "Levi", "Mizrahi", "Peretz",
  "Biton", "Dahan", "Azulay", "Ben-David", "Barak", "Shapiro",
  "Dayan", "Sharabi", "Malka", "Ohayon", "Golan", "Amir",
  "Avraham", "Ben-Ami", "Shalev", "Navon", "Sharma", "Patel",
  "Singh", "Kumar", "Gupta", "Verma", "Shah", "Mehta",
  "Kapoor", "Iyer", "Nair", "Rao", "Reddy", "Joshi",
  "Desai", "Malhotra", "Bhat", "Choudhury", "Banerjee", "Mukherjee",
  "Das", "Bose", "Sinha", "Khanna", "Agarwal", "Menon",
  "Pillai", "Kulkarni", "Saxena", "Arora", "Wang", "Li",
  "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao",
  "Wu", "Zhou", "Xu", "Sun", "Ma", "Zhu",
  "Hu", "Guo", "He", "Gao", "Lin", "Luo",
  "Zheng", "Liang", "Xie", "Song", "Tang", "Han",
  "Feng", "Yu", "Dong", "Xiao", "Sato", "Suzuki",
  "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura",
  "Kobayashi", "Kato", "Yoshida", "Yamada", "Sasaki", "Yamaguchi",
  "Matsumoto", "Inoue", "Kimura", "Hayashi", "Shimizu", "Yamazaki",
  "Mori", "Abe", "Ikeda", "Hashimoto", "Ishikawa", "Yamashita",
  "Ogawa", "Ishii", "Hasegawa", "Goto", "Kim", "Lee",
  "Park", "Choi", "Jung", "Kang", "Cho", "Yoon",
  "Jang", "Lim", "Shin", "Seo", "Kwon", "Hwang",
  "Ahn", "Ryu", "Hong", "Jeon", "Ko", "Moon",
  "Son", "Bae", "Baek", "Heo", "Nam", "Shim",
  "Noh", "Ha", "Kwak", "Ivanov", "Petrov", "Sidorov",
  "Smirnov", "Kuznetsov", "Popov", "Sokolov", "Lebedev", "Kozlov",
  "Novikov", "Morozov", "Volkov", "Solovyov", "Vasiliev", "Zaitsev",
  "Pavlov", "Semenov", "Golubev", "Vinogradov", "Bogdanov", "Shevchenko",
  "Kovalenko", "Bondarenko", "Tkachenko", "Kravchenko", "Papadopoulos", "Georgiou",
  "Nikolaidis", "Dimitriou", "Pappas", "Vasileiou", "Christodoulou", "Karagiannis",
  "Antoniou", "Konstantinou", "Alexiou", "Theodorou", "Stavrou", "Panagiotou",
  "Markou", "Mason", "Lambert", "Arriaga", "da Cruz", "Correa",
  "González", "Sánchez", "McLean", "Perez", "Heintze", "van den Wittenboer",
  "Castelli", "Martorell", "Cardoso", "Blom", "Strand", "Lind",
  "Savolainen", "Otsson", "Mäeots", "Gintalas", "Caune", "Kiedrowicz",
  "Ševčíková", "Roháčik", "Veres", "Stan", "Grubišić", "Zemljič",
  "Axundlu", "Akçay", "Dương", "Yulianti", "Miller", "Yusuf",
  "Obi", "Ogunbamigbe", "Sayyid", "Nsibande", "Pomaa", "Nguyen",
  "Brown", "Williams", "Villeneuve", "Salas", "Costa", "Gonzalez",
  "Sepúlveda", "Bustamante", "Lees", "Chrétien", "Bohnbach", "Wilson",
  "Giusti", "León", "Coelho", "Johannesson", "Aas", "Østergaard",
  "Perälä", "Neistisdóttir", "Sillaste", "Kalvelis", "Podnieks", "Kursa",
  "Staněk", "Rišová", "Tóth", "Ardelean", "Sošić", "Volk",
  "Cuvarlı", "Gülen", "Hoàng", "Agustina", "Larsen", "Danjuma",
  "Ihejirika", "Ogindan", "Kamau", "Mtuswa", "Asenso", "Lane",
  "Forsyth", "Russell", "Laplante", "Sanabria", "Ramos", "Castro",
  "Ayala", "Hoarau", "Weitzel", "Kolster", "Sauli", "Esparza",
  "Johansson", "Tveit", "Bach", "Tuovinen", "Ríkarðsdóttir", "Komarov",
  "Kavaliauskas", "Zālīte", "Gasik", "Bureš", "Pallo", "Bogdán",
  "Nemeș", "Šimić", "Popović", "Eyvazalı", "Ergül", "Wijaya",
  "Vaughn", "Nwachukwu", "Morawo", "Yudas", "Mkhize", "Agyapong",
  "Jacobs", "Jackson", "Parker", "Côté", "Acevedo", "Abreu",
  "Aguirre", "Hernández", "Rojas", "Brookes", "Lopez", "Jacob",
  "van Eck", "Garzoni", "Moliner", "Nunes", "Madsen", "Andersen",
  "Laurila", "Vagnsdóttir", "Vaher", "Akelis", "Dylong", "Müllerová",
  "Cibulová", "Gulyás", "Barbu", "Solomun", "Golob", "Salamoğlu",
  "Manço", "Lê", "Puspita", "Robinson", "Garba", "Nwosu",
  "Adesiyan", "Kitumaini", "Sokhulu", "Okyere", "Taylor", "Jenkins",
  "Bergeron", "Tirado", "Lima", "Avila", "Belmar", "Francis",
  "Brunel", "Mälzer", "Hoekstra", "Querini", "Campos", "Nogueira",
  "Larsson", "Solheim", "Kristiansen", "Räsänen", "Karelsson", "Gavrilov",
  "Gaižauskas", "Liepiņa", "Maciuszek", "Sedlák", "Palkovičová", "Fodor",
  "Niță", "Krznarić", "Novak", "Məmmədquluzadə", "Bilir", "Trần",
  "Waskita", "Smith", "Tukur", "Ojukwu", "Owolabi", "Njeri",
  "Duma", "Yeboa", "Morton", "Jennings", "Tessier", "Jimínez",
  "da Mota", "Muñoz", "Castellanos", "Bennett", "Cordier", "Trubin",
  "van Laarhoven", "Bettoni", "Naranjo", "Santos", "Olsson", "Holm",
  "Nissinen", "Arnfreyrsdóttir", "Nurk", "Kairys", "Ābele", "Olchawa",
  "Němec", "Ondruška", "Horváth", "Preda", "Brletić", "Turk",
  "Nəzirli", "Arslan", "Handayani", "Carr", "Ali", "Ogbuehi",
  "Olabode", "Mdletshe", "Oti", "Norman", "Beard", "Terry",
  "Boisvert", "Pineda", "Cruz", "Abarca", "Castillo", "Cox",
  "Albert", "Scheuermann", "François", "Tarantini", "Fuentes", "Borges",
  "Andersson", "Moen", "Dam", "Mäkinen", "Dennisdóttir", "Jürgenson",
  "Paulauskas", "Vilciņš", "Klejna", "Ševčík", "Konrád", "Nagy",
  "Toma", "Balić", "Rozman", "Nəzirova", "Zengin", "Nguyễn",
  "Lazuardi", "Martin", "Mohammed", "Owokoniran", "Ibrahim", "Mcwaye",
  "Boakye", "Goodman", "Gill", "Sweeney", "Fréchette", "Canales",
  "Sousa", "Ruiz", "Maureira", "Aguilar", "Tanguy", "Becker",
  "Arnold", "Ossani", "Navarro", "Leal", "Nordlund", "Dahl",
  "Johnsen", "Lehtinen", "Sturlaugsson", "Žukauskas", "Turiņš", "Wlaźlak",
  "Němečková", "Tomašek", "Juhász", "Mazilescu", "Ljubetić", "Kobal",
  "Qurbanov", "Đặng", "Wijayanti", "Harris", "Idris", "Bakare",
  "Magombo", "Gininda", "Watson", "Boyd", "Walter", "St-Jean",
  "Ozuna", "da Luz", "Chavez", "Rodríguez", "West", "Humbert",
  "Dowerg", "Uphaus", "Chindamo", "Jaume", "Pinto", "Bäckström",
  "Berge", "Klausen", "Berg", "Elentínusdóttir", "Fomin", "Jankauskas",
  "Siliņa", "Kolanko", "Holuby", "Suciu", "Gudelj", "Mlinar",
  "Əlibəyov", "Şama", "Bùi", "Najmudin", "Lawal", "Chukwu",
  "Oparinde", "Mohamed", "Malinga", "Gyasi", "Guzman", "Patchett",
  "Bouchard", "Iglesias", "da Rosa", "San Martín", "Gómez", "Charles",
  "Krein", "Reijers", "Treccani", "Águila", "Neto", "Englund",
  "Nilsen", "Olesen", "Vuorinen", "Ingimundsdóttir", "Palu", "Skuja",
  "Tórz", "Šmídová", "Ďaďo", "Dobre", "Perak", "Likar",
  "Qutqaşınlı", "Durmuş", "Phạm", "Hassanah", "Marquez", "Adelakun",
  "Shazi", "Nti", "White", "Mitchell", "Carter", "Richer",
  "Barragán", "Vasconcelos", "Romero", "Angarita", "Lucas", "Loos",
  "Vertooren", "Spanevello", "Abad", "Mota", "Nørgaard", "Laakso",
  "Steinfinnsson", "Gailys", "Lagzdiņš", "Węgier", "Čierny", "Kiss",
  "Fabijanić", "Rəhimli", "Türk", "Zulaika", "Shehu", "Anyanwu",
  "Ngwenya", "Safo", "Cook", "Wong", "Henderson", "Boucher",
  "Estrada", "Pires", "Maldonado", "Ibarra", "Bonilla", "Briggs",
  "Roy", "Scholz", "van Beeck Beeckmans", "Nievo", "Vila", "Cunha",
  "Södergren", "Overgaard", "Hiltunen", "Daggeirsson", "Malõšev", "Kiška",
  "Ziemelis", "Grzenia", "Fiala", "Adamec", "Tomescu", "Viljevac",
  "Ilić", "Bəşiroğlu", "Manullang", "Njoku", "Ninalowo", "Mutai",
  "Dlaba", "Amoasi", "Schneider", "Perano", "Provost", "Díaz",
  "Dias", "Chávez", "Jiménez", "Stokes", "Klein", "Gieß",
  "Wright", "Agostinelli", "Balaguer", "Solberg", "Schmidt", "Viljanen",
  "Sillisson", "Līce", "Małyszek", "Tůma", "Tománeková", "Pintér",
  "Popescu", "Tonc", "Rupnik", "Şıxlı", "Karadeniz", "Putra",
  "Harrison", "Eze", "Afolayan", "Ouma", "Ndinisa", "Akyeampomaa",
  "Guerrero", "Kemp", "Jacques", "Ojeda", "da Conceição", "Morales",
  "Candia", "Garcés", "Power", "Haering", "van 't Houteveen", "Rosiello",
  "Cabello", "Carneiro", "Hauge", "Thomsen", "Tamminen", "Valtersson",
  "Oras", "Narušis", "Birzniece", "Pachowicz", "Král", "Pavlovičová",
  "Takács", "Gheorghiu", "Šegović", "Ramšak", "Pənahov", "İhsanoğlu",
  "Hutasoit", "Campbell", "Onwuka", "Aderogba", "Juma", "Mbhele",
  "Ahortor", "Anderson", "Gibson", "Le", "Ochoa", "Fogaça",
  "Villalba", "Carmona", "Leconte", "Ruppert", "Roukes", "Caruso",
  "Hurtado", "Gaspar", "Axelsson", "Nielsen", "Bruun", "Kankaanpää",
  "Sigurbaldsdóttir", "Stepanov", "Stankevičius", "Rudzīte", "Drygała", "Křížová",
  "Kopa", "Szücs", "Manole", "Nedić", "Pirnat", "Məhərrəmli",
  "Alemdar", "Kusmawati", "Roberts", "Odunsi", "Hussein", "Mlondo",
  "Daako", "Elliott", "Armstrong", "Fleming", "Raymond", "Leyva",
  "Rocha", "Velazquez", "Alegría", "Talbot", "Gilles", "Radisch",
  "van de Darnau", "Giovine", "Amorim", "Linder", "Myhre", "Iversen",
  "Suomalainen", "Völundsson", "Mürk", "Riekstiņš", "Talaśka", "Hušťáková",
  "Sándor", "Georgescu", "Tuđa", "Koželj", "Şirvanzadə", "Kısakürek",
  "Vũ", "Maryati", "Kabir", "Olujimi", "Hassani", "Nenzi",
  "Nyaako", "Cooksley", "Bisson", "Serrano", "Duarte", "Pino",
  "Torres", "Rogers", "Muller", "Winkler", "Hermans", "Filippini",
  "Gimenez", "Batista", "Jönsson", "Eide", "Jespersen", "Mustonen",
  "Kristjónsdóttir", "Suvi", "Alksnis", "Pyszny", "Hrubý", "Šoltésová",
  "Balogh", "Dochioiu", "Peharda", "Gregorič", "Nərimanova", "Yüksel",
  "Mai", "Nainggolan", "Ballard", "Sa'idu", "Madu", "Salako",
  "Siwele", "Connolly", "Gervais", "Guerra", "Camargo", "Gutierrez",
  "Valdivia", "Palacios", "Begum", "Krause", "van Maasgouw", "Zichichi",
  "Segarra", "Henriques", "Petersson", "Ahmed", "Heiskanen", "Hallþórsson",
  "Fedorov", "Kobel", "Martinkovičová", "Kovács", "Pop", "Paradi",
  "Zorko", "Davies", "Arellano", "Gibbs", "Godard", "Vincent",
  "Linke", "Opizzi", "Cañete", "Olivo", "Burgos", "Macedo",
  "Cirino", "Östling", "Thorsen", "Steffensen", "Simola", "Vernharðsson",
  "Mäe", "Kalvaitis", "Podniece", "Steciuk", "Matějková", "Junásová",
  "Török", "Pușcașu", "Žic", "Krajnc", "Demirel", "Yuniar",
  "Wagner", "Oluwagbemi", "Sinema", "Siyaya", "Zimmerman", "Meyer",
  "Hopkins", "Chartrand", "Börner", "Levesque", "Ceri", "Dominguez",
  "del Valle", "Suarez", "Olivares", "Ortega", "Sá", "Vieira",
  "Arvidsson", "Fredriksen", "Heikkinen", "Adríansdóttir", "Maksimov", "Kaupas",
  "Husak", "Pavlíček", "Janošeková", "Szabó", "Stănescu", "Bunčić",
  "Primožič", "Şafak", "Widodo", "Suleiman", "Olusanya", "Auma",
  "Manana", "Mullen", "North", "Holmes", "Bazin", "Perron",
  "Mies", "de Swart", "Carriera", "Garriga", "Pacheco", "Bravo",
  "Arce", "Matos", "Cavalcante", "Malm", "Jensen", "Sørensen",
  "Moilanen", "Fjölvarsdóttir", "Merila", "Priedītis", "Jeka", "Vítek",
  "Vlnková", "Eftimie", "Damjanović", "Majcen", "Şener", "Yuliarti",
  "Barnett", "Udeh", "Anyango", "Blose", "Ata", "Gross",
  "Berry", "Adam", "Delisle", "Briemer", "van Ham", "Bompiani",
  "Bolaños", "Molina", "Alvarez", "Vergara", "Fonseca", "Hultman",
  "Knudsen", "Christensen", "Pasanen", "Maxsdóttir",
];

/** 200 entries. */
export const ALIEN_MALE_GIVEN: string[] = [
  "Jorik", "Zevon", "Zevis", "Qeleth", "Voron", "Morek",
  "Tavar", "Raen", "Daeyr", "Garel", "Taleth", "Caelek",
  "Joros", "Qelath", "Coris", "Coreth", "Orveth", "Raeur",
  "Daek", "Talyn", "Fenyn", "Arveth", "Torin", "Vaelan",
  "Kharor", "Aelath", "Zhorun", "Vyrun", "Tavir", "Drexyr",
  "Zhorar", "Zaror", "Eshix", "Aelyn", "Brais", "Nexos",
  "Veken", "Nexen", "Talan", "Kharik", "Zarar", "Daean",
  "Kaelath", "Varun", "Vekon", "Kelek", "Darar", "Kharin",
  "Zaear", "Vorath", "Garos", "Drexan", "Ryner", "Raein",
  "Drexor", "Kyeth", "Vaelos", "Vyran", "Zareth", "Drexar",
  "Orrir", "Loris", "Zaeath", "Aeler", "Brair", "Kyix",
  "Orvath", "Joryr", "Xanel", "Arvik", "Caelyn", "Belath",
  "Aelen", "Caelix", "Talyr", "Coror", "Varan", "Daein",
  "Therel", "Belyr", "Vekur", "Tavun", "Saelon", "Keler",
  "Arvur", "Loran", "Fenon", "Xelik", "Drexon", "Darin",
  "Kelur", "Corar", "Caelun", "Drexix", "Therir", "Kharar",
  "Vekin", "Morur", "Yoryn", "Kaelix", "Yorir", "Ulan",
  "Jexivar", "Eranaris", "Zhoroth", "Kyur", "Raeulen", "Brenis",
  "Jorer", "Daresh", "Ulyn", "Kyulen", "Fyror", "Haleun",
  "Saelaxis", "Orrorun", "Lorin", "Rynin", "Morev", "Haleion",
  "Aelis", "Othos", "Vekorik", "Zyneron", "Esharek", "Vaelorun",
  "Kharivar", "Yevorun", "Quoroth", "Othel", "Arvix", "Kyeron",
  "Zevaris", "Iororun", "Lazoth", "Cyrorun", "Varath", "Orrulen",
  "Orrik", "Kaeloth", "Arvar", "Ulath", "Yevos", "Orror",
  "Saelan", "Weyror", "Vyrur", "Tavek", "Garoth", "Fyrur",
  "Eshos", "Rael", "Loreus", "Kaelyn", "Vossek", "Daeon",
  "Yevorik", "Corath", "Caelik", "Raeor", "Saelath", "Talir",
  "Garir", "Zaer", "Thalorik", "Eraneron", "Gevis", "Orran",
  "Gevorik", "Ulix", "Esharis", "Coran", "Nexir", "Vorivar",
  "Garor", "Kharaxis", "Xorik", "Iorir", "Rynarek", "Tavur",
  "Synun", "Maelulen", "Talix", "Jexoth", "Daeyn", "Vyrar",
  "Rhexorik", "Iorur", "Xelyr", "Eranon", "Loren", "Drexoth",
  "Lazyn", "Zynarek", "Ryneus", "Joron", "Darel", "Zaroth",
  "Torarek", "Tyrik",
];

/** 200 entries. */
export const ALIEN_FEMALE_GIVEN: string[] = [
  "Noxia", "Lumiva", "Thaearae", "Talara", "Caearae", "Oraena",
  "Kireya", "Sariel", "Sarysa", "Phaena", "Zaena", "Veyeth",
  "Seriel", "Velira", "Sarira", "Sarara", "Aeviva", "Phaeora",
  "Zirira", "Zyra", "Yvia", "Aeveth", "Lyrune", "Eirina",
  "Phaeoa", "Zieri", "Soriva", "Sareth", "Nelysa", "Noxara",
  "Enarae", "Rhena", "Thiara", "Velina", "Sorena", "Lumarae",
  "Serila", "Yarina", "Kireth", "Caeoa", "Vaira", "Ashila",
  "Veyeri", "Phaeri", "Veyiel", "Zila", "Caeia", "Oliune",
  "Zyrena", "Yareri", "Orayne", "Ciryne", "Aevina", "Aevila",
  "Zaeira", "Zirora", "Kirena", "Syreya", "Eiriva", "Thaeyne",
  "Lyrira", "Ciroa", "Rheune", "Nelune", "Yarira", "Thieya",
  "Aevysa", "Sarune", "Mirora", "Ziessa", "Lumysa", "Irysa",
  "Rheysa", "Eliarae", "Vaiel", "Oryne", "Arieya", "Oroa",
  "Talira", "Iraya", "Aevyne", "Syrarae", "Sareri", "Thioa",
  "Myryne", "Kirysa", "Rheila", "Rheth", "Soreri", "Ilyiva",
  "Neliel", "Liorira", "Velia", "Neloa", "Sorysa", "Caeune",
  "Mirena", "Thiena", "Zaeune", "Saeleth", "Ashayae", "Naiaya",
  "Ceyoa", "Oraina", "Umairi", "Maeiel", "Thaeya", "Maeyra",
  "Ashauna", "Ceyari", "Ryneva", "Naevune", "Vaeis", "Yvari",
  "Quaessae", "Ceyila", "Zirysa", "Kira", "Orarae", "Wynena",
  "Rheuna", "Brieth", "Arieva", "Eireth", "Nerinae", "Ivaysa",
  "Xaessae", "Zyraya", "Evioa", "Ivarae", "Eiressa", "Teyari",
  "Caeiva", "Zinae", "Jaeari", "Nerelle", "Oshaeri", "Ivaira",
  "Daeuna", "Naiessae", "Zyrune", "Jaeura", "Zeloa", "Olieya",
  "Ceyira", "Faelle", "Zelayae", "Naeveri", "Ilyessae", "Lumina",
  "Thaea", "Elira", "Kaeviva", "Neressa", "Ashais", "Ceyia",
  "Xaeri", "Kiriva", "Maeiri", "Thaeorae", "Eirani", "Veyuna",
  "Ashari", "Naiysa", "Phaeiri", "Ceyra", "Zeleva", "Caeara",
  "Rynura", "Saeva", "Thiri", "Eliri", "Phaeiva", "Jaeri",
  "Orainae", "Sereth", "Myresh", "Maeina", "Mirira", "Xyrorae",
  "Saeia", "Kaeveya", "Quaira", "Bria", "Syryra", "Oshara",
  "Bris", "Cirune", "Teya", "Arina", "Naevyra", "Maeis",
  "Orari", "Zyressae", "Syressae", "Ziria", "Oliarae", "Veyora",
  "Eniri", "Zirayae",
];

/** 200 entries. */
export const ALIEN_SURNAMES: string[] = [
  "Xelmar", "Morar", "Sorvos", "Ghalmar", "Vaelar", "Orath",
  "Praxsen", "Zaek", "Shalis", "Ravqel", "Ghalai", "Threxath",
  "Praxis", "Vorqel", "Drexesh", "Fenvar", "Zorath", "Myrwyn",
  "Korror", "Vyrthal", "Rynsen", "Zaewyn", "Jaxsen", "Rynvek",
  "Synvar", "Nolar", "Kyrqel", "Quenin", "Zaein", "Belvos",
  "Ghalek", "Rhelyx", "Rhelqel", "Tyrmar", "Kaervek", "Kharvos",
  "Zaevar", "Rynthal", "Korrvek", "Zharvar", "Vyror", "Fenath",
  "Noldren", "Lethrath", "Vorrath", "Synar", "Fenin", "Qarwyn",
  "Fenyx", "Tharthal", "Nolath", "Talthal", "Kelor", "Ghalthal",
  "Tyresh", "Tharqel", "Vhalyx", "Ravrath", "Praxath", "Ravsen",
  "Nolthal", "Kharmar", "Azhvar", "Zoror", "Vhalmar", "Xelath",
  "Torvos", "Kelai", "Vyrek", "Rhelvos", "Myrath", "Ravesh",
  "Nolvos", "Vyrrath", "Fenvek", "Vekesh", "Rynqel", "Vekdren",
  "Synvek", "Jaxesh", "Lorrath", "Varai", "Nexvar", "Fenrath",
  "Kyrmar", "Saelrath", "Soror", "Kharai", "Varvek", "Sorvar",
  "Ravdren", "Oththal", "Talrath", "Rynvos", "Rynmar", "Korrvos",
  "Rhelvar", "Qarrath", "Dravar", "Zevesh", "Fexor", "Zharai",
  "Zaesen", "Tvekavel", "Tormir", "Praxeth", "Sornir", "Othakar",
  "Nolun", "Taltov", "Zhalyx", "Ishath", "Lyrkar", "Azhakar",
  "Nyrai", "Vhalvos", "Quenrath", "Phalorin", "Rynrax", "Zharesh",
  "Sorai", "Yevek", "Qiror", "Lyror", "Vorquin", "Quenthal",
  "Voreshk", "Qarqel", "Letharis", "Belar", "Tvekeshk", "Vekun",
  "Voris", "Vekvek", "Tyrek", "Xelkar", "Qarek", "Sornvar",
  "Nexwyn", "Tharesh", "Vhalir", "Korreon", "Nolwyn", "Feneshk",
  "Korryx", "Coreth", "Quenis", "Zorquin", "Yevar", "Yeveon",
  "Veynmar", "Quenrax", "Orryx", "Orrvar", "Azhavel", "Tyreth",
  "Coris", "Drexthal", "Beleon", "Synir", "Nyrakar", "Korrrax",
  "Vyrmir", "Khareshk", "Dramir", "Drexvar", "Vyrwyn", "Raveon",
  "Lyrvar", "Rhexrath", "Korrorin", "Zhalwyn", "Gorrar", "Tharor",
  "Sorir", "Tyrorin", "Vaelwyn", "Korrtov", "Ghalrath", "Orrar",
  "Kelrath", "Nyrqel", "Ravrax", "Jorsen", "Zharthal", "Tyroren",
  "Tvekmar", "Synmir", "Azheth", "Tvekoren", "Sornun", "Zhalrath",
  "Taleth", "Urryx", "Vaelzar", "Rynrath", "Urris", "Tyrath",
  "Drexir", "Nyrmir",
];
