/**
 * PERSONALITY — the canonical trait library. Authored data, no logic.
 *
 * All 250 traits, each carrying its own mechanics straight from the Part IV
 * matrix: its own favoured tags, opposed tags, intensity and rule. Nothing
 * here is a synonym for anything else, and no trait resolves by being
 * translated into a shared behaviour class.
 *
 * Every visible name is unique, and identity is the id — never the label.
 *
 * `favored` is what this person is drawn to and steadied by.
 * `opposed` is what costs them.
 * `context` marks a rule that only applies in a matching situation.
 * `decay` is how long they hold a reaction.
 * `attribute` keeps a word off somebody the numbers contradict.
 */

import type { AttributeKey } from '../engine/types';

/**
 * A semantic tag on a choice, an outcome or an action. The world emits
 * these; traits subscribe to them. The vocabulary is open on purpose: the
 * matrix names far more than the game currently emits, and the rest stay as
 * dormant hooks rather than being trimmed away.
 */
export type PersonalityTag = string;

export type TraitIntensity = 'mild' | 'moderate' | 'strong' | 'extreme';

/** Situations a rule can be limited to. */
export type TraitContext = 'crisis' | 'protecting' | 'traumaEcho';

export type PersonalityGroup =
  | 'Courage & Fear'
  | 'Honesty & Secrecy'
  | 'Loyalty & Attachment'
  | 'Authority & Control'
  | 'Compassion & Hardness'
  | 'Risk & Reward'
  | 'Social Style'
  | 'Conflict Style'
  | 'Discipline & Routine'
  | 'Ambition & Status'
  | 'Money & Possessions'
  | 'Curiosity & Knowledge'
  | 'Planning & Decision Making'
  | 'Emotional Regulation'
  | 'Trust & Suspicion'
  | 'Responsibility & Guilt'
  | 'Ideals & Principles'
  | 'Work & Competence'
  | 'Exploration & Novelty'
  | 'Violence & Combat Attitude'
  | 'Hope & Outlook'
  | 'Independence & Cooperation'
  | 'Patience & Time'
  | 'Pride & Shame'
  | 'Humor & Demeanor';

export interface PersonalityTrait {
  id: string;
  label: string;
  group: PersonalityGroup;
  /** What this person is drawn to, and steadied by. */
  favored: PersonalityTag[];
  /** What costs them, in morale or in stress. */
  opposed: PersonalityTag[];
  intensity: TraitIntensity;
  /** Reactions linger rather than fading at the normal rate. */
  persistence?: boolean;
  /**
   * How long this person holds a reaction. `slow` keeps a grudge and a good
   * turn alike; `fast` lets both go. Read off the authored rule.
   */
  decay?: 'slow' | 'fast';
  /** The rule only applies in this situation. */
  context?: TraitContext;
  /** The authored mechanical identity, shown to the player as what they do. */
  rule: string;
  attribute?: AttributeKey;
  direction?: 'high' | 'low';
}

export const PERSONALITY_TRAITS: PersonalityTrait[] = [
  {
    id: 'brave',
    label: 'Brave',
    group: 'Courage & Fear',
    favored: ['danger', 'physical_risk'],
    opposed: ['cowardly_retreat'],
    intensity: 'moderate',
    rule: 'reduced stress from chosen danger; autonomous choices lean toward reasonable risk, especially when purpose is clear.',
  },
  {
    id: 'cautious',
    label: 'Cautious',
    group: 'Courage & Fear',
    favored: ['plan', 'verify', 'retreat'],
    opposed: ['blind_risk', 'reckless_action'],
    intensity: 'moderate',
    rule: 'gains stability from preparation; unnecessary risk adds stress; prefers scouting, safer routes, and contingency plans.',
  },
  {
    id: 'fearless',
    label: 'Fearless',
    group: 'Courage & Fear',
    favored: ['danger', 'physical_risk'],
    opposed: ['panic'],
    intensity: 'strong',
    rule: 'physical danger creates much less stress; may underweight danger in autonomous choices, but does not seek violence by itself.',
  },
  {
    id: 'anxious',
    label: 'Anxious',
    group: 'Courage & Fear',
    favored: ['verify', 'plan', 'safety'],
    opposed: ['uncertainty', 'unresolved_threat'],
    intensity: 'moderate',
    rule: 'uncertainty and unverified danger accumulate stress; information and a concrete plan reduce it.',
  },
  {
    id: 'timid',
    label: 'Timid',
    group: 'Courage & Fear',
    favored: ['retreat', 'safety'],
    opposed: ['confrontation', 'extreme_risk'],
    intensity: 'strong',
    rule: 'direct confrontation and extreme risk add stress; autonomous behavior favors escape/avoidance unless bonds or duty override.',
  },
  {
    id: 'adrenaline-seeking',
    label: 'Adrenaline-Seeking',
    group: 'Courage & Fear',
    favored: ['danger', 'novelty', 'gamble'],
    opposed: ['routine', 'excessive_safety'],
    intensity: 'moderate',
    rule: 'successful high-risk action gives morale; prolonged safety/routine can slightly reduce morale; autonomous risk weight rises.',
  },
  {
    id: 'trauma-wary',
    label: 'Trauma-Wary',
    group: 'Courage & Fear',
    favored: ['safety', 'avoid_trigger'],
    opposed: ['trauma_echo', 'similar_danger'],
    intensity: 'strong',
    context: 'traumaEcho',
    rule: 'when current tags match a qualifying past life-event trauma, stress response is amplified and avoidance weight rises.',
  },
  {
    id: 'steady-under-fire',
    label: 'Steady Under Fire',
    group: 'Courage & Fear',
    favored: ['combat', 'immediate_crisis', 'calm'],
    opposed: ['panic'],
    intensity: 'strong',
    context: 'crisis',
    rule: 'stress penalties during active danger are reduced and delegated decision weighting stays less distorted by panic.',
  },
  {
    id: 'panic-prone',
    label: 'Panic-Prone',
    group: 'Courage & Fear',
    favored: ['retreat', 'reassurance'],
    opposed: ['sudden_crisis', 'ambush', 'isolation'],
    intensity: 'strong',
    context: 'crisis',
    rule: 'sudden danger spikes stress more; high stress strongly increases escape/simple-choice weighting until stabilized.',
  },
  {
    id: 'protective-courage',
    label: 'Protective Courage',
    group: 'Courage & Fear',
    favored: ['protect_others', 'rescue'],
    opposed: ['abandon_others'],
    intensity: 'strong',
    context: 'protecting',
    rule: 'risk tolerance rises sharply when protecting crew/family/dependents; abandoning a reachable person costs morale.',
  },
  {
    id: 'honest',
    label: 'Honest',
    group: 'Honesty & Secrecy',
    favored: ['honesty', 'disclosure'],
    opposed: ['deception'],
    intensity: 'moderate',
    rule: 'lying for convenience costs morale; truth-telling under pressure can improve morale and relationship trust.',
  },
  {
    id: 'blunt',
    label: 'Blunt',
    group: 'Honesty & Secrecy',
    favored: ['honesty', 'directness'],
    opposed: ['social_smoothing', 'evasiveness'],
    intensity: 'mild',
    rule: 'prefers direct options; diplomatic euphemism has little appeal; blunt delivery can create relationship friction with sensitive characters.',
  },
  {
    id: 'diplomatic',
    label: 'Diplomatic',
    group: 'Honesty & Secrecy',
    favored: ['deescalation', 'tact', 'compromise'],
    opposed: ['humiliation', 'needless_confrontation'],
    intensity: 'moderate',
    rule: 'gains morale from resolving conflict without needless damage; autonomous dialogue favors tactful compromise.',
  },
  {
    id: 'secretive',
    label: 'Secretive',
    group: 'Honesty & Secrecy',
    favored: ['secrecy', 'privacy'],
    opposed: ['forced_disclosure'],
    intensity: 'moderate',
    rule: 'revealing personal/strategic information adds stress; withholding information is favored when consequences are uncertain.',
  },
  {
    id: 'deceptive',
    label: 'Deceptive',
    group: 'Honesty & Secrecy',
    favored: ['deception', 'manipulation'],
    opposed: ['compelled_honesty'],
    intensity: 'moderate',
    rule: 'deception carries little internal cost and may gain morale when it succeeds; autonomous social choices use misdirection more readily.',
  },
  {
    id: 'confessional',
    label: 'Confessional',
    group: 'Honesty & Secrecy',
    favored: ['disclosure', 'accountability'],
    opposed: ['concealment_after_failure'],
    intensity: 'moderate',
    rule: 'carrying a secret after personal wrongdoing adds stress; confession/restitution reduces it.',
  },
  {
    id: 'guarded',
    label: 'Guarded',
    group: 'Honesty & Secrecy',
    favored: ['privacy', 'caution'],
    opposed: ['vulnerability', 'rapid_trust'],
    intensity: 'moderate',
    decay: 'fast',
    rule: 'intimate disclosure and premature trust add stress; relationships deepen more slowly but can become normal once established.',
  },
  {
    id: 'transparent',
    label: 'Transparent',
    group: 'Honesty & Secrecy',
    favored: ['disclosure', 'honesty'],
    opposed: ['hidden_agenda', 'secrecy'],
    intensity: 'moderate',
    rule: 'concealed plans create stress; open communication improves morale/relationship confidence.',
  },
  {
    id: 'manipulative',
    label: 'Manipulative',
    group: 'Honesty & Secrecy',
    favored: ['manipulation', 'leverage'],
    opposed: ['loss_of_control'],
    intensity: 'moderate',
    rule: 'autonomous choices favor indirect influence and asymmetric information; being manipulated by others produces strong resentment.',
  },
  {
    id: 'principled-honesty',
    label: 'Principled Honesty',
    group: 'Honesty & Secrecy',
    favored: ['honesty', 'promise'],
    opposed: ['deception_for_convenience'],
    intensity: 'strong',
    rule: 'knowingly lying for selfish/trivial gain costs substantial morale; deception to prevent grave harm remains possible with reduced penalty.',
  },
  {
    id: 'loyal',
    label: 'Loyal',
    group: 'Loyalty & Attachment',
    favored: ['crew', 'protect_others', 'promise'],
    opposed: ['betrayal', 'abandon_ally'],
    intensity: 'moderate',
    decay: 'slow',
    rule: 'supporting established allies improves morale/relationships; betraying them creates lingering penalties.',
  },
  {
    id: 'fiercely-loyal',
    label: 'Fiercely Loyal',
    group: 'Loyalty & Attachment',
    favored: ['crew', 'family', 'rescue'],
    opposed: ['betrayal', 'abandon_ally'],
    intensity: 'strong',
    rule: 'major cost for abandoning close bonds; rescue/defense choices gain strong autonomous weight.',
  },
  {
    id: 'detached',
    label: 'Detached',
    group: 'Loyalty & Attachment',
    favored: ['autonomy', 'practicality'],
    opposed: ['forced_attachment'],
    intensity: 'mild',
    rule: 'relationship losses have reduced morale impact; can make separation decisions with less internal cost.',
  },
  {
    id: 'family-oriented',
    label: 'Family-Oriented',
    group: 'Loyalty & Attachment',
    favored: ['family', 'home', 'protect_dependents'],
    opposed: ['neglect_family', 'abandon_family'],
    intensity: 'strong',
    rule: 'family safety and contact strongly affect morale; family-related choices receive high priority.',
  },
  {
    id: 'crew-oriented',
    label: 'Crew-Oriented',
    group: 'Loyalty & Attachment',
    favored: ['crew', 'cooperation', 'protect_others'],
    opposed: ['sacrifice_crew', 'crew_fragmentation'],
    intensity: 'strong',
    rule: 'crew cohesion and safety strongly affect morale; favors solutions that preserve the group.',
  },
  {
    id: 'possessive',
    label: 'Possessive',
    group: 'Loyalty & Attachment',
    favored: ['bond_exclusivity', 'control'],
    opposed: ['rejection', 'bond_threat'],
    intensity: 'strong',
    rule: 'perceived loss of an important bond creates stress and jealousy; may favor controlling relationship choices.',
  },
  {
    id: 'independent',
    label: 'Independent',
    group: 'Loyalty & Attachment',
    favored: ['autonomy', 'self_reliance'],
    opposed: ['control', 'dependency'],
    intensity: 'moderate',
    rule: 'gains morale from self-directed action; micromanagement/control adds stress; may resist obligations without clear consent.',
  },
  {
    id: 'devoted',
    label: 'Devoted',
    group: 'Loyalty & Attachment',
    favored: ['duty_to_person_or_cause', 'sacrifice'],
    opposed: ['abandon_commitment'],
    intensity: 'strong',
    rule: 'can accept severe hardship for a chosen bond/cause with reduced stress; breaking that devotion is costly.',
  },
  {
    id: 'slow-to-attach',
    label: 'Slow to Attach',
    group: 'Loyalty & Attachment',
    favored: ['caution', 'evidence_of_trust'],
    opposed: ['rapid_intimacy'],
    intensity: 'mild',
    rule: 'new relationships produce smaller morale swings; trust/attachment grows slowly through repeated evidence.',
  },
  {
    id: 'easily-attached',
    label: 'Easily Attached',
    group: 'Loyalty & Attachment',
    favored: ['socialize', 'new_bond'],
    opposed: ['rejection', 'separation'],
    intensity: 'moderate',
    rule: 'relationships become morale-relevant quickly; separation/betrayal by newer companions hurts more than normal.',
  },
  {
    id: 'authoritarian',
    label: 'Authoritarian',
    group: 'Authority & Control',
    favored: ['authority', 'command', 'hierarchy'],
    opposed: ['insubordination', 'diffuse_control'],
    intensity: 'moderate',
    rule: 'clear hierarchy stabilizes morale; autonomous leadership favors direct orders and enforcement.',
  },
  {
    id: 'democratic',
    label: 'Democratic',
    group: 'Authority & Control',
    favored: ['consensus', 'consultation'],
    opposed: ['unilateral_command'],
    intensity: 'moderate',
    rule: 'consultation improves morale; major unilateral decisions affecting others create friction.',
  },
  {
    id: 'controlling',
    label: 'Controlling',
    group: 'Authority & Control',
    favored: ['control', 'plan', 'oversight'],
    opposed: ['uncertainty', 'delegation_without_visibility'],
    intensity: 'strong',
    rule: 'loss of control raises stress; favors oversight, explicit plans, and checking delegated work.',
  },
  {
    id: 'delegating',
    label: 'Delegating',
    group: 'Authority & Control',
    favored: ['delegation', 'trust', 'specialization'],
    opposed: ['micromanagement'],
    intensity: 'moderate',
    rule: 'successful delegation improves morale; autonomous leadership uses qualified specialists instead of personally controlling everything.',
  },
  {
    id: 'rebellious',
    label: 'Rebellious',
    group: 'Authority & Control',
    favored: ['autonomy', 'lawbreaking_when_oppressive'],
    opposed: ['authority', 'coercion'],
    intensity: 'strong',
    rule: 'imposed authority and coercion raise stress; defiance options gain weight when rules feel illegitimate.',
  },
  {
    id: 'rule-following',
    label: 'Rule-Following',
    group: 'Authority & Control',
    favored: ['rules', 'institution', 'procedure'],
    opposed: ['lawbreaking', 'corruption'],
    intensity: 'moderate',
    rule: 'lawful/procedural choices improve stability; casual rule-breaking creates morale friction.',
  },
  {
    id: 'pragmatic-about-rules',
    label: 'Pragmatic About Rules',
    group: 'Authority & Control',
    favored: ['outcome', 'flexibility'],
    opposed: ['rigid_procedure'],
    intensity: 'mild',
    rule: 'little emotional cost for minor rule-breaking when outcomes justify it; does not seek illegality for its own sake.',
  },
  {
    id: 'commanding',
    label: 'Commanding',
    group: 'Authority & Control',
    favored: ['command', 'decisive_action'],
    opposed: ['leadership_vacuum'],
    intensity: 'moderate',
    rule: 'taking charge during uncertainty reduces stress; autonomous behavior steps into leadership gaps.',
  },
  {
    id: 'conflict-avoidant-leader',
    label: 'Conflict-Avoidant Leader',
    group: 'Authority & Control',
    favored: ['consensus', 'deescalation'],
    opposed: ['discipline', 'confrontation'],
    intensity: 'moderate',
    rule: 'direct disciplinary confrontation adds stress; favors mediation and indirect correction even when slower.',
    attribute: 'leadership',
    direction: 'low',
  },
  {
    id: 'hands-off',
    label: 'Hands-Off',
    group: 'Authority & Control',
    favored: ['delegation', 'autonomy'],
    opposed: ['micromanagement'],
    intensity: 'moderate',
    rule: 'prefers broad objectives and trusted autonomy; detailed control of others creates friction.',
    attribute: 'leadership',
    direction: 'low',
  },
  {
    id: 'compassionate',
    label: 'Compassionate',
    group: 'Compassion & Hardness',
    favored: ['compassion', 'rescue', 'aid'],
    opposed: ['cruelty', 'abandonment'],
    intensity: 'strong',
    rule: 'helping genuine need improves morale; preventable suffering caused/ignored creates morale loss.',
  },
  {
    id: 'merciful',
    label: 'Merciful',
    group: 'Compassion & Hardness',
    favored: ['mercy', 'second_chance'],
    opposed: ['execution', 'harsh_punishment'],
    intensity: 'strong',
    rule: 'unnecessary harsh punishment costs morale; mercy is favored when risk remains acceptable.',
  },
  {
    id: 'hard-hearted',
    label: 'Hard-Hearted',
    group: 'Compassion & Hardness',
    favored: ['practicality', 'harsh_necessity'],
    opposed: ['sentimental_sacrifice'],
    intensity: 'moderate',
    rule: 'reduced morale penalty from harsh but useful decisions; may undervalue emotional harm in autonomous choices.',
  },
  {
    id: 'empathetic',
    label: 'Empathetic',
    group: 'Compassion & Hardness',
    favored: ['emotional_support', 'compassion'],
    opposed: ['crew_suffering', 'humiliation'],
    intensity: 'strong',
    rule: 'others\' suffering has larger morale/stress impact; supportive choices gain weight.',
  },
  {
    id: 'unsympathetic',
    label: 'Unsympathetic',
    group: 'Compassion & Hardness',
    favored: ['practicality', 'task_focus'],
    opposed: ['emotional_burden'],
    intensity: 'mild',
    rule: 'others\' distress has reduced effect on morale; fewer autonomous resources spent purely on comfort.',
  },
  {
    id: 'protective-of-the-weak',
    label: 'Protective of the Weak',
    group: 'Compassion & Hardness',
    favored: ['protect_vulnerable', 'rescue'],
    opposed: ['exploitation', 'abandon_vulnerable'],
    intensity: 'strong',
    rule: 'exploitation of vulnerable people produces anger/stress; intervention choices gain major weight.',
  },
  {
    id: 'utilitarian',
    label: 'Utilitarian',
    group: 'Compassion & Hardness',
    favored: ['save_many', 'efficiency', 'outcome'],
    opposed: ['wasteful_sacrifice'],
    intensity: 'strong',
    rule: 'autonomous decisions favor total expected benefit; sacrificing a few to save many carries reduced internal cost.',
  },
  {
    id: 'forgiving',
    label: 'Forgiving',
    group: 'Compassion & Hardness',
    favored: ['reconciliation', 'second_chance'],
    opposed: ['ongoing_revenge'],
    intensity: 'moderate',
    decay: 'fast',
    rule: 'betrayal penalties decay faster after sincere repair; forgiveness options gain weight.',
  },
  {
    id: 'vindictive',
    label: 'Vindictive',
    group: 'Compassion & Hardness',
    favored: ['punishment', 'retaliation'],
    opposed: ['forgiveness_without_cost'],
    intensity: 'strong',
    decay: 'slow',
    rule: 'betrayal creates persistent relationship penalty; retaliation can restore some morale, forgiveness is emotionally costly.',
  },
  {
    id: 'gentle',
    label: 'Gentle',
    group: 'Compassion & Hardness',
    favored: ['nonviolence', 'compassion'],
    opposed: ['personally_inflicted_harm'],
    intensity: 'strong',
    rule: 'personally causing suffering adds stress; nonviolent solutions gain weight.',
  },
  {
    id: 'risk-taker',
    label: 'Risk-Taker',
    group: 'Risk & Reward',
    favored: ['gamble', 'opportunity', 'physical_risk'],
    opposed: ['excessive_caution'],
    intensity: 'moderate',
    rule: 'successful gambles improve morale; autonomous choices accept worse odds for higher payoff.',
  },
  {
    id: 'risk-averse',
    label: 'Risk-Averse',
    group: 'Risk & Reward',
    favored: ['conserve', 'safety', 'plan'],
    opposed: ['gamble', 'unnecessary_risk'],
    intensity: 'strong',
    rule: 'unnecessary risk adds stress; favors safer routes and reserve preservation.',
  },
  {
    id: 'calculated',
    label: 'Calculated',
    group: 'Risk & Reward',
    favored: ['verify', 'plan', 'opportunity'],
    opposed: ['blind_risk'],
    intensity: 'moderate',
    rule: 'risk is acceptable when odds are understood; unknown odds reduce autonomous willingness sharply.',
    attribute: 'evaluation',
    direction: 'high',
  },
  {
    id: 'gambler',
    label: 'Gambler',
    group: 'Risk & Reward',
    favored: ['gamble', 'uncertain_reward'],
    opposed: ['guaranteed_small_gain'],
    intensity: 'strong',
    rule: 'uncertain high-payoff options gain large weight; wins boost morale, losses can trigger stronger negative swings.',
  },
  {
    id: 'conservative',
    label: 'Conservative',
    group: 'Risk & Reward',
    favored: ['conserve', 'save', 'stability'],
    opposed: ['speculation', 'overextension'],
    intensity: 'moderate',
    rule: 'preserving resources improves morale; speculative commitments create stress.',
  },
  {
    id: 'opportunistic',
    label: 'Opportunistic',
    group: 'Risk & Reward',
    favored: ['opportunity', 'improvisation'],
    opposed: ['missed_opportunity'],
    intensity: 'moderate',
    rule: 'sudden advantageous openings gain weight; passing a low-cost opportunity can mildly reduce morale.',
  },
  {
    id: 'strategically-patient',
    label: 'Strategically Patient',
    group: 'Risk & Reward',
    favored: ['patience', 'wait', 'plan'],
    opposed: ['premature_action'],
    intensity: 'moderate',
    rule: 'waiting for better odds carries little stress; premature action is disfavored.',
  },
  {
    id: 'impulsive',
    label: 'Impulsive',
    group: 'Risk & Reward',
    favored: ['decisive_action', 'novelty'],
    opposed: ['delay', 'overplanning'],
    intensity: 'moderate',
    rule: 'prolonged deliberation adds stress; immediate options gain weight, especially under uncertainty.',
  },
  {
    id: 'all-in',
    label: 'All-In',
    group: 'Risk & Reward',
    favored: ['commitment', 'decisive_action'],
    opposed: ['hedging_after_commitment'],
    intensity: 'strong',
    rule: 'once convinced/committed, heavily favors full commitment and dislikes partial retreat.',
  },
  {
    id: 'hedging',
    label: 'Hedging',
    group: 'Risk & Reward',
    favored: ['contingency', 'reserve', 'partial_commitment'],
    opposed: ['all_in'],
    intensity: 'moderate',
    rule: 'keeping fallback options reduces stress; irreversible commitments without backup are disfavored.',
  },
  {
    id: 'charismatic',
    label: 'Charismatic',
    group: 'Social Style',
    favored: ['socialize', 'persuade', 'recognition'],
    opposed: ['isolation'],
    intensity: 'mild',
    rule: 'positive social interaction improves morale; autonomous behavior more readily engages people.',
    attribute: 'charisma',
    direction: 'high',
  },
  {
    id: 'reserved',
    label: 'Reserved',
    group: 'Social Style',
    favored: ['privacy', 'small_group', 'solitude'],
    opposed: ['public_exposure'],
    intensity: 'mild',
    rule: 'privacy restores stress; unnecessary public attention creates friction.',
    attribute: 'charisma',
    direction: 'low',
  },
  {
    id: 'outgoing',
    label: 'Outgoing',
    group: 'Social Style',
    favored: ['socialize', 'networking'],
    opposed: ['isolation'],
    intensity: 'moderate',
    rule: 'prolonged isolation lowers morale; social opportunities gain autonomous weight.',
    attribute: 'charisma',
    direction: 'high',
  },
  {
    id: 'introverted',
    label: 'Introverted',
    group: 'Social Style',
    favored: ['solitude', 'privacy'],
    opposed: ['constant_socializing'],
    intensity: 'moderate',
    rule: 'quiet time reduces stress; prolonged dense social exposure can raise it.',
    attribute: 'charisma',
    direction: 'low',
  },
  {
    id: 'warm',
    label: 'Warm',
    group: 'Social Style',
    favored: ['emotional_support', 'socialize'],
    opposed: ['coldness', 'rejection'],
    intensity: 'moderate',
    rule: 'supportive interactions strengthen relationships faster; hostile/cold treatment hurts more.',
    attribute: 'charisma',
    direction: 'high',
  },
  {
    id: 'aloof',
    label: 'Aloof',
    group: 'Social Style',
    favored: ['autonomy', 'emotional_distance'],
    opposed: ['forced_intimacy'],
    intensity: 'mild',
    rule: 'social approval has reduced morale impact; deep disclosure is disfavored.',
    attribute: 'charisma',
    direction: 'low',
  },
  {
    id: 'charming',
    label: 'Charming',
    group: 'Social Style',
    favored: ['persuade', 'humor', 'socialize'],
    opposed: ['humiliation'],
    intensity: 'mild',
    rule: 'successful social influence improves morale; playful persuasion options gain weight.',
    attribute: 'charisma',
    direction: 'high',
  },
  {
    id: 'awkward',
    label: 'Awkward',
    group: 'Social Style',
    favored: ['directness', 'small_group'],
    opposed: ['public_social_pressure'],
    intensity: 'moderate',
    rule: 'failed/high-pressure social situations create extra stress; may favor simpler direct responses.',
    attribute: 'socialAwareness',
    direction: 'low',
  },
  {
    id: 'formal',
    label: 'Formal',
    group: 'Social Style',
    favored: ['procedure', 'respect', 'institution'],
    opposed: ['casual_disrespect'],
    intensity: 'mild',
    rule: 'role-appropriate conduct improves comfort; sloppy familiarity in formal contexts causes friction.',
    attribute: 'discipline',
    direction: 'high',
  },
  {
    id: 'casual',
    label: 'Casual',
    group: 'Social Style',
    favored: ['informality', 'humor'],
    opposed: ['ceremony', 'rigid_formality'],
    intensity: 'mild',
    rule: 'informal interaction lowers stress; excessive ceremony is mildly disfavored.',
    attribute: 'discipline',
    direction: 'low',
  },
  {
    id: 'confrontational',
    label: 'Confrontational',
    group: 'Conflict Style',
    favored: ['confrontation', 'directness'],
    opposed: ['avoidance'],
    intensity: 'moderate',
    rule: 'unresolved conflict creates stress; direct challenge options gain weight.',
  },
  {
    id: 'avoidant',
    label: 'Avoidant',
    group: 'Conflict Style',
    favored: ['deescalation', 'retreat'],
    opposed: ['confrontation'],
    intensity: 'strong',
    rule: 'interpersonal conflict adds stress; favors withdrawal, delay, or indirect resolution.',
    attribute: 'leadership',
    direction: 'low',
  },
  {
    id: 'mediator',
    label: 'Mediator',
    group: 'Conflict Style',
    favored: ['consensus', 'deescalation', 'fairness'],
    opposed: ['escalation'],
    intensity: 'strong',
    rule: 'resolving disputes fairly improves morale; mediation options gain weight.',
  },
  {
    id: 'argumentative',
    label: 'Argumentative',
    group: 'Conflict Style',
    favored: ['debate', 'confrontation'],
    opposed: ['unchallenged_claim'],
    intensity: 'moderate',
    rule: 'rebuttal/challenge options gain weight; being unable to contest something can cause frustration.',
  },
  {
    id: 'peacemaker',
    label: 'Peacemaker',
    group: 'Conflict Style',
    favored: ['nonviolence', 'deescalation'],
    opposed: ['escalation', 'aggression'],
    intensity: 'strong',
    rule: 'ending hostility improves morale; unnecessary escalation costs morale.',
  },
  {
    id: 'intimidating',
    label: 'Intimidating',
    group: 'Conflict Style',
    favored: ['authority', 'threat', 'dominance'],
    opposed: ['being_dominated'],
    intensity: 'moderate',
    rule: 'intimidation options gain weight; backing down to coercion creates stress/resentment.',
  },
  {
    id: 'passive-aggressive',
    label: 'Passive-Aggressive',
    group: 'Conflict Style',
    favored: ['indirect_conflict', 'resentment'],
    opposed: ['direct_confrontation'],
    intensity: 'moderate',
    rule: 'avoids direct conflict but stores relationship penalties; may choose indirect retaliation.',
  },
  {
    id: 'stoic-in-conflict',
    label: 'Stoic in Conflict',
    group: 'Conflict Style',
    favored: ['calm', 'confrontation'],
    opposed: ['panic'],
    intensity: 'moderate',
    rule: 'social conflict produces less stress; relationship decisions remain steadier under pressure.',
    attribute: 'composure',
    direction: 'high',
  },
  {
    id: 'hot-tempered',
    label: 'Hot-Tempered',
    group: 'Conflict Style',
    favored: ['aggression', 'immediate_response'],
    opposed: ['insult', 'provocation'],
    intensity: 'strong',
    rule: 'insult/provocation spikes stress/anger and increases confrontational option weights until cooled.',
  },
  {
    id: 'grudge-holding',
    label: 'Grudge-Holding',
    group: 'Conflict Style',
    favored: ['punishment', 'distance'],
    opposed: ['forgiveness'],
    intensity: 'strong',
    persistence: true,
    decay: 'slow',
    rule: 'betrayal/insult relationship penalties decay slowly without restitution.',
  },
  {
    id: 'disciplined',
    label: 'Disciplined',
    group: 'Discipline & Routine',
    favored: ['routine', 'duty', 'plan'],
    opposed: ['neglect', 'procrastination'],
    intensity: 'moderate',
    rule: 'completing planned responsibilities improves morale; abandoning routine creates friction.',
  },
  {
    id: 'chaotic',
    label: 'Chaotic',
    group: 'Discipline & Routine',
    favored: ['improvise', 'novelty'],
    opposed: ['rigid_routine'],
    intensity: 'moderate',
    rule: 'rigid repetitive schedules reduce morale; improvisational solutions gain weight.',
  },
  {
    id: 'methodical',
    label: 'Methodical',
    group: 'Discipline & Routine',
    favored: ['plan', 'verify', 'thoroughness'],
    opposed: ['rushed_action'],
    intensity: 'moderate',
    decay: 'fast',
    rule: 'stepwise preparation lowers stress; rushed execution is disfavored.',
  },
  {
    id: 'procrastinating',
    label: 'Procrastinating',
    group: 'Discipline & Routine',
    favored: ['delay', 'comfort'],
    opposed: ['deadline', 'immediate_task'],
    intensity: 'moderate',
    rule: 'Mild immediate benefit from delay but rising stress as deadlines approach; autonomous task start is delayed.',
    attribute: 'discipline',
    direction: 'low',
  },
  {
    id: 'habitual',
    label: 'Habitual',
    group: 'Discipline & Routine',
    favored: ['routine', 'familiarity'],
    opposed: ['disruption', 'novelty'],
    intensity: 'moderate',
    rule: 'routines stabilize morale; sudden schedule disruption creates stress.',
  },
  {
    id: 'flexible',
    label: 'Flexible',
    group: 'Discipline & Routine',
    favored: ['improvise', 'adaptation'],
    opposed: ['rigidity'],
    intensity: 'moderate',
    rule: 'plan changes produce little stress; alternate methods gain weight.',
    attribute: 'discipline',
    direction: 'low',
  },
  {
    id: 'perfectionist',
    label: 'Perfectionist',
    group: 'Discipline & Routine',
    favored: ['craft_quality', 'thoroughness'],
    opposed: ['sloppy_result', 'good_enough'],
    intensity: 'strong',
    rule: 'excellent outcomes improve morale; accepting visibly poor work costs morale/time preference.',
  },
  {
    id: 'good-enough-pragmatist',
    label: 'Good-Enough Pragmatist',
    group: 'Discipline & Routine',
    favored: ['efficiency', 'speed'],
    opposed: ['perfectionism', 'overwork'],
    intensity: 'moderate',
    rule: 'functional solutions are satisfying; extra cost for marginal quality is disfavored.',
  },
  {
    id: 'workaholic',
    label: 'Workaholic',
    group: 'Discipline & Routine',
    favored: ['work', 'productivity'],
    opposed: ['idle_time', 'rest'],
    intensity: 'moderate',
    rule: 'productive work improves morale; prolonged idleness hurts morale, but fatigue risk still applies normally.',
  },
  {
    id: 'rest-protective',
    label: 'Rest-Protective',
    group: 'Discipline & Routine',
    favored: ['rest', 'recovery', 'comfort'],
    opposed: ['overwork'],
    intensity: 'moderate',
    rule: 'adequate recovery improves morale; repeated unnecessary work while exhausted creates stress/resentment.',
  },
  {
    id: 'ambitious',
    label: 'Ambitious',
    group: 'Ambition & Status',
    favored: ['achievement', 'promotion', 'opportunity'],
    opposed: ['stagnation'],
    intensity: 'moderate',
    rule: 'advancement improves morale; repeated stagnation can lower it.',
  },
  {
    id: 'content',
    label: 'Content',
    group: 'Ambition & Status',
    favored: ['stability', 'present'],
    opposed: ['status_chasing'],
    intensity: 'mild',
    rule: 'little morale gain from prestige; can reject advancement without penalty.',
  },
  {
    id: 'competitive',
    label: 'Competitive',
    group: 'Ambition & Status',
    favored: ['competition', 'achievement'],
    opposed: ['losing_to_rival'],
    intensity: 'moderate',
    rule: 'outperforming rivals improves morale; losing to comparable rivals hurts more.',
  },
  {
    id: 'status-conscious',
    label: 'Status-Conscious',
    group: 'Ambition & Status',
    favored: ['status', 'reputation'],
    opposed: ['humiliation', 'low_status'],
    intensity: 'strong',
    rule: 'public status changes strongly affect morale; save-face options gain weight.',
  },
  {
    id: 'unassuming',
    label: 'Unassuming',
    group: 'Ambition & Status',
    favored: ['service', 'cooperation'],
    opposed: ['boasting', 'recognition'],
    intensity: 'mild',
    rule: 'recognition has muted effect; giving away credit carries little cost.',
  },
  {
    id: 'recognition-seeking',
    label: 'Recognition-Seeking',
    group: 'Ambition & Status',
    favored: ['recognition', 'public_success'],
    opposed: ['ignored_success'],
    intensity: 'moderate',
    rule: 'praise/visibility improves morale; being overlooked after major contribution hurts.',
  },
  {
    id: 'legacy-minded',
    label: 'Legacy-Minded',
    group: 'Ambition & Status',
    favored: ['future', 'institution', 'sacrifice'],
    opposed: ['short_term_selfishness'],
    intensity: 'strong',
    rule: 'long-term impact and remembered contribution improve morale; disposable short-term gains are disfavored.',
  },
  {
    id: 'power-seeking',
    label: 'Power-Seeking',
    group: 'Ambition & Status',
    favored: ['authority', 'control', 'promotion'],
    opposed: ['subordination'],
    intensity: 'strong',
    rule: 'gaining authority improves morale; losing influence creates stress and autonomous efforts to regain it.',
  },
  {
    id: 'service-minded',
    label: 'Service-Minded',
    group: 'Ambition & Status',
    favored: ['service', 'aid', 'duty'],
    opposed: ['selfish_gain'],
    intensity: 'moderate',
    rule: 'being useful to others improves morale; prestige without usefulness has limited appeal.',
  },
  {
    id: 'achievement-oriented',
    label: 'Achievement-Oriented',
    group: 'Ambition & Status',
    favored: ['goal_completion', 'measurable_progress'],
    opposed: ['unfinished_goal'],
    intensity: 'moderate',
    decay: 'slow',
    rule: 'completing explicit objectives improves morale; abandoned goals linger as stress.',
  },
  {
    id: 'frugal',
    label: 'Frugal',
    group: 'Money & Possessions',
    favored: ['save', 'conserve', 'bargain'],
    opposed: ['waste', 'luxury_spend'],
    intensity: 'moderate',
    rule: 'preserving resources improves morale; unnecessary spending creates friction.',
  },
  {
    id: 'generous',
    label: 'Generous',
    group: 'Money & Possessions',
    favored: ['share_resources', 'aid'],
    opposed: ['hoarding', 'refusal_to_help'],
    intensity: 'moderate',
    rule: 'meaningful giving improves morale; selfish withholding from close others can cost morale.',
  },
  {
    id: 'materialistic',
    label: 'Materialistic',
    group: 'Money & Possessions',
    favored: ['wealth', 'possessions', 'luxury'],
    opposed: ['loss_of_property', 'deprivation'],
    intensity: 'strong',
    rule: 'valuable possessions/status goods improve morale; material loss hurts more.',
  },
  {
    id: 'ascetic',
    label: 'Ascetic',
    group: 'Money & Possessions',
    favored: ['simplicity', 'sacrifice'],
    opposed: ['luxury', 'materialism'],
    intensity: 'moderate',
    rule: 'can tolerate low comfort with reduced morale penalty; excessive luxury has little value.',
  },
  {
    id: 'hoarding',
    label: 'Hoarding',
    group: 'Money & Possessions',
    favored: ['stockpile', 'conserve'],
    opposed: ['discard', 'scarcity'],
    intensity: 'strong',
    rule: 'low reserves/discarding usable goods creates stress; storing surplus is strongly favored.',
  },
  {
    id: 'spendthrift',
    label: 'Spendthrift',
    group: 'Money & Possessions',
    favored: ['spend', 'luxury', 'present'],
    opposed: ['saving', 'austerity'],
    intensity: 'moderate',
    rule: 'spending on comfort/reward improves short-term morale; strict austerity causes friction.',
  },
  {
    id: 'debt-averse',
    label: 'Debt-Averse',
    group: 'Money & Possessions',
    favored: ['save', 'repay_debt'],
    opposed: ['debt', 'borrowing'],
    intensity: 'strong',
    rule: 'debt creates ongoing stress; borrowing is strongly disfavored unless survival-critical.',
  },
  {
    id: 'speculative',
    label: 'Speculative',
    group: 'Money & Possessions',
    favored: ['investment', 'gamble', 'opportunity'],
    opposed: ['static_reserves'],
    intensity: 'moderate',
    rule: 'uncertain investment opportunities gain weight; idle excess resources feel underused.',
  },
  {
    id: 'security-seeking',
    label: 'Security-Seeking',
    group: 'Money & Possessions',
    favored: ['stockpile', 'stable_income', 'reserve'],
    opposed: ['scarcity', 'volatile_plan'],
    intensity: 'strong',
    rule: 'reserves reduce stress; unstable finances/resources increase it.',
  },
  {
    id: 'possession-light',
    label: 'Possession-Light',
    group: 'Money & Possessions',
    favored: ['mobility', 'discard', 'simplicity'],
    opposed: ['hoarding'],
    intensity: 'mild',
    rule: 'abandoning property carries reduced morale cost; inventory attachment is low.',
  },
  {
    id: 'curious',
    label: 'Curious',
    group: 'Curiosity & Knowledge',
    favored: ['explore', 'study', 'novelty'],
    opposed: ['ignored_unknown'],
    intensity: 'moderate',
    rule: 'learning/discovery improves morale; obvious unanswered questions can create mild friction.',
  },
  {
    id: 'inquisitive',
    label: 'Inquisitive',
    group: 'Curiosity & Knowledge',
    favored: ['verify', 'ask', 'investigate'],
    opposed: ['unexamined_claim'],
    intensity: 'moderate',
    rule: 'information-seeking options gain weight; unresolved uncertainty adds stress.',
  },
  {
    id: 'skeptical',
    label: 'Skeptical',
    group: 'Curiosity & Knowledge',
    favored: ['verify', 'evidence'],
    opposed: ['credulity', 'unsupported_claim'],
    intensity: 'strong',
    rule: 'verification reduces stress; accepting unverified claims is disfavored.',
  },
  {
    id: 'credulous',
    label: 'Credulous',
    group: 'Curiosity & Knowledge',
    favored: ['trust', 'story', 'institution_claim'],
    opposed: ['skepticism'],
    intensity: 'moderate',
    rule: 'accepts claims more readily in autonomous decisions; betrayal after trust carries stronger morale hit.',
  },
  {
    id: 'scholarly',
    label: 'Scholarly',
    group: 'Curiosity & Knowledge',
    favored: ['study', 'research', 'teach'],
    opposed: ['anti_intellectual_action'],
    intensity: 'moderate',
    rule: 'structured study improves morale; destroying/ignoring valuable knowledge costs morale.',
  },
  {
    id: 'hands-on-learner',
    label: 'Hands-On Learner',
    group: 'Curiosity & Knowledge',
    favored: ['experiment', 'practice', 'craft'],
    opposed: ['pure_theory'],
    intensity: 'moderate',
    rule: 'practical experimentation gains weight; learning only through abstract study is less satisfying.',
    attribute: 'learning',
    direction: 'low',
  },
  {
    id: 'mystery-seeking',
    label: 'Mystery-Seeking',
    group: 'Curiosity & Knowledge',
    favored: ['mystery', 'explore', 'anomaly'],
    opposed: ['safe_known_path'],
    intensity: 'strong',
    rule: 'unknown/anomalous opportunities gain weight; repeatedly ignoring them can reduce morale.',
  },
  {
    id: 'knowledge-hoarding',
    label: 'Knowledge-Hoarding',
    group: 'Curiosity & Knowledge',
    favored: ['secrecy', 'information_advantage'],
    opposed: ['free_disclosure'],
    intensity: 'moderate',
    rule: 'keeping exclusive useful information feels valuable; sharing it freely is disfavored.',
  },
  {
    id: 'teacherly',
    label: 'Teacherly',
    group: 'Curiosity & Knowledge',
    favored: ['teach', 'mentor', 'explain'],
    opposed: ['withhold_knowledge'],
    intensity: 'moderate',
    rule: 'successful teaching improves morale/relationships; opportunities to mentor gain weight.',
    attribute: 'socialAwareness',
    direction: 'high',
  },
  {
    id: 'anti-intellectual',
    label: 'Anti-Intellectual',
    group: 'Curiosity & Knowledge',
    favored: ['practicality', 'hands_on'],
    opposed: ['theory', 'prolonged_study'],
    intensity: 'moderate',
    rule: 'abstract study without practical payoff creates friction; direct practical solutions gain weight.',
    attribute: 'learning',
    direction: 'low',
  },
  {
    id: 'planner',
    label: 'Planner',
    group: 'Planning & Decision Making',
    favored: ['plan', 'contingency'],
    opposed: ['improvise_without_plan'],
    intensity: 'moderate',
    rule: 'clear plans reduce stress; unplanned commitments add friction.',
    attribute: 'reasoning',
    direction: 'high',
  },
  {
    id: 'improviser',
    label: 'Improviser',
    group: 'Planning & Decision Making',
    favored: ['improvise', 'flexibility'],
    opposed: ['rigid_plan'],
    intensity: 'moderate',
    rule: 'adapting in motion reduces stress; overplanning can feel restrictive.',
  },
  {
    id: 'decisive',
    label: 'Decisive',
    group: 'Planning & Decision Making',
    favored: ['decisive_action', 'commitment'],
    opposed: ['delay', 'reconsider'],
    intensity: 'moderate',
    rule: 'committing reduces stress; prolonged indecision raises it.',
    attribute: 'decisionMaking',
    direction: 'high',
  },
  {
    id: 'indecisive',
    label: 'Indecisive',
    group: 'Planning & Decision Making',
    favored: ['consult', 'delay', 'verify'],
    opposed: ['irreversible_choice'],
    intensity: 'strong',
    rule: 'complex irreversible decisions create stress; autonomous behavior seeks advice or postponement.',
    attribute: 'decisionMaking',
    direction: 'low',
  },
  {
    id: 'analytical',
    label: 'Analytical',
    group: 'Planning & Decision Making',
    favored: ['verify', 'compare', 'plan'],
    opposed: ['gut_only'],
    intensity: 'moderate',
    rule: 'evidence-based comparison lowers stress; acting with poor information is disfavored.',
    attribute: 'reasoning',
    direction: 'high',
  },
  {
    id: 'intuitive',
    label: 'Intuitive',
    group: 'Planning & Decision Making',
    favored: ['improvise', 'decisive_action'],
    opposed: ['overanalysis'],
    intensity: 'moderate',
    rule: 'comfortable acting on incomplete information; excessive analysis causes friction.',
    attribute: 'reasoning',
    direction: 'low',
  },
  {
    id: 'second-guesser',
    label: 'Second-Guesser',
    group: 'Planning & Decision Making',
    favored: ['reconsider', 'verify'],
    opposed: ['irreversible_commitment'],
    intensity: 'strong',
    persistence: true,
    decay: 'slow',
    rule: 'after consequential choices, stress can linger and reconsideration options gain weight.',
    attribute: 'decisionMaking',
    direction: 'low',
  },
  {
    id: 'contingency-minded',
    label: 'Contingency-Minded',
    group: 'Planning & Decision Making',
    favored: ['contingency', 'reserve', 'plan'],
    opposed: ['single_point_failure'],
    intensity: 'strong',
    rule: 'backup plans reduce stress; plans with no fallback are strongly disfavored.',
  },
  {
    id: 'simplifier',
    label: 'Simplifier',
    group: 'Planning & Decision Making',
    favored: ['simple_plan', 'decisive_action'],
    opposed: ['complexity', 'micromanagement'],
    intensity: 'moderate',
    rule: 'fewer clearer options reduce stress; complicated multi-step solutions are disfavored when simpler ones work.',
    attribute: 'reasoning',
    direction: 'low',
  },
  {
    id: 'overthinker',
    label: 'Overthinker',
    group: 'Planning & Decision Making',
    favored: ['study', 'verify', 'consult'],
    opposed: ['time_pressure', 'uncertainty'],
    intensity: 'strong',
    rule: 'uncertainty drives repeated analysis; time pressure increases stress and may delay autonomous commitment.',
    attribute: 'reasoning',
    direction: 'high',
  },
  {
    id: 'calm',
    label: 'Calm',
    group: 'Emotional Regulation',
    favored: ['calm', 'crisis'],
    opposed: ['panic'],
    intensity: 'strong',
    rule: 'stress gains from ordinary pressure are reduced; autonomous option weighting remains steadier.',
    attribute: 'composure',
    direction: 'high',
  },
  {
    id: 'volatile',
    label: 'Volatile',
    group: 'Emotional Regulation',
    favored: ['emotional_expression', 'immediate_reaction'],
    opposed: ['emotional_suppression'],
    intensity: 'strong',
    rule: 'both positive and negative morale swings are amplified; recent events weigh more heavily in decisions.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'stoic',
    label: 'Stoic',
    group: 'Emotional Regulation',
    favored: ['calm', 'restraint'],
    opposed: ['forced_expression'],
    intensity: 'moderate',
    rule: 'outward/emotional reactions are muted; stress/morale deltas from social events are somewhat compressed.',
    attribute: 'composure',
    direction: 'high',
  },
  {
    id: 'expressive',
    label: 'Expressive',
    group: 'Emotional Regulation',
    favored: ['emotional_expression', 'disclosure'],
    opposed: ['suppression'],
    intensity: 'moderate',
    decay: 'slow',
    rule: 'expressing feelings reduces stress; forced suppression lets stress linger.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'resentful',
    label: 'Resentful',
    group: 'Emotional Regulation',
    favored: ['punishment', 'distance'],
    opposed: ['unrepaired_harm'],
    intensity: 'strong',
    persistence: true,
    decay: 'slow',
    rule: 'negative relationship reactions decay slowly unless repaired.',
  },
  {
    id: 'quick-to-recover',
    label: 'Quick to Recover',
    group: 'Emotional Regulation',
    favored: ['recovery', 'reassurance'],
    opposed: ['brooding'],
    intensity: 'strong',
    decay: 'fast',
    rule: 'stress/morale penalties decay faster after setbacks; does not prevent initial reaction.',
    attribute: 'resilience',
    direction: 'high',
  },
  {
    id: 'sensitive',
    label: 'Sensitive',
    group: 'Emotional Regulation',
    favored: ['reassurance', 'warmth'],
    opposed: ['criticism', 'rejection', 'humiliation'],
    intensity: 'strong',
    rule: 'social rejection/criticism has amplified morale/stress impact.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'criticism-resistant',
    label: 'Criticism-Resistant',
    group: 'Emotional Regulation',
    favored: ['directness', 'criticism'],
    opposed: ['humiliation'],
    intensity: 'strong',
    rule: 'insults/criticism have reduced morale impact; reputation harm still matters if other traits care.',
  },
  {
    id: 'brooding',
    label: 'Brooding',
    group: 'Emotional Regulation',
    favored: ['reflection', 'solitude'],
    opposed: ['unresolved_failure'],
    intensity: 'strong',
    persistence: true,
    decay: 'slow',
    rule: 'setbacks and guilt decay slowly; reflection/restitution can accelerate recovery.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'emotionally-compartmentalized',
    label: 'Emotionally Compartmentalized',
    group: 'Emotional Regulation',
    favored: ['crisis', 'duty'],
    opposed: ['post_crisis'],
    intensity: 'strong',
    rule: 'acute emotional penalties are delayed during crisis, then partially applied afterward.',
    attribute: 'discipline',
    direction: 'high',
  },
  {
    id: 'trusting',
    label: 'Trusting',
    group: 'Trust & Suspicion',
    favored: ['trust', 'cooperation'],
    opposed: ['betrayal'],
    intensity: 'moderate',
    rule: 'accepts help/claims more readily; betrayal causes stronger relationship damage.',
  },
  {
    id: 'suspicious',
    label: 'Suspicious',
    group: 'Trust & Suspicion',
    favored: ['verify', 'privacy'],
    opposed: ['rapid_trust'],
    intensity: 'moderate',
    rule: 'unknown motives raise stress; verification and observation are favored.',
  },
  {
    id: 'paranoid',
    label: 'Paranoid',
    group: 'Trust & Suspicion',
    favored: ['suspicion', 'surveillance'],
    opposed: ['uncertainty', 'hidden_agenda'],
    intensity: 'strong',
    rule: 'perceived hidden threats strongly alter autonomous decisions; false-positive suspicion is intentionally possible.',
  },
  {
    id: 'open-minded',
    label: 'Open-Minded',
    group: 'Trust & Suspicion',
    favored: ['novelty', 'trust', 'new_people'],
    opposed: ['prejudice', 'rigid_assumption'],
    intensity: 'moderate',
    rule: 'unfamiliar people/ideas receive fairer initial weighting; unconventional options gain consideration.',
  },
  {
    id: 'cynical',
    label: 'Cynical',
    group: 'Trust & Suspicion',
    favored: ['verify', 'self_interest'],
    opposed: ['idealistic_claim'],
    intensity: 'moderate',
    rule: 'assumes selfish motives; hard bargains/defensive choices gain weight, disappointment from betrayal is reduced.',
  },
  {
    id: 'benefit-of-the-doubt',
    label: 'Benefit-of-the-Doubt',
    group: 'Trust & Suspicion',
    favored: ['trust', 'second_chance'],
    opposed: ['premature_punishment'],
    intensity: 'moderate',
    rule: 'ambiguous mistakes receive softer relationship penalties; reconciliation is favored.',
  },
  {
    id: 'evidence-driven-trust',
    label: 'Evidence-Driven Trust',
    group: 'Trust & Suspicion',
    favored: ['verify', 'trust_after_evidence'],
    opposed: ['blind_trust'],
    intensity: 'strong',
    rule: 'trust changes mostly through observed behavior; relationship gains/losses are slower but more stable.',
    attribute: 'evaluation',
    direction: 'high',
  },
  {
    id: 'clan-minded',
    label: 'Clan-Minded',
    group: 'Trust & Suspicion',
    favored: ['in_group', 'family', 'crew'],
    opposed: ['outsider_priority'],
    intensity: 'strong',
    rule: 'favors known in-group over strangers when resources conflict; outsider trust builds slowly.',
  },
  {
    id: 'institution-trusting',
    label: 'Institution-Trusting',
    group: 'Trust & Suspicion',
    favored: ['institution', 'procedure', 'authority'],
    opposed: ['unofficial_channel'],
    intensity: 'moderate',
    rule: 'official assurances reduce stress; official options gain autonomous weight.',
  },
  {
    id: 'institution-skeptical',
    label: 'Institution-Skeptical',
    group: 'Trust & Suspicion',
    favored: ['independent_verification', 'autonomy'],
    opposed: ['institution', 'authority_claim'],
    intensity: 'moderate',
    rule: 'formal authority claims are discounted; independent/underground verification gains weight.',
  },
  {
    id: 'responsible',
    label: 'Responsible',
    group: 'Responsibility & Guilt',
    favored: ['duty', 'responsibility', 'promise'],
    opposed: ['neglect'],
    intensity: 'moderate',
    rule: 'fulfilling obligations improves morale; avoidable neglect costs morale.',
  },
  {
    id: 'duty-bound',
    label: 'Duty-Bound',
    group: 'Responsibility & Guilt',
    favored: ['duty', 'responsibility'],
    opposed: ['abandon_duty'],
    intensity: 'extreme',
    rule: 'accepted critical duties dominate autonomous priorities; extreme abandonment can trigger rare refusal.',
  },
  {
    id: 'guilt-prone',
    label: 'Guilt-Prone',
    group: 'Responsibility & Guilt',
    favored: ['accountability', 'restitution'],
    opposed: ['caused_harm', 'failure'],
    intensity: 'strong',
    decay: 'slow',
    rule: 'causing preventable harm creates amplified lingering stress; restitution/confession helps recovery.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'blame-shifting',
    label: 'Blame-Shifting',
    group: 'Responsibility & Guilt',
    favored: ['blame_other', 'self_protection'],
    opposed: ['accountability'],
    intensity: 'moderate',
    rule: 'owning fault is emotionally costly; autonomous dialogue tends to externalize blame.',
  },
  {
    id: 'accountable',
    label: 'Accountable',
    group: 'Responsibility & Guilt',
    favored: ['accountability', 'restitution'],
    opposed: ['coverup', 'blame_shift'],
    intensity: 'moderate',
    rule: 'admitting mistakes and repairing harm improves morale; coverups cost morale.',
  },
  {
    id: 'martyring',
    label: 'Martyring',
    group: 'Responsibility & Guilt',
    favored: ['sacrifice', 'duty'],
    opposed: ['self_preservation'],
    intensity: 'strong',
    rule: 'taking burdens for others improves morale/meaning; can overvalue self-sacrifice in autonomous choices.',
  },
  {
    id: 'boundary-conscious',
    label: 'Boundary-Conscious',
    group: 'Responsibility & Guilt',
    favored: ['autonomy', 'fair_obligation'],
    opposed: ['martyrdom', 'unfair_burden'],
    intensity: 'moderate',
    rule: 'refuses unnecessary responsibility; accepting others\' avoidable burdens creates stress.',
  },
  {
    id: 'promise-keeping',
    label: 'Promise-Keeping',
    group: 'Responsibility & Guilt',
    favored: ['promise', 'duty'],
    opposed: ['betray_promise'],
    intensity: 'extreme',
    rule: 'keeping active commitments strongly affects morale; casual betrayal can trigger rare refusal.',
  },
  {
    id: 'outcome-focused',
    label: 'Outcome-Focused',
    group: 'Responsibility & Guilt',
    favored: ['outcome', 'efficiency'],
    opposed: ['procedural_purity'],
    intensity: 'moderate',
    rule: 'judges responsibility by results; breaking process/promise has reduced cost when outcome clearly improves.',
  },
  {
    id: 'protective-of-dependents',
    label: 'Protective of Dependents',
    group: 'Responsibility & Guilt',
    favored: ['protect_dependents', 'rescue'],
    opposed: ['abandon_dependents'],
    intensity: 'extreme',
    rule: 'dependents\' safety dominates priorities; knowingly abandoning reachable dependents can trigger refusal.',
  },
  {
    id: 'principled',
    label: 'Principled',
    group: 'Ideals & Principles',
    favored: ['principle', 'consistency'],
    opposed: ['hypocrisy', 'compromise_for_convenience'],
    intensity: 'strong',
    rule: 'acting against declared values costs morale; consistency improves morale.',
  },
  {
    id: 'pragmatic',
    label: 'Pragmatic',
    group: 'Ideals & Principles',
    favored: ['outcome', 'compromise'],
    opposed: ['ideological_purity'],
    intensity: 'moderate',
    rule: 'compromise carries little cost when useful; symbolic purity is disfavored if outcomes suffer.',
  },
  {
    id: 'idealistic',
    label: 'Idealistic',
    group: 'Ideals & Principles',
    favored: ['principle', 'reform', 'hope'],
    opposed: ['cynical_compromise'],
    intensity: 'strong',
    rule: 'pursuing a better outcome improves morale; repeated compromise of ideals hurts.',
  },
  {
    id: 'fatalistic',
    label: 'Fatalistic',
    group: 'Ideals & Principles',
    favored: ['acceptance', 'present'],
    opposed: ['control_the_uncontrollable'],
    intensity: 'moderate',
    rule: 'uncontrollable losses create less stress; long-shot attempts to control fate are less attractive.',
  },
  {
    id: 'humanistic',
    label: 'Humanistic',
    group: 'Ideals & Principles',
    favored: ['compassion', 'dignity', 'protect_others'],
    opposed: ['dehumanization', 'cruelty'],
    intensity: 'strong',
    rule: 'preserving dignity/life improves morale; cruelty/dehumanization is strongly opposed.',
  },
  {
    id: 'traditionalist',
    label: 'Traditionalist',
    group: 'Ideals & Principles',
    favored: ['tradition', 'institution', 'continuity'],
    opposed: ['reform', 'novelty'],
    intensity: 'moderate',
    decay: 'fast',
    rule: 'established customs stabilize morale; abrupt unnecessary change creates friction.',
  },
  {
    id: 'iconoclastic',
    label: 'Iconoclastic',
    group: 'Ideals & Principles',
    favored: ['reform', 'novelty', 'challenge_norm'],
    opposed: ['tradition_for_its_own_sake'],
    intensity: 'moderate',
    rule: 'challenging stale norms improves morale; deference to tradition without reason is disfavored.',
  },
  {
    id: 'pacifistic',
    label: 'Pacifistic',
    group: 'Ideals & Principles',
    favored: ['nonviolence', 'deescalation'],
    opposed: ['violence', 'execution', 'torture'],
    intensity: 'extreme',
    rule: 'violence creates strong stress/morale cost; gratuitous lethal violence may trigger rare refusal.',
  },
  {
    id: 'retributive',
    label: 'Retributive',
    group: 'Ideals & Principles',
    favored: ['punishment', 'justice'],
    opposed: ['mercy_without_accountability'],
    intensity: 'strong',
    decay: 'fast',
    rule: 'seeing wrongdoing punished improves morale; unpunished serious harm creates resentment.',
  },
  {
    id: 'consequentialist',
    label: 'Consequentialist',
    group: 'Ideals & Principles',
    favored: ['outcome', 'save_many', 'efficiency'],
    opposed: ['rule_for_rule_sake'],
    intensity: 'strong',
    rule: 'autonomous decisions heavily weight expected consequences; methods matter less unless another trait says otherwise.',
  },
  {
    id: 'proud-craftsperson',
    label: 'Proud Craftsperson',
    group: 'Work & Competence',
    favored: ['craft_quality', 'repair', 'build'],
    opposed: ['sloppy_result'],
    intensity: 'moderate',
    rule: 'high-quality skilled work improves morale; shoddy work under their name hurts.',
    attribute: 'discipline',
    direction: 'high',
  },
  {
    id: 'efficiency-minded',
    label: 'Efficiency-Minded',
    group: 'Work & Competence',
    favored: ['speed', 'conserve', 'workflow'],
    opposed: ['waste', 'redundant_work'],
    intensity: 'moderate',
    rule: 'efficient solutions improve morale; avoidable wasted time/resources create friction.',
    attribute: 'reasoning',
    direction: 'high',
  },
  {
    id: 'thorough',
    label: 'Thorough',
    group: 'Work & Competence',
    favored: ['verify', 'craft_quality', 'inspection'],
    opposed: ['rushed_action'],
    intensity: 'moderate',
    rule: 'complete work reduces stress; skipping checks is disfavored.',
  },
  {
    id: 'sloppy',
    label: 'Sloppy',
    group: 'Work & Competence',
    favored: ['speed', 'good_enough'],
    opposed: ['thoroughness', 'perfectionism'],
    intensity: 'mild',
    rule: 'reduced emotional cost for imperfect work; fast approximate solutions gain weight.',
    attribute: 'discipline',
    direction: 'low',
  },
  {
    id: 'mentor',
    label: 'Mentor',
    group: 'Work & Competence',
    favored: ['teach', 'delegate', 'develop_other'],
    opposed: ['withhold_knowledge'],
    intensity: 'moderate',
    rule: 'developing less-skilled crew improves morale/relationships.',
    attribute: 'leadership',
    direction: 'high',
  },
  {
    id: 'self-reliant',
    label: 'Self-Reliant',
    group: 'Work & Competence',
    favored: ['self_reliance', 'autonomy'],
    opposed: ['help_seek'],
    intensity: 'moderate',
    rule: 'solving problems personally improves morale; asking for help too early creates friction.',
  },
  {
    id: 'help-seeking',
    label: 'Help-Seeking',
    group: 'Work & Competence',
    favored: ['help_seek', 'specialization', 'cooperation'],
    opposed: ['stubborn_self_reliance'],
    intensity: 'moderate',
    rule: 'involving qualified help reduces stress; lone attempts outside competence are disfavored.',
  },
  {
    id: 'competence-insecure',
    label: 'Competence-Insecure',
    group: 'Work & Competence',
    favored: ['verify', 'low_visibility_task'],
    opposed: ['failure', 'public_evaluation'],
    intensity: 'strong',
    rule: 'failure/public incompetence creates extra stress; may avoid high-visibility tasks unless supported.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'prideful',
    label: 'Prideful',
    group: 'Work & Competence',
    favored: ['self_reliance', 'recognition'],
    opposed: ['admit_inability', 'humiliation'],
    intensity: 'strong',
    rule: 'admitting inability creates stress; may over-attempt tasks rather than ask for help.',
  },
  {
    id: 'professional',
    label: 'Professional',
    group: 'Work & Competence',
    favored: ['duty', 'procedure', 'craft_quality'],
    opposed: ['sloppiness', 'role_violation'],
    intensity: 'moderate',
    rule: 'competent role-appropriate conduct improves morale; unprofessional behavior creates friction.',
  },
  {
    id: 'adventurous',
    label: 'Adventurous',
    group: 'Exploration & Novelty',
    favored: ['explore', 'novelty', 'physical_risk'],
    opposed: ['routine', 'safe_known_path'],
    intensity: 'moderate',
    rule: 'new places/experiences improve morale; exploration options gain weight.',
  },
  {
    id: 'homebody',
    label: 'Homebody',
    group: 'Exploration & Novelty',
    favored: ['home', 'comfort', 'routine'],
    opposed: ['travel', 'prolonged_absence'],
    intensity: 'moderate',
    rule: 'home/familiar surroundings improve morale; prolonged travel slowly lowers it.',
  },
  {
    id: 'wanderlust',
    label: 'Wanderlust',
    group: 'Exploration & Novelty',
    favored: ['travel', 'explore', 'novelty'],
    opposed: ['stagnation', 'long_stay'],
    intensity: 'strong',
    rule: 'prolonged stay in one place lowers morale; travel opportunities gain weight.',
  },
  {
    id: 'routine-seeking',
    label: 'Routine-Seeking',
    group: 'Exploration & Novelty',
    favored: ['routine', 'familiarity'],
    opposed: ['novelty', 'disruption'],
    intensity: 'moderate',
    rule: 'known environments reduce stress; unfamiliar settings increase it.',
  },
  {
    id: 'frontier-minded',
    label: 'Frontier-Minded',
    group: 'Exploration & Novelty',
    favored: ['explore', 'first_contact', 'unknown_system'],
    opposed: ['safe_known_path'],
    intensity: 'strong',
    rule: 'being first into unknown places improves morale; frontier choices gain large weight.',
  },
  {
    id: 'comfort-seeking',
    label: 'Comfort-Seeking',
    group: 'Exploration & Novelty',
    favored: ['comfort', 'safe_lodging', 'civilization'],
    opposed: ['hardship', 'deprivation'],
    intensity: 'moderate',
    rule: 'comfort strongly aids morale recovery; unnecessary hardship is disfavored.',
  },
  {
    id: 'collector',
    label: 'Collector',
    group: 'Exploration & Novelty',
    favored: ['rare_item', 'loot', 'discovery'],
    opposed: ['discard_unique_item'],
    intensity: 'moderate',
    rule: 'acquiring unusual objects improves morale; abandoning rare finds causes friction.',
  },
  {
    id: 'naturalist',
    label: 'Naturalist',
    group: 'Exploration & Novelty',
    favored: ['nature', 'ecology', 'protect_environment'],
    opposed: ['ecological_harm'],
    intensity: 'moderate',
    rule: 'intact ecosystems/discovery improve morale; needless ecological destruction costs morale.',
  },
  {
    id: 'ruin-obsessed',
    label: 'Ruin-Obsessed',
    group: 'Exploration & Novelty',
    favored: ['ruins', 'mystery', 'archaeology'],
    opposed: ['ignore_ruin'],
    intensity: 'strong',
    rule: 'ancient/abandoned sites strongly pull autonomous exploration choices.',
  },
  {
    id: 'cautious-explorer',
    label: 'Cautious Explorer',
    group: 'Exploration & Novelty',
    favored: ['explore', 'plan', 'verify'],
    opposed: ['blind_exploration'],
    intensity: 'moderate',
    rule: 'enjoys discovery only after preparation; scouting strongly raises willingness to explore.',
  },
  {
    id: 'aggressive',
    label: 'Aggressive',
    group: 'Violence & Combat Attitude',
    favored: ['aggression', 'combat', 'intimidation'],
    opposed: ['retreat', 'deescalation'],
    intensity: 'strong',
    rule: 'initiating decisive force gains weight; backing down from challenge can create frustration.',
  },
  {
    id: 'defensive',
    label: 'Defensive',
    group: 'Violence & Combat Attitude',
    favored: ['defense', 'protect_others', 'retreat'],
    opposed: ['unprovoked_aggression'],
    intensity: 'strong',
    context: 'protecting',
    rule: 'violence is favored when protecting/answering attack; initiating aggression is disfavored.',
  },
  {
    id: 'combat-confident',
    label: 'Combat-Confident',
    group: 'Violence & Combat Attitude',
    favored: ['combat', 'calm'],
    opposed: ['panic', 'retreat'],
    intensity: 'moderate',
    context: 'crisis',
    rule: 'combat produces less stress; tactical options remain more stable under fire.',
  },
  {
    id: 'combat-averse',
    label: 'Combat-Averse',
    group: 'Violence & Combat Attitude',
    favored: ['nonviolence', 'retreat'],
    opposed: ['combat', 'violence'],
    intensity: 'strong',
    rule: 'combat adds stress even when justified; escape/deescalation options gain weight.',
  },
  {
    id: 'predatory',
    label: 'Predatory',
    group: 'Violence & Combat Attitude',
    favored: ['ambush', 'exploit_weakness', 'aggression'],
    opposed: ['fair_fight'],
    intensity: 'strong',
    rule: 'autonomous combat favors asymmetric advantage; mercy toward weak foes is less attractive.',
  },
  {
    id: 'protective-fighter',
    label: 'Protective Fighter',
    group: 'Violence & Combat Attitude',
    favored: ['protect_others', 'combat', 'rescue'],
    opposed: ['abandon_ally'],
    intensity: 'strong',
    context: 'protecting',
    rule: 'combat stress is reduced when defending others; protection options gain large weight.',
  },
  {
    id: 'mercenary',
    label: 'Mercenary',
    group: 'Violence & Combat Attitude',
    favored: ['payment', 'contract', 'combat'],
    opposed: ['unpaid_sacrifice'],
    intensity: 'moderate',
    rule: 'violence is acceptable when payoff/contract is clear; unpaid risk is disfavored.',
  },
  {
    id: 'honor-bound-fighter',
    label: 'Honor-Bound Fighter',
    group: 'Violence & Combat Attitude',
    favored: ['fair_fight', 'defense', 'challenge'],
    opposed: ['torture', 'treachery', 'helpless_target'],
    intensity: 'strong',
    rule: 'combat is acceptable under a code; dirty violence creates morale loss.',
  },
  {
    id: 'dirty-fighter',
    label: 'Dirty Fighter',
    group: 'Violence & Combat Attitude',
    favored: ['ambush', 'deception', 'combat'],
    opposed: ['fairness_constraint'],
    intensity: 'moderate',
    rule: 'little internal cost for unfair tactics; autonomous combat exploits available advantages.',
  },
  {
    id: 'weapon-shy',
    label: 'Weapon-Shy',
    group: 'Violence & Combat Attitude',
    favored: ['nonviolence', 'unarmed_option'],
    opposed: ['weapon_use', 'firearms'],
    intensity: 'strong',
    rule: 'personally using weapons adds stress; unarmed/avoidance alternatives gain weight.',
  },
  {
    id: 'optimistic',
    label: 'Optimistic',
    group: 'Hope & Outlook',
    favored: ['hope', 'future', 'retry'],
    opposed: ['doom', 'surrender'],
    intensity: 'moderate',
    decay: 'fast',
    rule: 'setbacks decay faster; signs of improvement give larger morale gains.',
  },
  {
    id: 'pessimistic',
    label: 'Pessimistic',
    group: 'Hope & Outlook',
    favored: ['conserve', 'contingency'],
    opposed: ['optimistic_gamble'],
    intensity: 'moderate',
    rule: 'bad forecasts create less surprise but positive expectations are discounted; safer fallbacks gain weight.',
  },
  {
    id: 'hopeful',
    label: 'Hopeful',
    group: 'Hope & Outlook',
    favored: ['future', 'rebuild', 'rescue'],
    opposed: ['give_up'],
    intensity: 'strong',
    rule: 'evidence of future improvement strongly raises morale; rebuilding options gain weight.',
  },
  {
    id: 'doomer',
    label: 'Doomer',
    group: 'Hope & Outlook',
    favored: ['retreat', 'conserve'],
    opposed: ['hopeful_longshot'],
    intensity: 'strong',
    rule: 'worsening forecasts accelerate morale loss/withdrawal; surrender/escape options appear more attractive.',
  },
  {
    id: 'realistic',
    label: 'Realistic',
    group: 'Hope & Outlook',
    favored: ['verify', 'evidence', 'plan'],
    opposed: ['wishful_thinking', 'catastrophizing'],
    intensity: 'moderate',
    rule: 'morale follows evidence more than tone; balanced expected-value options gain weight.',
    attribute: 'evaluation',
    direction: 'high',
  },
  {
    id: 'romantic',
    label: 'Romantic',
    group: 'Hope & Outlook',
    favored: ['love', 'symbolism', 'sacrifice', 'beauty'],
    opposed: ['cold_practicality'],
    intensity: 'moderate',
    rule: 'meaningful gestures/ideals improve morale; purely transactional choices can feel empty.',
  },
  {
    id: 'world-weary',
    label: 'World-Weary',
    group: 'Hope & Outlook',
    favored: ['practicality', 'calm'],
    opposed: ['shock', 'novelty'],
    intensity: 'moderate',
    rule: 'surprises and bad news have muted emotional effect; enthusiasm gains are also somewhat reduced.',
  },
  {
    id: 'future-oriented',
    label: 'Future-Oriented',
    group: 'Hope & Outlook',
    favored: ['future', 'invest', 'plan'],
    opposed: ['present_consumption'],
    intensity: 'moderate',
    rule: 'long-term investment improves morale; sacrificing future for trivial present gain is disfavored.',
  },
  {
    id: 'present-oriented',
    label: 'Present-Oriented',
    group: 'Hope & Outlook',
    favored: ['present', 'comfort', 'immediate_reward'],
    opposed: ['deferred_reward'],
    intensity: 'moderate',
    rule: 'immediate quality-of-life gains matter more; long deferred sacrifices carry extra friction.',
  },
  {
    id: 'nostalgic',
    label: 'Nostalgic',
    group: 'Hope & Outlook',
    favored: ['home', 'memory', 'tradition'],
    opposed: ['loss_of_memento', 'sever_past'],
    intensity: 'moderate',
    rule: 'reminders of home/past bonds restore morale; abandoning meaningful mementos/places hurts.',
  },
  {
    id: 'cooperative',
    label: 'Cooperative',
    group: 'Independence & Cooperation',
    favored: ['cooperation', 'share_resources', 'team'],
    opposed: ['solo', 'selfish_gain'],
    intensity: 'moderate',
    rule: 'shared effort improves morale; teamwork options gain weight.',
  },
  {
    id: 'solo-minded',
    label: 'Solo-Minded',
    group: 'Independence & Cooperation',
    favored: ['solo', 'autonomy', 'self_reliance'],
    opposed: ['forced_teamwork'],
    intensity: 'moderate',
    rule: 'solo work restores autonomy; unnecessary group dependence creates friction.',
  },
  {
    id: 'consensus-seeking',
    label: 'Consensus-Seeking',
    group: 'Independence & Cooperation',
    favored: ['consensus', 'consultation'],
    opposed: ['unilateral_command'],
    intensity: 'strong',
    rule: 'major group decisions without consultation create stress; ask-the-crew options gain weight.',
  },
  {
    id: 'self-directed',
    label: 'Self-Directed',
    group: 'Independence & Cooperation',
    favored: ['autonomy', 'decisive_action'],
    opposed: ['micromanagement', 'second_guessing'],
    intensity: 'strong',
    rule: 'being second-guessed adds stress; self-directed choices gain weight.',
    attribute: 'discipline',
    direction: 'high',
  },
  {
    id: 'mutual-aid-oriented',
    label: 'Mutual-Aid Oriented',
    group: 'Independence & Cooperation',
    favored: ['share_resources', 'cooperation', 'reciprocity'],
    opposed: ['exploitation', 'free_riding'],
    intensity: 'strong',
    rule: 'reciprocal help improves morale/relationships; exploitative imbalance creates resentment.',
  },
  {
    id: 'transactional',
    label: 'Transactional',
    group: 'Independence & Cooperation',
    favored: ['contract', 'payment', 'clear_exchange'],
    opposed: ['vague_obligation', 'charity'],
    intensity: 'moderate',
    rule: 'explicit exchanges reduce stress; ambiguous favors/obligations are disfavored.',
  },
  {
    id: 'dependent',
    label: 'Dependent',
    group: 'Independence & Cooperation',
    favored: ['group', 'reassurance', 'trusted_person'],
    opposed: ['isolation', 'separation'],
    intensity: 'strong',
    rule: 'separation from trusted people raises stress; group-preserving choices gain weight.',
    attribute: 'leadership',
    direction: 'low',
  },
  {
    id: 'autonomous',
    label: 'Autonomous',
    group: 'Independence & Cooperation',
    favored: ['autonomy', 'solo'],
    opposed: ['dependency', 'control'],
    intensity: 'strong',
    rule: 'functions well alone with reduced isolation penalty; control/dependence is strongly disfavored.',
  },
  {
    id: 'team-builder',
    label: 'Team-Builder',
    group: 'Independence & Cooperation',
    favored: ['cooperation', 'morale_support', 'mentor'],
    opposed: ['crew_fragmentation'],
    intensity: 'strong',
    rule: 'actions improving group cohesion increase morale; conflict-smoothing options gain weight.',
  },
  {
    id: 'factional',
    label: 'Factional',
    group: 'Independence & Cooperation',
    favored: ['in_group', 'clan'],
    opposed: ['out_group_priority'],
    intensity: 'strong',
    rule: 'favors chosen subgroup within larger crew; inter-faction disputes can create relationship bias.',
  },
  {
    id: 'unhurried',
    label: 'Unhurried',
    group: 'Patience & Time',
    favored: ['patience', 'wait'],
    opposed: ['urgency_without_need'],
    intensity: 'moderate',
    rule: 'waiting carries little stress; can tolerate slow plans for better outcomes.',
  },
  {
    id: 'impatient',
    label: 'Impatient',
    group: 'Patience & Time',
    favored: ['urgency', 'decisive_action'],
    opposed: ['delay', 'waiting'],
    intensity: 'strong',
    rule: 'delays add stress; immediate-action options gain weight.',
  },
  {
    id: 'deadline-driven',
    label: 'Deadline-Driven',
    group: 'Patience & Time',
    favored: ['deadline', 'urgency', 'goal_completion'],
    opposed: ['open_ended_task'],
    intensity: 'moderate',
    rule: 'clear deadlines focus behavior and can reduce stress; vague tasks create drift.',
    attribute: 'discipline',
    direction: 'high',
  },
  {
    id: 'leisurely',
    label: 'Leisurely',
    group: 'Patience & Time',
    favored: ['patience', 'comfort'],
    opposed: ['artificial_urgency'],
    intensity: 'mild',
    rule: 'slow pacing is preferred; imposed urgency creates friction unless threat is real.',
  },
  {
    id: 'time-anxious',
    label: 'Time-Anxious',
    group: 'Patience & Time',
    favored: ['urgency', 'plan'],
    opposed: ['countdown', 'delay'],
    intensity: 'strong',
    rule: 'visible time pressure amplifies stress and may overweight speed.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'long-horizon-thinker',
    label: 'Long-Horizon Thinker',
    group: 'Patience & Time',
    favored: ['future', 'invest', 'patience'],
    opposed: ['short_term_gain'],
    intensity: 'strong',
    rule: 'delayed high-value outcomes gain weight; immediate gains are discounted.',
  },
  {
    id: 'short-horizon-thinker',
    label: 'Short-Horizon Thinker',
    group: 'Patience & Time',
    favored: ['present', 'immediate_reward'],
    opposed: ['long_term_sacrifice'],
    intensity: 'strong',
    rule: 'immediate survival/reward dominates; distant benefits are discounted.',
  },
  {
    id: 'waiting-averse',
    label: 'Waiting-Averse',
    group: 'Patience & Time',
    favored: ['work', 'study', 'decisive_action'],
    opposed: ['idle_time', 'waiting'],
    intensity: 'moderate',
    rule: 'idle time lowers morale; seeks productive action during delays.',
  },
  {
    id: 'deliberate',
    label: 'Deliberate',
    group: 'Patience & Time',
    favored: ['consult', 'verify', 'plan'],
    opposed: ['snap_decision'],
    intensity: 'moderate',
    decay: 'fast',
    rule: 'time to consider reduces stress; rushed major decisions are disfavored.',
  },
  {
    id: 'snap-decider',
    label: 'Snap-Decider',
    group: 'Patience & Time',
    favored: ['decisive_action', 'intuitive'],
    opposed: ['deliberation', 'reconsider'],
    intensity: 'moderate',
    rule: 'quick commitment lowers stress; extended analysis creates friction.',
  },
  {
    id: 'proud',
    label: 'Proud',
    group: 'Pride & Shame',
    favored: ['recognition', 'autonomy', 'achievement'],
    opposed: ['humiliation', 'public_failure'],
    intensity: 'strong',
    rule: 'humiliation causes major morale loss; save-face options gain weight.',
  },
  {
    id: 'humble',
    label: 'Humble',
    group: 'Pride & Shame',
    favored: ['service', 'accountability'],
    opposed: ['boasting', 'status'],
    intensity: 'mild',
    rule: 'recognition/status have reduced impact; apologizing/admitting error has low cost.',
    attribute: 'charisma',
    direction: 'low',
  },
  {
    id: 'shame-prone',
    label: 'Shame-Prone',
    group: 'Pride & Shame',
    favored: ['privacy', 'restitution'],
    opposed: ['public_failure', 'exposure'],
    intensity: 'strong',
    decay: 'slow',
    rule: 'public failure/exposure creates lingering stress; redemption options gain weight.',
    attribute: 'composure',
    direction: 'low',
  },
  {
    id: 'thick-skinned',
    label: 'Thick-Skinned',
    group: 'Pride & Shame',
    favored: ['directness', 'criticism'],
    opposed: ['insult', 'embarrassment'],
    intensity: 'strong',
    rule: 'social criticism/insult has reduced emotional effect.',
    attribute: 'resilience',
    direction: 'high',
  },
  {
    id: 'boastful',
    label: 'Boastful',
    group: 'Pride & Shame',
    favored: ['recognition', 'public_success'],
    opposed: ['ignored_success'],
    intensity: 'moderate',
    rule: 'displaying success improves morale; bragging options gain weight.',
  },
  {
    id: 'modest',
    label: 'Modest',
    group: 'Pride & Shame',
    favored: ['service', 'privacy'],
    opposed: ['boasting', 'spotlight'],
    intensity: 'mild',
    rule: 'excessive recognition creates discomfort; deflect-credit options gain weight.',
    attribute: 'charisma',
    direction: 'low',
  },
  {
    id: 'honor-conscious',
    label: 'Honor-Conscious',
    group: 'Pride & Shame',
    favored: ['reputation', 'promise', 'fairness'],
    opposed: ['dishonor', 'betrayal'],
    intensity: 'strong',
    rule: 'reputation for integrity strongly affects morale; honor-restoring choices gain weight.',
  },
  {
    id: 'reputation-indifferent',
    label: 'Reputation-Indifferent',
    group: 'Pride & Shame',
    favored: ['autonomy', 'practicality'],
    opposed: ['public_opinion'],
    intensity: 'strong',
    rule: 'public approval/disapproval has little emotional effect unless another trait cares.',
  },
  {
    id: 'face-saving',
    label: 'Face-Saving',
    group: 'Pride & Shame',
    favored: ['privacy', 'compromise_in_private'],
    opposed: ['public_concession', 'humiliation'],
    intensity: 'moderate',
    rule: 'avoids public loss of status; private compromise is much easier.',
  },
  {
    id: 'self-deprecating',
    label: 'Self-Deprecating',
    group: 'Pride & Shame',
    favored: ['humor', 'accountability'],
    opposed: ['shame_spiral'],
    intensity: 'mild',
    rule: 'can convert minor embarrassment into humor, reducing stress and social tension.',
    attribute: 'charisma',
    direction: 'low',
  },
  {
    id: 'dry-humored',
    label: 'Dry-Humored',
    group: 'Humor & Demeanor',
    favored: ['humor', 'calm'],
    opposed: ['forced_cheer'],
    intensity: 'mild',
    rule: 'dry humor during tension reduces stress slightly; understated joke options appear.',
  },
  {
    id: 'playful',
    label: 'Playful',
    group: 'Humor & Demeanor',
    favored: ['humor', 'socialize', 'novelty'],
    opposed: ['rigid_seriousness'],
    intensity: 'moderate',
    rule: 'playful interaction improves morale; prolonged severe atmosphere lowers it.',
    attribute: 'charisma',
    direction: 'high',
  },
  {
    id: 'serious',
    label: 'Serious',
    group: 'Humor & Demeanor',
    favored: ['seriousness', 'duty'],
    opposed: ['joking_during_crisis'],
    intensity: 'mild',
    rule: 'focused sober conduct improves comfort; frivolity during important moments causes friction.',
  },
  {
    id: 'sarcastic',
    label: 'Sarcastic',
    group: 'Humor & Demeanor',
    favored: ['humor', 'confrontation'],
    opposed: ['earnest_vulnerability'],
    intensity: 'mild',
    rule: 'sarcasm can reduce own stress but may create relationship friction with sensitive characters.',
  },
  {
    id: 'earnest',
    label: 'Earnest',
    group: 'Humor & Demeanor',
    favored: ['honesty', 'emotional_expression'],
    opposed: ['cynicism', 'manipulation'],
    intensity: 'moderate',
    rule: 'sincere communication improves morale/relationships; manipulative social games are disfavored.',
  },
  {
    id: 'morbidly-funny',
    label: 'Morbidly Funny',
    group: 'Humor & Demeanor',
    favored: ['humor', 'crisis'],
    opposed: ['forced_solemnity'],
    intensity: 'moderate',
    rule: 'dark humor during danger/grief can reduce stress; can offend traits that dislike it.',
  },
  {
    id: 'cheerful',
    label: 'Cheerful',
    group: 'Humor & Demeanor',
    favored: ['hope', 'socialize', 'humor'],
    opposed: ['prolonged_gloom'],
    intensity: 'moderate',
    rule: 'positive social events produce larger morale gains; can help relationship recovery.',
    attribute: 'charisma',
    direction: 'high',
  },
  {
    id: 'grim',
    label: 'Grim',
    group: 'Humor & Demeanor',
    favored: ['seriousness', 'duty'],
    opposed: ['forced_optimism'],
    intensity: 'mild',
    rule: 'low need for upbeat atmosphere; bad news causes less tonal disruption but joy gains are muted.',
  },
  {
    id: 'deadpan',
    label: 'Deadpan',
    group: 'Humor & Demeanor',
    favored: ['calm', 'humor'],
    opposed: ['emotional_display'],
    intensity: 'mild',
    rule: 'outward response remains restrained; dialogue tone changes more than core morale.',
  },
  {
    id: 'theatrical',
    label: 'Theatrical',
    group: 'Humor & Demeanor',
    favored: ['recognition', 'emotional_expression', 'humor'],
    opposed: ['ignored_presence'],
    intensity: 'moderate',
    rule: 'dramatic expression/attention improves morale; performative options gain weight.',
    attribute: 'charisma',
    direction: 'high',
  },
];
