/**
 * PLANETS — pure authored data, no logic.
 *
 * One primary biome and zero to three environmental modifiers, straight from
 * the planet generation library. A hundred biomes across three hundred
 * modifiers is enough variety that the same biome plays differently every
 * seed without anyone hand-authoring a thousand worlds.
 *
 * Modifiers are description first. Where one of them clearly implies a
 * mechanical consequence, that consequence lives in `engine/planet.ts` as an
 * authored effect keyed by id — never guessed from the words here.
 */

export interface BiomeEntry {
  id: string;
  /** Entry number in the library, so identity survives a rename. */
  n: number;
  name: string;
  description: string;
}

export type ModifierCategory =
  | 'Atmosphere & Air'
  | 'Weather & Storms'
  | 'Temperature & Climate'
  | 'Gravity & Physical Conditions'
  | 'Geology & Seismic Activity'
  | 'Magnetic, Electrical & Radiation'
  | 'Water & Hydrology'
  | 'Ecology & Biosphere'
  | 'Flora & Vegetation'
  | 'Fauna & Animal Hazards'
  | 'Biological & Health Hazards'
  | 'Resources & Geochemical Wealth'
  | 'Terrain & Surface Navigation'
  | 'Light, Orbit & Sky'
  | 'Unusual Natural Phenomena';

export interface PlanetModifierEntry {
  id: string;
  n: number;
  name: string;
  category: ModifierCategory;
  description: string;
}

/** Part I — 100 primary biomes. */
export const BIOMES: BiomeEntry[] = [
  { id: 'temperate-continental', n: 1, name: 'Temperate Continental', description: 'Mixed forests, plains, rivers, lakes, and mountain chains.' },
  { id: 'temperate-archipelago', n: 2, name: 'Temperate Archipelago', description: 'Large oceans broken by island chains and coastal settlements.' },
  { id: 'ocean-world', n: 3, name: 'Ocean World', description: 'Almost entirely water, with scattered islands, floating habitats, or underwater sites.' },
  { id: 'shallow-sea-world', n: 4, name: 'Shallow-Sea World', description: 'Broad warm shallow oceans, reefs, sandbars, and low continents.' },
  { id: 'reef-world', n: 5, name: 'Reef World', description: 'Vast reef ecosystems dominate the seas and coastal shelves.' },
  { id: 'jungle-world', n: 6, name: 'Jungle World', description: 'Dense warm forests, heavy rainfall, and difficult overland travel.' },
  { id: 'megaforest-world', n: 7, name: 'Megaforest World', description: 'Enormous trees and vertically layered ecosystems dominate the land.' },
  { id: 'bioluminescent-forest', n: 8, name: 'Bioluminescent Forest', description: 'Forest ecosystems rich in naturally glowing flora and fungi.' },
  { id: 'fungal-world', n: 9, name: 'Fungal World', description: 'Giant fungal ecosystems occupy the ecological role of forests and grasslands.' },
  { id: 'swamp-world', n: 10, name: 'Swamp World', description: 'Marshes, wetlands, mud flats, and shallow water dominate the surface.' },
  { id: 'mangrove-world', n: 11, name: 'Mangrove World', description: 'Tangled coastal forests and waterways cover much of the habitable land.' },
  { id: 'savanna-world', n: 12, name: 'Savanna World', description: 'Open grasslands, scattered forests, and large migratory ecosystems.' },
  { id: 'prairie-steppe-world', n: 13, name: 'Prairie / Steppe World', description: 'Vast open grasslands with sparse cover and extreme horizons.' },
  { id: 'desert-world', n: 14, name: 'Desert World', description: 'Dry continents, dunes, rocky wastes, and isolated fertile zones.' },
  { id: 'dune-sea-world', n: 15, name: 'Dune-Sea World', description: 'Giant shifting sand seas broken by rocky islands and exposed ridges.' },
  { id: 'canyon-world', n: 16, name: 'Canyon World', description: 'Deep ravines, enormous canyon systems, and cliff settlements.' },
  { id: 'mesa-world', n: 17, name: 'Mesa World', description: 'Plateaus, cliffs, isolated highlands, and broad dry valleys.' },
  { id: 'salt-world', n: 18, name: 'Salt World', description: 'Ancient dried seas, salt flats, brine basins, and mineral crusts.' },
  { id: 'badlands-world', n: 19, name: 'Badlands World', description: 'Highly eroded terrain with ravines, exposed strata, and broken rock.' },
  { id: 'volcanic-world', n: 20, name: 'Volcanic World', description: 'Lava fields, volcanic chains, geothermal valleys, and fertile ashlands.' },
  { id: 'lava-world', n: 21, name: 'Lava World', description: 'Extensive molten regions and survivable zones separated by severe heat.' },
  { id: 'ash-world', n: 22, name: 'Ash World', description: 'Dark ash plains, volcanic dust, and intermittent eruptive regions.' },
  { id: 'geothermal-world', n: 23, name: 'Geothermal World', description: 'Geysers, hot springs, steam vents, and heat-driven ecosystems.' },
  { id: 'ice-world', n: 24, name: 'Ice World', description: 'Glaciers, frozen oceans, permanent snowfields, and isolated warm pockets.' },
  { id: 'tundra-world', n: 25, name: 'Tundra World', description: 'Cold but broadly habitable plains, mosslands, and short growing seasons.' },
  { id: 'glacial-ocean-world', n: 26, name: 'Glacial-Ocean World', description: 'Thick surface ice conceals large oceans and sub-ice ecosystems.' },
  { id: 'alpine-world', n: 27, name: 'Alpine World', description: 'Mountains dominate nearly every continent and habitable valley.' },
  { id: 'highland-world', n: 28, name: 'Highland World', description: 'Rolling uplands, high plateaus, and steep river valleys.' },
  { id: 'storm-world', n: 29, name: 'Storm World', description: 'Climate and ecology are shaped by frequent major storms.' },
  { id: 'monsoon-world', n: 30, name: 'Monsoon World', description: 'Powerful seasonal rain cycles produce floodplains and lush wet seasons.' },
  { id: 'hyper-wind-world', n: 31, name: 'Hyper-Wind World', description: 'Strong persistent winds shape terrain, architecture, and ecology.' },
  { id: 'lightning-world', n: 32, name: 'Lightning World', description: 'Intense electrical storms are a defining feature of the environment.' },
  { id: 'electromagnetic-world', n: 33, name: 'Electromagnetic World', description: 'Strong natural electromagnetic activity shapes settlement and technology use.' },
  { id: 'aurora-world', n: 34, name: 'Aurora World', description: 'Powerful magnetospheric effects create frequent, planet-wide auroral displays.' },
  { id: 'radiation-heavy-world', n: 35, name: 'Radiation-Heavy World', description: 'Surface ecosystems exist under unusually high natural radiation.' },
  { id: 'thin-atmosphere-world', n: 36, name: 'Thin-Atmosphere World', description: 'Broadly explorable terrain with a naturally sparse atmosphere.' },
  { id: 'dense-atmosphere-world', n: 37, name: 'Dense-Atmosphere World', description: 'Heavy air, thick haze, unusual weather, and reduced long-range visibility.' },
  { id: 'low-gravity-world', n: 38, name: 'Low-Gravity World', description: 'Habitable terrain shaped by weak gravity and tall natural formations.' },
  { id: 'high-gravity-world', n: 39, name: 'High-Gravity World', description: 'Dense, compact terrain and life adapted to stronger gravity.' },
  { id: 'tidally-locked-world', n: 40, name: 'Tidally Locked World', description: 'Permanent day, permanent night, and a habitable transition belt.' },
  { id: 'twilight-world', n: 41, name: 'Twilight World', description: 'Most life and settlement concentrate in a persistent dusk climate.' },
  { id: 'extreme-season-world', n: 42, name: 'Extreme-Season World', description: 'Huge seasonal swings dominate ecology and settlement patterns.' },
  { id: 'crystal-world', n: 43, name: 'Crystal World', description: 'Giant natural crystal formations and mineral forests shape the landscape.' },
  { id: 'glass-desert-world', n: 44, name: 'Glass Desert World', description: 'Fused glass, obsidian plains, and heat-scarred terrain dominate.' },
  { id: 'metallic-plains-world', n: 45, name: 'Metallic Plains World', description: 'Exposed metal-rich geology creates strange plains and ridges.' },
  { id: 'subterranean-world', n: 46, name: 'Subterranean World', description: 'Most life and civilization occupy vast underground habitats.' },
  { id: 'cavern-world', n: 47, name: 'Cavern World', description: 'Sinkholes, cave seas, natural vaults, and giant chamber systems dominate.' },
  { id: 'floating-island-world', n: 48, name: 'Floating-Island World', description: 'Rare atmospheric/geological conditions support suspended landmasses.' },
  { id: 'post-biosphere-world', n: 49, name: 'Post-Biosphere World', description: 'Once-rich ecology has largely collapsed, leaving ruins and survivor pockets.' },
  { id: 'pristine-wild-world', n: 50, name: 'Pristine Wild World', description: 'Highly habitable, biologically rich, and only lightly settled.' },
  { id: 'rainforest-basin-world', n: 51, name: 'Rainforest Basin World', description: 'Giant lowland basins trap moisture and support dense rainforests.' },
  { id: 'cloud-forest-world', n: 52, name: 'Cloud-Forest World', description: 'Cool, misty mountain forests dominate habitable elevations.' },
  { id: 'redwood-world', n: 53, name: 'Redwood World', description: 'Towering long-lived forests create enormous shaded ecosystems.' },
  { id: 'bamboo-forest-world', n: 54, name: 'Bamboo-Forest World', description: 'Fast-growing woody grasslands form dense continental forests.' },
  { id: 'thorn-scrub-world', n: 55, name: 'Thorn-Scrub World', description: 'Dry, tangled thorn vegetation dominates warm semi-arid regions.' },
  { id: 'mediterranean-world', n: 56, name: 'Mediterranean World', description: 'Dry summers, mild wet winters, scrub forests, and coastal agriculture.' },
  { id: 'chaparral-world', n: 57, name: 'Chaparral World', description: 'Fire-adapted shrublands cover broad warm uplands.' },
  { id: 'floodplain-world', n: 58, name: 'Floodplain World', description: 'Huge rivers and seasonal flood basins dominate settlement and farming.' },
  { id: 'river-delta-world', n: 59, name: 'River-Delta World', description: 'Branching river deltas, marsh islands, and sediment-rich lowlands.' },
  { id: 'lake-world', n: 60, name: 'Lake World', description: 'Thousands of freshwater seas and giant lake systems dominate the land.' },
  { id: 'inland-sea-world', n: 61, name: 'Inland-Sea World', description: 'Continents surround vast enclosed seas and fertile coastal belts.' },
  { id: 'atoll-world', n: 62, name: 'Atoll World', description: 'Low coral-ring islands and lagoons make up nearly all dry land.' },
  { id: 'karst-world', n: 63, name: 'Karst World', description: 'Limestone towers, sinkholes, caves, and underground rivers dominate.' },
  { id: 'sinkhole-world', n: 64, name: 'Sinkhole World', description: 'Vast collapse basins and vertical shafts shape the landscape.' },
  { id: 'basalt-world', n: 65, name: 'Basalt World', description: 'Dark volcanic plateaus and columnar rock fields dominate.' },
  { id: 'obsidian-world', n: 66, name: 'Obsidian World', description: 'Volcanic glass fields and black ridges are common terrain.' },
  { id: 'pumice-world', n: 67, name: 'Pumice World', description: 'Lightweight volcanic rock, porous plains, and floating stone fields.' },
  { id: 'hot-spring-world', n: 68, name: 'Hot-Spring World', description: 'Mineral springs and warm-water wetlands support dense settlement.' },
  { id: 'mud-volcano-world', n: 69, name: 'Mud-Volcano World', description: 'Sediment eruptions, clay flats, and gas-rich basins are widespread.' },
  { id: 'permafrost-world', n: 70, name: 'Permafrost World', description: 'Permanently frozen ground supports sparse but resilient ecosystems.' },
  { id: 'snow-forest-world', n: 71, name: 'Snow-Forest World', description: 'Boreal forests and deep seasonal snow dominate the habitable regions.' },
  { id: 'polar-desert-world', n: 72, name: 'Polar-Desert World', description: 'Extremely cold, very dry terrain with little precipitation.' },
  { id: 'sea-ice-world', n: 73, name: 'Sea-Ice World', description: 'Seasonal or permanent floating ice covers most oceans.' },
  { id: 'fog-world', n: 74, name: 'Fog World', description: 'Persistent ground fog and low cloud define much of the surface.' },
  { id: 'mist-coast-world', n: 75, name: 'Mist-Coast World', description: 'Cool oceanic coasts, cliffs, fog forests, and wet grasslands.' },
  { id: 'cloud-sea-world', n: 76, name: 'Cloud-Sea World', description: 'High plateaus rise above vast lower cloud layers.' },
  { id: 'supercontinent-world', n: 77, name: 'Supercontinent World', description: 'Most dry land forms one enormous connected landmass.' },
  { id: 'island-continent-world', n: 78, name: 'Island-Continent World', description: 'Several Australia-scale islands dominate the world ocean.' },
  { id: 'fragmented-continent-world', n: 79, name: 'Fragmented-Continent World', description: 'Many mid-sized continents and interior seas create complex coastlines.' },
  { id: 'rift-valley-world', n: 80, name: 'Rift-Valley World', description: 'Active continental rifts form deep valleys, lakes, and volcanic belts.' },
  { id: 'impact-basin-world', n: 81, name: 'Impact-Basin World', description: 'Giant ancient craters create seas, mountain rings, and isolated ecosystems.' },
  { id: 'crater-lake-world', n: 82, name: 'Crater-Lake World', description: 'Large impact craters commonly contain lakes and fertile basins.' },
  { id: 'mountain-ring-world', n: 83, name: 'Mountain-Ring World', description: 'Circular mountain systems surround huge interior plains or seas.' },
  { id: 'plateau-sea-world', n: 84, name: 'Plateau-Sea World', description: 'High continents are cut by shallow inland seas and flooded shelves.' },
  { id: 'cliff-coast-world', n: 85, name: 'Cliff-Coast World', description: 'Sheer coastal cliffs and narrow littoral zones dominate the shorelines.' },
  { id: 'red-sand-world', n: 86, name: 'Red-Sand World', description: 'Iron-rich dunes and rust-colored plains dominate dry regions.' },
  { id: 'blue-grass-world', n: 87, name: 'Blue-Grass World', description: 'Photosynthetic ground cover creates blue-toned grasslands and meadows.' },
  { id: 'purple-flora-world', n: 88, name: 'Purple-Flora World', description: 'Dominant plant pigments give forests and plains violet coloration.' },
  { id: 'amber-forest-world', n: 89, name: 'Amber-Forest World', description: 'Golden/orange photosynthetic flora dominates temperate forests.' },
  { id: 'coral-land-world', n: 90, name: 'Coral-Land World', description: 'Reef-like terrestrial organisms build rigid branching landscapes on land.' },
  { id: 'spore-sea-world', n: 91, name: 'Spore-Sea World', description: 'Airborne spores and giant fungal mats dominate ecology.' },
  { id: 'vine-world', n: 92, name: 'Vine World', description: 'Fast-growing vines and creepers overwhelm most exposed land.' },
  { id: 'flowering-plain-world', n: 93, name: 'Flowering-Plain World', description: 'Vast flowering grasslands and seasonal bloom events dominate.' },
  { id: 'giant-fern-world', n: 94, name: 'Giant-Fern World', description: 'Fern-like megaflora forms dense humid forests.' },
  { id: 'root-maze-world', n: 95, name: 'Root-Maze World', description: 'Massive exposed root networks create natural tunnels and elevated terrain.' },
  { id: 'shell-reef-world', n: 96, name: 'Shell-Reef World', description: 'Mineralized shell organisms form continental-scale reef structures.' },
  { id: 'tar-pit-world', n: 97, name: 'Tar-Pit World', description: 'Hydrocarbon seeps, tar basins, and petroleum wetlands shape large regions.' },
  { id: 'mineral-spring-world', n: 98, name: 'Mineral-Spring World', description: 'Colorful mineral terraces, alkaline lakes, and chemical wetlands are common.' },
  { id: 'dry-ocean-basin-world', n: 99, name: 'Dry-Ocean-Basin World', description: 'Former seabeds form immense low basins below rugged continental rims.' },
  { id: 'patchwork-world', n: 100, name: 'Patchwork World', description: 'Strongly varied climate zones create abrupt biome transitions across short distances.' },
];

/** Part II — 300 environmental modifiers. */
export const PLANET_MODIFIERS: PlanetModifierEntry[] = [
  { id: 'breathable-oxygen-rich-air', n: 1, name: 'Breathable Oxygen-Rich Air', category: 'Atmosphere & Air', description: 'Slightly elevated oxygen supports easy respiration and stronger fires.' },
  { id: 'breathable-low-oxygen-air', n: 2, name: 'Breathable Low-Oxygen Air', category: 'Atmosphere & Air', description: 'Survivable without gear, but strenuous activity is more tiring.' },
  { id: 'thin-breathable-atmosphere', n: 3, name: 'Thin Breathable Atmosphere', category: 'Atmosphere & Air', description: 'Safe for most people but physically taxing at elevation.' },
  { id: 'dense-breathable-atmosphere', n: 4, name: 'Dense Breathable Atmosphere', category: 'Atmosphere & Air', description: 'Heavy air changes sound, flight, weather, and movement.' },
  { id: 'high-humidity', n: 5, name: 'High Humidity', category: 'Atmosphere & Air', description: 'Air remains persistently moist.' },
  { id: 'extremely-dry-air', n: 6, name: 'Extremely Dry Air', category: 'Atmosphere & Air', description: 'Dehydration and skin/gear wear become more important.' },
  { id: 'high-carbon-dioxide-background', n: 7, name: 'High Carbon Dioxide Background', category: 'Atmosphere & Air', description: 'Breathable overall but tiring during prolonged exertion.' },
  { id: 'high-inert-gas-content', n: 8, name: 'High Inert-Gas Content', category: 'Atmosphere & Air', description: 'Breathing remains possible but pressure behavior is unusual.' },
  { id: 'strong-atmospheric-haze', n: 9, name: 'Strong Atmospheric Haze', category: 'Atmosphere & Air', description: 'Long-distance visibility is reduced.' },
  { id: 'crystal-clear-air', n: 10, name: 'Crystal-Clear Air', category: 'Atmosphere & Air', description: 'Exceptional visibility across very long distances.' },
  { id: 'persistent-dust-in-air', n: 11, name: 'Persistent Dust in Air', category: 'Atmosphere & Air', description: 'Fine particles affect visibility and machinery.' },
  { id: 'salt-laden-air', n: 12, name: 'Salt-Laden Air', category: 'Atmosphere & Air', description: 'Coastal aerosols accelerate corrosion.' },
  { id: 'sulfur-trace-atmosphere', n: 13, name: 'Sulfur Trace Atmosphere', category: 'Atmosphere & Air', description: 'The air smells harsh and irritates some species.' },
  { id: 'metallic-aerosols', n: 14, name: 'Metallic Aerosols', category: 'Atmosphere & Air', description: 'Fine mineral particles create unusual skies and equipment wear.' },
  { id: 'seasonal-pollen-saturation', n: 15, name: 'Seasonal Pollen Saturation', category: 'Atmosphere & Air', description: 'Airborne biological material spikes during certain seasons.' },
  { id: 'spore-heavy-atmosphere', n: 16, name: 'Spore-Heavy Atmosphere', category: 'Atmosphere & Air', description: 'Fungal spores are common and may trigger health events.' },
  { id: 'natural-smog-layers', n: 17, name: 'Natural Smog Layers', category: 'Atmosphere & Air', description: 'Geology and biology combine to produce persistent atmospheric murk.' },
  { id: 'high-pressure-surface-air', n: 18, name: 'High-Pressure Surface Air', category: 'Atmosphere & Air', description: 'Sea-level atmospheric pressure is well above standard.' },
  { id: 'low-pressure-surface-air', n: 19, name: 'Low-Pressure Surface Air', category: 'Atmosphere & Air', description: 'Sea-level pressure is below standard but generally survivable.' },
  { id: 'localized-toxic-air-pockets', n: 20, name: 'Localized Toxic Air Pockets', category: 'Atmosphere & Air', description: 'Most air is safe, but valleys/caves can accumulate dangerous gases.' },
  { id: 'frequent-thunderstorms', n: 21, name: 'Frequent Thunderstorms', category: 'Weather & Storms', description: 'Electrical storms are a routine part of the climate.' },
  { id: 'rare-superstorms', n: 22, name: 'Rare Superstorms', category: 'Weather & Storms', description: 'Long calm periods are interrupted by catastrophic weather.' },
  { id: 'permanent-storm-belts', n: 23, name: 'Permanent Storm Belts', category: 'Weather & Storms', description: 'Certain latitude bands experience nearly constant storms.' },
  { id: 'hypercanes', n: 24, name: 'Hypercanes', category: 'Weather & Storms', description: 'Extremely powerful tropical cyclones occasionally form.' },
  { id: 'seasonal-monsoons', n: 25, name: 'Seasonal Monsoons', category: 'Weather & Storms', description: 'Predictable wet seasons transform travel and settlement.' },
  { id: 'flash-flood-climate', n: 26, name: 'Flash-Flood Climate', category: 'Weather & Storms', description: 'Intense rain quickly turns dry channels into dangerous rivers.' },
  { id: 'persistent-drizzle', n: 27, name: 'Persistent Drizzle', category: 'Weather & Storms', description: 'Light rainfall is nearly constant.' },
  { id: 'heavy-snow-seasons', n: 28, name: 'Heavy Snow Seasons', category: 'Weather & Storms', description: 'Deep snowfall regularly blocks travel.' },
  { id: 'blizzard-zones', n: 29, name: 'Blizzard Zones', category: 'Weather & Storms', description: 'Certain regions experience frequent whiteout storms.' },
  { id: 'hail-seasons', n: 30, name: 'Hail Seasons', category: 'Weather & Storms', description: 'Large hail periodically damages crops, vehicles, and structures.' },
  { id: 'dust-storms', n: 31, name: 'Dust Storms', category: 'Weather & Storms', description: 'Fine particulate storms sweep across open terrain.' },
  { id: 'sandstorms', n: 32, name: 'Sandstorms', category: 'Weather & Storms', description: 'Abrasive sand makes exposed travel hazardous.' },
  { id: 'ash-storms', n: 33, name: 'Ash Storms', category: 'Weather & Storms', description: 'Volcanic ash is redistributed by weather systems.' },
  { id: 'salt-storms', n: 34, name: 'Salt Storms', category: 'Weather & Storms', description: 'Dry salt particles blow across former seabeds.' },
  { id: 'electrical-rain', n: 35, name: 'Electrical Rain', category: 'Weather & Storms', description: 'Rainfall is often accompanied by intense static discharge.' },
  { id: 'warm-rain', n: 36, name: 'Warm Rain', category: 'Weather & Storms', description: 'Precipitation remains unusually warm even in temperate zones.' },
  { id: 'freezing-rain', n: 37, name: 'Freezing Rain', category: 'Weather & Storms', description: 'Ice accumulation creates recurring travel hazards.' },
  { id: 'microburst-weather', n: 38, name: 'Microburst Weather', category: 'Weather & Storms', description: 'Sudden localized downdrafts make flight and surface travel unpredictable.' },
  { id: 'strong-jetstream-surface-winds', n: 39, name: 'Strong Jetstream Surface Winds', category: 'Weather & Storms', description: 'High winds regularly descend to inhabited elevations.' },
  { id: 'calm-climate', n: 40, name: 'Calm Climate', category: 'Weather & Storms', description: 'Severe weather is unusually rare.' },
  { id: 'generally-warm', n: 41, name: 'Generally Warm', category: 'Temperature & Climate', description: 'Most inhabited regions remain above standard temperate temperatures.' },
  { id: 'generally-cool', n: 42, name: 'Generally Cool', category: 'Temperature & Climate', description: 'Habitable regions skew cooler than human comfort norms.' },
  { id: 'hot-days-cold-nights', n: 43, name: 'Hot Days / Cold Nights', category: 'Temperature & Climate', description: 'Large daily temperature swings are common.' },
  { id: 'mild-year-round-climate', n: 44, name: 'Mild Year-Round Climate', category: 'Temperature & Climate', description: 'Seasonal variation is limited.' },
  { id: 'severe-winters', n: 45, name: 'Severe Winters', category: 'Temperature & Climate', description: 'Winters strongly affect travel, agriculture, and settlement.' },
  { id: 'severe-summers', n: 46, name: 'Severe Summers', category: 'Temperature & Climate', description: 'Peak heat becomes a seasonal hazard.' },
  { id: 'long-spring', n: 47, name: 'Long Spring', category: 'Temperature & Climate', description: 'Transitional mild weather lasts unusually long.' },
  { id: 'long-autumn', n: 48, name: 'Long Autumn', category: 'Temperature & Climate', description: 'Cooling seasons are extended and stable.' },
  { id: 'short-growing-season', n: 49, name: 'Short Growing Season', category: 'Temperature & Climate', description: 'Agriculture depends on brief productive periods.' },
  { id: 'multiple-growing-seasons', n: 50, name: 'Multiple Growing Seasons', category: 'Temperature & Climate', description: 'Crops can be harvested repeatedly each year.' },
  { id: 'equatorial-heat-belt', n: 51, name: 'Equatorial Heat Belt', category: 'Temperature & Climate', description: 'Tropical latitudes are significantly harsher than usual.' },
  { id: 'cool-equator', n: 52, name: 'Cool Equator', category: 'Temperature & Climate', description: 'Atmospheric/ocean circulation keeps equatorial zones surprisingly mild.' },
  { id: 'warm-poles', n: 53, name: 'Warm Poles', category: 'Temperature & Climate', description: 'Polar regions remain relatively temperate.' },
  { id: 'frozen-poles', n: 54, name: 'Frozen Poles', category: 'Temperature & Climate', description: 'Ice caps are unusually large.' },
  { id: 'extreme-seasonal-tilt', n: 55, name: 'Extreme Seasonal Tilt', category: 'Temperature & Climate', description: 'Axial tilt creates dramatic seasonal differences.' },
  { id: 'minimal-seasons', n: 56, name: 'Minimal Seasons', category: 'Temperature & Climate', description: 'Axial tilt is low and climate varies little through the year.' },
  { id: 'rapid-seasonal-change', n: 57, name: 'Rapid Seasonal Change', category: 'Temperature & Climate', description: 'Weather shifts abruptly between seasonal states.' },
  { id: 'long-seasonal-cycles', n: 58, name: 'Long Seasonal Cycles', category: 'Temperature & Climate', description: 'Seasons last years rather than months.' },
  { id: 'localized-heat-islands', n: 59, name: 'Localized Heat Islands', category: 'Temperature & Climate', description: 'Geothermal or geological regions stay much warmer than surroundings.' },
  { id: 'localized-cold-sinks', n: 60, name: 'Localized Cold Sinks', category: 'Temperature & Climate', description: 'Deep basins trap cold air and remain icy year-round.' },
  { id: 'low-gravity', n: 61, name: 'Low Gravity', category: 'Gravity & Physical Conditions', description: 'Surface gravity is noticeably below standard.' },
  { id: 'very-low-gravity', n: 62, name: 'Very Low Gravity', category: 'Gravity & Physical Conditions', description: 'Movement, construction, and falls behave dramatically differently.' },
  { id: 'high-gravity', n: 63, name: 'High Gravity', category: 'Gravity & Physical Conditions', description: 'Surface movement and lifting are more tiring.' },
  { id: 'very-high-gravity', n: 64, name: 'Very High Gravity', category: 'Gravity & Physical Conditions', description: 'Extended activity demands major physical adaptation or assistance.' },
  { id: 'uneven-gravity-anomalies', n: 65, name: 'Uneven Gravity Anomalies', category: 'Gravity & Physical Conditions', description: 'Localized regions produce measurable gravity variation.' },
  { id: 'strong-tidal-forces', n: 66, name: 'Strong Tidal Forces', category: 'Gravity & Physical Conditions', description: 'Moons or nearby bodies create powerful tides and crustal effects.' },
  { id: 'weak-tidal-forces', n: 67, name: 'Weak Tidal Forces', category: 'Gravity & Physical Conditions', description: 'Oceans and coastal cycles are unusually mild.' },
  { id: 'rapid-rotation', n: 68, name: 'Rapid Rotation', category: 'Gravity & Physical Conditions', description: 'Short days and strong Coriolis effects shape weather.' },
  { id: 'slow-rotation', n: 69, name: 'Slow Rotation', category: 'Gravity & Physical Conditions', description: 'Long days and nights influence climate and behavior.' },
  { id: 'long-day-cycle', n: 70, name: 'Long Day Cycle', category: 'Gravity & Physical Conditions', description: 'One day lasts several standard days.' },
  { id: 'short-day-cycle', n: 71, name: 'Short Day Cycle', category: 'Gravity & Physical Conditions', description: 'Day/night cycles pass quickly.' },
  { id: 'multiple-moon-tides', n: 72, name: 'Multiple-Moon Tides', category: 'Gravity & Physical Conditions', description: 'Several moons create complex tidal patterns.' },
  { id: 'large-moon-dominance', n: 73, name: 'Large Moon Dominance', category: 'Gravity & Physical Conditions', description: 'One huge moon strongly shapes tides and night skies.' },
  { id: 'no-major-moon', n: 74, name: 'No Major Moon', category: 'Gravity & Physical Conditions', description: 'Tides are weak and nights are darker.' },
  { id: 'frequent-microquakes', n: 75, name: 'Frequent Microquakes', category: 'Gravity & Physical Conditions', description: 'Small tremors are common but rarely destructive.' },
  { id: 'crustal-flexing', n: 76, name: 'Crustal Flexing', category: 'Gravity & Physical Conditions', description: 'Tidal forces regularly deform the surface.' },
  { id: 'low-escape-velocity', n: 77, name: 'Low Escape Velocity', category: 'Gravity & Physical Conditions', description: 'Atmospheric loss and easy launch conditions affect technology.' },
  { id: 'high-escape-velocity', n: 78, name: 'High Escape Velocity', category: 'Gravity & Physical Conditions', description: 'Launching to orbit is more expensive and difficult.' },
  { id: 'strong-surface-buoyancy', n: 79, name: 'Strong Surface Buoyancy', category: 'Gravity & Physical Conditions', description: 'Dense atmosphere or fluid conditions change vehicle behavior.' },
  { id: 'high-atmospheric-drag', n: 80, name: 'High Atmospheric Drag', category: 'Gravity & Physical Conditions', description: 'Flight and projectile behavior differ noticeably.' },
  { id: 'active-plate-tectonics', n: 81, name: 'Active Plate Tectonics', category: 'Geology & Seismic Activity', description: 'Continents shift and mountain building remains vigorous.' },
  { id: 'geologically-quiet', n: 82, name: 'Geologically Quiet', category: 'Geology & Seismic Activity', description: 'Major earthquakes and volcanism are rare.' },
  { id: 'frequent-earthquakes', n: 83, name: 'Frequent Earthquakes', category: 'Geology & Seismic Activity', description: 'Significant quakes occur regularly.' },
  { id: 'megaquake-risk', n: 84, name: 'Megaquake Risk', category: 'Geology & Seismic Activity', description: 'Rare but devastating seismic events shape construction standards.' },
  { id: 'volcanic-hotspots', n: 85, name: 'Volcanic Hotspots', category: 'Geology & Seismic Activity', description: 'Isolated mantle plumes create island chains and lava provinces.' },
  { id: 'ring-of-fire-belts', n: 86, name: 'Ring-of-Fire Belts', category: 'Geology & Seismic Activity', description: 'Volcanic arcs surround large ocean basins.' },
  { id: 'supervolcano-regions', n: 87, name: 'Supervolcano Regions', category: 'Geology & Seismic Activity', description: 'Massive calderas create long-term hazard zones.' },
  { id: 'geothermal-abundance', n: 88, name: 'Geothermal Abundance', category: 'Geology & Seismic Activity', description: 'Usable geothermal heat is widespread.' },
  { id: 'unstable-sinkholes', n: 89, name: 'Unstable Sinkholes', category: 'Geology & Seismic Activity', description: 'Ground collapse is a recurring regional risk.' },
  { id: 'karst-instability', n: 90, name: 'Karst Instability', category: 'Geology & Seismic Activity', description: 'Cave collapse and underground drainage reshape terrain.' },
  { id: 'rapid-erosion', n: 91, name: 'Rapid Erosion', category: 'Geology & Seismic Activity', description: 'Soft geology changes valleys and cliffs quickly.' },
  { id: 'slow-erosion', n: 92, name: 'Slow Erosion', category: 'Geology & Seismic Activity', description: 'Hard rock preserves ancient terrain features.' },
  { id: 'rich-sedimentary-basins', n: 93, name: 'Rich Sedimentary Basins', category: 'Geology & Seismic Activity', description: 'Fossils, fuels, and layered minerals are abundant.' },
  { id: 'exposed-mantle-rock', n: 94, name: 'Exposed Mantle Rock', category: 'Geology & Seismic Activity', description: 'Deep geological material reaches the surface in rare zones.' },
  { id: 'basalt-flood-provinces', n: 95, name: 'Basalt Flood Provinces', category: 'Geology & Seismic Activity', description: 'Ancient lava flows cover huge continental areas.' },
  { id: 'active-rift-zones', n: 96, name: 'Active Rift Zones', category: 'Geology & Seismic Activity', description: 'New crust and rift valleys are still forming.' },
  { id: 'subduction-trenches', n: 97, name: 'Subduction Trenches', category: 'Geology & Seismic Activity', description: 'Deep ocean trenches and volcanic margins are common.' },
  { id: 'impact-rich-geology', n: 98, name: 'Impact-Rich Geology', category: 'Geology & Seismic Activity', description: 'Ancient craters heavily shape the surface.' },
  { id: 'young-surface', n: 99, name: 'Young Surface', category: 'Geology & Seismic Activity', description: 'Much of the crust has been resurfaced relatively recently.' },
  { id: 'ancient-surface', n: 100, name: 'Ancient Surface', category: 'Geology & Seismic Activity', description: 'Extremely old landscapes preserve deep planetary history.' },
  { id: 'strong-magnetosphere', n: 101, name: 'Strong Magnetosphere', category: 'Magnetic, Electrical & Radiation', description: 'Surface radiation is well shielded.' },
  { id: 'weak-magnetosphere', n: 102, name: 'Weak Magnetosphere', category: 'Magnetic, Electrical & Radiation', description: 'Radiation exposure is elevated at altitude and during storms.' },
  { id: 'chaotic-magnetic-field', n: 103, name: 'Chaotic Magnetic Field', category: 'Magnetic, Electrical & Radiation', description: 'Compass/navigation behavior is unreliable.' },
  { id: 'magnetic-reversal-era', n: 104, name: 'Magnetic Reversal Era', category: 'Magnetic, Electrical & Radiation', description: 'Field orientation is unstable over geological timescales.' },
  { id: 'localized-magnetic-anomalies', n: 105, name: 'Localized Magnetic Anomalies', category: 'Magnetic, Electrical & Radiation', description: 'Certain regions strongly distort sensors.' },
  { id: 'frequent-auroras', n: 106, name: 'Frequent Auroras', category: 'Magnetic, Electrical & Radiation', description: 'Auroral displays are common far from the poles.' },
  { id: 'planet-wide-auroras', n: 107, name: 'Planet-Wide Auroras', category: 'Magnetic, Electrical & Radiation', description: 'Major solar activity can light much of the sky.' },
  { id: 'electrical-ground-currents', n: 108, name: 'Electrical Ground Currents', category: 'Magnetic, Electrical & Radiation', description: 'Natural currents interfere with buried infrastructure.' },
  { id: 'static-charged-environment', n: 109, name: 'Static-Charged Environment', category: 'Magnetic, Electrical & Radiation', description: 'Movement and storms frequently build dangerous static.' },
  { id: 'lightning-rich-atmosphere', n: 110, name: 'Lightning-Rich Atmosphere', category: 'Magnetic, Electrical & Radiation', description: 'Electrical discharge is unusually common.' },
  { id: 'high-background-radiation', n: 111, name: 'High Background Radiation', category: 'Magnetic, Electrical & Radiation', description: 'Natural radiation exceeds standard inhabited-world norms.' },
  { id: 'radiation-safe-zones', n: 112, name: 'Radiation Safe Zones', category: 'Magnetic, Electrical & Radiation', description: 'Geography creates pockets of unusually low exposure.' },
  { id: 'solar-flare-exposure', n: 113, name: 'Solar-Flare Exposure', category: 'Magnetic, Electrical & Radiation', description: 'Weak shielding makes stellar activity a periodic hazard.' },
  { id: 'particle-storm-seasons', n: 114, name: 'Particle-Storm Seasons', category: 'Magnetic, Electrical & Radiation', description: 'Charged-particle events occur predictably.' },
  { id: 'radio-noise-environment', n: 115, name: 'Radio-Noise Environment', category: 'Magnetic, Electrical & Radiation', description: 'Natural emissions interfere with communications.' },
  { id: 'sensor-interference-zones', n: 116, name: 'Sensor-Interference Zones', category: 'Magnetic, Electrical & Radiation', description: 'Geology or atmosphere creates persistent scanning blind spots.' },
  { id: 'emp-storms', n: 117, name: 'EMP Storms', category: 'Magnetic, Electrical & Radiation', description: 'Rare electromagnetic pulses can disrupt unshielded electronics.' },
  { id: 'charged-dust', n: 118, name: 'Charged Dust', category: 'Magnetic, Electrical & Radiation', description: 'Airborne mineral particles carry significant electrical charge.' },
  { id: 'piezoelectric-terrain', n: 119, name: 'Piezoelectric Terrain', category: 'Magnetic, Electrical & Radiation', description: 'Stress in rock generates measurable electrical effects.' },
  { id: 'magnetic-mineral-belts', n: 120, name: 'Magnetic Mineral Belts', category: 'Magnetic, Electrical & Radiation', description: 'Ore-rich regions strongly affect navigation and machinery.' },
  { id: 'water-rich-surface', n: 121, name: 'Water-Rich Surface', category: 'Water & Hydrology', description: 'Lakes, rivers, wetlands, and seas are common.' },
  { id: 'water-poor-surface', n: 122, name: 'Water-Poor Surface', category: 'Water & Hydrology', description: 'Liquid surface water is scarce outside protected basins.' },
  { id: 'deep-global-oceans', n: 123, name: 'Deep Global Oceans', category: 'Water & Hydrology', description: 'Ocean trenches reach extreme depths.' },
  { id: 'shallow-global-seas', n: 124, name: 'Shallow Global Seas', category: 'Water & Hydrology', description: 'Large areas are covered by relatively shallow water.' },
  { id: 'strong-tides', n: 125, name: 'Strong Tides', category: 'Water & Hydrology', description: 'Coastal water levels change dramatically.' },
  { id: 'mega-tides', n: 126, name: 'Mega-Tides', category: 'Water & Hydrology', description: 'Tidal cycles inundate huge coastal areas.' },
  { id: 'minimal-tides', n: 127, name: 'Minimal Tides', category: 'Water & Hydrology', description: 'Coastlines remain comparatively stable.' },
  { id: 'seasonal-flooding', n: 128, name: 'Seasonal Flooding', category: 'Water & Hydrology', description: 'Rivers and wetlands expand predictably each year.' },
  { id: 'glacial-melt-seasons', n: 129, name: 'Glacial Melt Seasons', category: 'Water & Hydrology', description: 'Large meltwater pulses reshape rivers and valleys.' },
  { id: 'underground-aquifers', n: 130, name: 'Underground Aquifers', category: 'Water & Hydrology', description: 'Major freshwater reserves lie beneath the surface.' },
  { id: 'subterranean-oceans', n: 131, name: 'Subterranean Oceans', category: 'Water & Hydrology', description: 'Deep liquid reservoirs exist beneath crustal layers.' },
  { id: 'brine-seas', n: 132, name: 'Brine Seas', category: 'Water & Hydrology', description: 'Many large bodies of water are highly saline.' },
  { id: 'freshwater-dominant-oceans', n: 133, name: 'Freshwater-Dominant Oceans', category: 'Water & Hydrology', description: 'Unusually low-salinity seas support distinct ecosystems.' },
  { id: 'acidic-lakes', n: 134, name: 'Acidic Lakes', category: 'Water & Hydrology', description: 'Some basins contain naturally corrosive water.' },
  { id: 'alkaline-lakes', n: 135, name: 'Alkaline Lakes', category: 'Water & Hydrology', description: 'Mineral-rich basic lakes create unusual habitats.' },
  { id: 'hot-oceans', n: 136, name: 'Hot Oceans', category: 'Water & Hydrology', description: 'Ocean temperatures remain unusually high.' },
  { id: 'cold-oceans', n: 137, name: 'Cold Oceans', category: 'Water & Hydrology', description: 'Most seas are frigid even outside polar regions.' },
  { id: 'hydrothermal-vent-abundance', n: 138, name: 'Hydrothermal Vent Abundance', category: 'Water & Hydrology', description: 'Seafloors contain widespread vent ecosystems.' },
  { id: 'violent-surf', n: 139, name: 'Violent Surf', category: 'Water & Hydrology', description: 'Strong wave energy dominates exposed coasts.' },
  { id: 'calm-inland-waters', n: 140, name: 'Calm Inland Waters', category: 'Water & Hydrology', description: 'Huge protected seas have very little wave action.' },
  { id: 'high-biodiversity', n: 141, name: 'High Biodiversity', category: 'Ecology & Biosphere', description: 'Many ecological niches support enormous species variety.' },
  { id: 'low-biodiversity', n: 142, name: 'Low Biodiversity', category: 'Ecology & Biosphere', description: 'A small number of organisms dominate most ecosystems.' },
  { id: 'rapid-evolution', n: 143, name: 'Rapid Evolution', category: 'Ecology & Biosphere', description: 'Short generation times and environmental pressure drive fast adaptation.' },
  { id: 'slow-evolutionary-turnover', n: 144, name: 'Slow Evolutionary Turnover', category: 'Ecology & Biosphere', description: 'Stable ecosystems change very gradually.' },
  { id: 'megafauna-common', n: 145, name: 'Megafauna Common', category: 'Ecology & Biosphere', description: 'Very large land or sea animals are widespread.' },
  { id: 'microfauna-dominant', n: 146, name: 'Microfauna Dominant', category: 'Ecology & Biosphere', description: 'Small organisms dominate animal life.' },
  { id: 'highly-territorial-wildlife', n: 147, name: 'Highly Territorial Wildlife', category: 'Ecology & Biosphere', description: 'Many species aggressively defend habitat.' },
  { id: 'docile-wildlife', n: 148, name: 'Docile Wildlife', category: 'Ecology & Biosphere', description: 'Large native animals are generally non-aggressive.' },
  { id: 'predator-rich-ecosystems', n: 149, name: 'Predator-Rich Ecosystems', category: 'Ecology & Biosphere', description: 'Apex predators are unusually abundant.' },
  { id: 'herbivore-rich-ecosystems', n: 150, name: 'Herbivore-Rich Ecosystems', category: 'Ecology & Biosphere', description: 'Large grazing/browsing populations dominate open biomes.' },
  { id: 'seasonal-migrations', n: 151, name: 'Seasonal Migrations', category: 'Ecology & Biosphere', description: 'Massive animal movements occur regularly.' },
  { id: 'swarm-cycles', n: 152, name: 'Swarm Cycles', category: 'Ecology & Biosphere', description: 'Insect-like or small flying organisms periodically appear in huge numbers.' },
  { id: 'bioluminescence-common', n: 153, name: 'Bioluminescence Common', category: 'Ecology & Biosphere', description: 'Many organisms produce visible light.' },
  { id: 'photosynthesis-uses-unusual-pigments', n: 154, name: 'Photosynthesis Uses Unusual Pigments', category: 'Ecology & Biosphere', description: 'Flora may appear purple, red, blue, or black.' },
  { id: 'airborne-seed-seasons', n: 155, name: 'Airborne Seed Seasons', category: 'Ecology & Biosphere', description: 'Massive seed dispersal changes visibility and air quality.' },
  { id: 'spore-blooms', n: 156, name: 'Spore Blooms', category: 'Ecology & Biosphere', description: 'Fungal reproduction creates periodic atmospheric events.' },
  { id: 'fast-growing-vegetation', n: 157, name: 'Fast-Growing Vegetation', category: 'Ecology & Biosphere', description: 'Cleared land is rapidly reclaimed.' },
  { id: 'slow-growing-vegetation', n: 158, name: 'Slow-Growing Vegetation', category: 'Ecology & Biosphere', description: 'Ecosystem recovery after damage takes decades or centuries.' },
  { id: 'symbiotic-ecosystems', n: 159, name: 'Symbiotic Ecosystems', category: 'Ecology & Biosphere', description: 'Many organisms depend on close multi-species relationships.' },
  { id: 'invasive-offworld-species', n: 160, name: 'Invasive-Offworld Species', category: 'Ecology & Biosphere', description: 'Imported organisms have reshaped major ecosystems.' },
  { id: 'giant-trees', n: 161, name: 'Giant Trees', category: 'Flora & Vegetation', description: 'Mature forests contain exceptionally tall organisms.' },
  { id: 'dense-understory', n: 162, name: 'Dense Understory', category: 'Flora & Vegetation', description: 'Ground travel through forests is difficult.' },
  { id: 'sparse-forests', n: 163, name: 'Sparse Forests', category: 'Flora & Vegetation', description: 'Trees are widely spaced with open ground beneath.' },
  { id: 'floating-vegetation', n: 164, name: 'Floating Vegetation', category: 'Flora & Vegetation', description: 'Plants form rafts, mats, or buoyant islands.' },
  { id: 'carnivorous-flora', n: 165, name: 'Carnivorous Flora', category: 'Flora & Vegetation', description: 'Some plants actively trap animal life.' },
  { id: 'mobile-flora', n: 166, name: 'Mobile Flora', category: 'Flora & Vegetation', description: 'Certain plant-like organisms slowly relocate.' },
  { id: 'hard-shelled-vegetation', n: 167, name: 'Hard-Shelled Vegetation', category: 'Flora & Vegetation', description: 'Plants use mineralized protective structures.' },
  { id: 'glasslike-leaves', n: 168, name: 'Glasslike Leaves', category: 'Flora & Vegetation', description: 'Silica-rich foliage creates sharp or reflective surfaces.' },
  { id: 'water-storing-plants', n: 169, name: 'Water-Storing Plants', category: 'Flora & Vegetation', description: 'Succulent forms dominate dry zones.' },
  { id: 'deep-rooted-flora', n: 170, name: 'Deep-Rooted Flora', category: 'Flora & Vegetation', description: 'Vegetation survives drought through enormous root systems.' },
  { id: 'shallow-rooted-flora', n: 171, name: 'Shallow-Rooted Flora', category: 'Flora & Vegetation', description: 'Surface moisture strongly controls plant distribution.' },
  { id: 'seasonal-superblooms', n: 172, name: 'Seasonal Superblooms', category: 'Flora & Vegetation', description: 'Huge synchronized flowering events occur.' },
  { id: 'evergreen-dominance', n: 173, name: 'Evergreen Dominance', category: 'Flora & Vegetation', description: 'Most vegetation retains foliage year-round.' },
  { id: 'deciduous-dominance', n: 174, name: 'Deciduous Dominance', category: 'Flora & Vegetation', description: 'Seasonal leaf loss dramatically changes landscapes.' },
  { id: 'fire-dependent-flora', n: 175, name: 'Fire-Dependent Flora', category: 'Flora & Vegetation', description: 'Many species require periodic burns to reproduce.' },
  { id: 'salt-tolerant-flora', n: 176, name: 'Salt-Tolerant Flora', category: 'Flora & Vegetation', description: 'Coastal and saline environments support extensive plant life.' },
  { id: 'cold-adapted-flora', n: 177, name: 'Cold-Adapted Flora', category: 'Flora & Vegetation', description: 'Vegetation remains active near freezing temperatures.' },
  { id: 'heat-adapted-flora', n: 178, name: 'Heat-Adapted Flora', category: 'Flora & Vegetation', description: 'Plants tolerate temperatures dangerous to many animals.' },
  { id: 'night-blooming-flora', n: 179, name: 'Night-Blooming Flora', category: 'Flora & Vegetation', description: 'Many plants become active only after dark.' },
  { id: 'chemical-defense-flora', n: 180, name: 'Chemical-Defense Flora', category: 'Flora & Vegetation', description: 'Irritating or toxic compounds are common in vegetation.' },
  { id: 'large-grazers', n: 181, name: 'Large Grazers', category: 'Fauna & Animal Hazards', description: 'Herd animals dominate open terrain.' },
  { id: 'burrowing-megafauna', n: 182, name: 'Burrowing Megafauna', category: 'Fauna & Animal Hazards', description: 'Very large animals live beneath the surface.' },
  { id: 'aerial-megafauna', n: 183, name: 'Aerial Megafauna', category: 'Fauna & Animal Hazards', description: 'Huge flying organisms are common enough to affect travel.' },
  { id: 'marine-megafauna', n: 184, name: 'Marine Megafauna', category: 'Fauna & Animal Hazards', description: 'Giant ocean animals are regularly encountered.' },
  { id: 'pack-predators', n: 185, name: 'Pack Predators', category: 'Fauna & Animal Hazards', description: 'Coordinated hunters pose local danger.' },
  { id: 'ambush-predators', n: 186, name: 'Ambush Predators', category: 'Fauna & Animal Hazards', description: 'Camouflaged predators favor close-range attacks.' },
  { id: 'venomous-fauna', n: 187, name: 'Venomous Fauna', category: 'Fauna & Animal Hazards', description: 'Toxic bites/stings are common.' },
  { id: 'armored-fauna', n: 188, name: 'Armored Fauna', category: 'Fauna & Animal Hazards', description: 'Many animals evolved heavy natural protection.' },
  { id: 'electrosensitive-fauna', n: 189, name: 'Electrosensitive Fauna', category: 'Fauna & Animal Hazards', description: 'Animals detect electrical fields and machinery.' },
  { id: 'electrogenic-fauna', n: 190, name: 'Electrogenic Fauna', category: 'Fauna & Animal Hazards', description: 'Some animals naturally generate electrical discharges.' },
  { id: 'acidic-defensive-secretions', n: 191, name: 'Acidic Defensive Secretions', category: 'Fauna & Animal Hazards', description: 'Native animals use corrosive chemicals defensively.' },
  { id: 'spore-carrying-fauna', n: 192, name: 'Spore-Carrying Fauna', category: 'Fauna & Animal Hazards', description: 'Animals spread fungal or parasitic spores.' },
  { id: 'highly-curious-wildlife', n: 193, name: 'Highly Curious Wildlife', category: 'Fauna & Animal Hazards', description: 'Native animals frequently approach people and equipment.' },
  { id: 'tool-using-wildlife', n: 194, name: 'Tool-Using Wildlife', category: 'Fauna & Animal Hazards', description: 'Some non-sapient animals manipulate simple objects.' },
  { id: 'night-active-fauna', n: 195, name: 'Night-Active Fauna', category: 'Fauna & Animal Hazards', description: 'Most significant animal activity occurs after dark.' },
  { id: 'day-active-fauna', n: 196, name: 'Day-Active Fauna', category: 'Fauna & Animal Hazards', description: 'Major wildlife activity peaks during daylight.' },
  { id: 'seasonal-breeding-aggression', n: 197, name: 'Seasonal Breeding Aggression', category: 'Fauna & Animal Hazards', description: 'Normally calm animals become dangerous during mating periods.' },
  { id: 'mass-nesting-events', n: 198, name: 'Mass Nesting Events', category: 'Fauna & Animal Hazards', description: 'Huge numbers of animals gather in predictable locations.' },
  { id: 'long-distance-migrators', n: 199, name: 'Long-Distance Migrators', category: 'Fauna & Animal Hazards', description: 'Some species cross continents or oceans seasonally.' },
  { id: 'urban-adapted-wildlife', n: 200, name: 'Urban-Adapted Wildlife', category: 'Fauna & Animal Hazards', description: 'Native animals thrive around settlements.' },
  { id: 'high-pathogen-load', n: 201, name: 'High Pathogen Load', category: 'Biological & Health Hazards', description: 'Local microbes create frequent minor illness risk.' },
  { id: 'low-pathogen-load', n: 202, name: 'Low Pathogen Load', category: 'Biological & Health Hazards', description: 'Native disease pressure is unusually low.' },
  { id: 'cross-species-pathogen-risk', n: 203, name: 'Cross-Species Pathogen Risk', category: 'Biological & Health Hazards', description: 'Some native microbes can affect off-world species.' },
  { id: 'strong-allergen-presence', n: 204, name: 'Strong Allergen Presence', category: 'Biological & Health Hazards', description: 'Pollen/spores trigger common reactions.' },
  { id: 'skin-irritating-flora', n: 205, name: 'Skin-Irritating Flora', category: 'Biological & Health Hazards', description: 'Contact with local vegetation can cause rashes or burns.' },
  { id: 'parasitic-insects', n: 206, name: 'Parasitic Insects', category: 'Biological & Health Hazards', description: 'Biting or egg-laying small fauna require precautions.' },
  { id: 'waterborne-parasites', n: 207, name: 'Waterborne Parasites', category: 'Biological & Health Hazards', description: 'Untreated natural water carries biological risk.' },
  { id: 'foodborne-toxin-risk', n: 208, name: 'Foodborne Toxin Risk', category: 'Biological & Health Hazards', description: 'Some edible-looking organisms contain dangerous compounds.' },
  { id: 'rapid-food-spoilage', n: 209, name: 'Rapid Food Spoilage', category: 'Biological & Health Hazards', description: 'Local microbes degrade stored food quickly.' },
  { id: 'slow-food-spoilage', n: 210, name: 'Slow Food Spoilage', category: 'Biological & Health Hazards', description: 'Environmental conditions preserve food naturally.' },
  { id: 'native-antibiotic-organisms', n: 211, name: 'Native Antibiotic Organisms', category: 'Biological & Health Hazards', description: 'Some local species naturally suppress infection.' },
  { id: 'medicinal-biodiversity', n: 212, name: 'Medicinal Biodiversity', category: 'Biological & Health Hazards', description: 'Many organisms have useful pharmaceutical compounds.' },
  { id: 'neurotoxic-spores', n: 213, name: 'Neurotoxic Spores', category: 'Biological & Health Hazards', description: 'Rare fungal blooms can impair coordination or perception.' },
  { id: 'hallucinogenic-pollen', n: 214, name: 'Hallucinogenic Pollen', category: 'Biological & Health Hazards', description: 'Seasonal exposure can alter perception.' },
  { id: 'sleep-disrupting-ecology', n: 215, name: 'Sleep-Disrupting Ecology', category: 'Biological & Health Hazards', description: 'Local sounds/chemicals interfere with normal rest.' },
  { id: 'fatigue-inducing-heat-biology', n: 216, name: 'Fatigue-Inducing Heat Biology', category: 'Biological & Health Hazards', description: 'Heat plus native allergens increases exhaustion.' },
  { id: 'highly-sterile-terrain', n: 217, name: 'Highly Sterile Terrain', category: 'Biological & Health Hazards', description: 'Some regions support almost no microbial life.' },
  { id: 'corrosive-biological-films', n: 218, name: 'Corrosive Biological Films', category: 'Biological & Health Hazards', description: 'Microbial mats can damage exposed materials.' },
  { id: 'bioelectric-microorganisms', n: 219, name: 'Bioelectric Microorganisms', category: 'Biological & Health Hazards', description: 'Dense colonies generate weak electrical fields.' },
  { id: 'rapid-wound-infection', n: 220, name: 'Rapid Wound Infection', category: 'Biological & Health Hazards', description: 'Open injuries require faster treatment than usual.' },
  { id: 'metal-rich-crust', n: 221, name: 'Metal-Rich Crust', category: 'Resources & Geochemical Wealth', description: 'Useful ores are abundant and accessible.' },
  { id: 'metal-poor-crust', n: 222, name: 'Metal-Poor Crust', category: 'Resources & Geochemical Wealth', description: 'Industrial metals are unusually scarce.' },
  { id: 'rare-earth-abundance', n: 223, name: 'Rare-Earth Abundance', category: 'Resources & Geochemical Wealth', description: 'High-value technological minerals are common.' },
  { id: 'rare-earth-scarcity', n: 224, name: 'Rare-Earth Scarcity', category: 'Resources & Geochemical Wealth', description: 'Electronics/manufacturing inputs are difficult to source locally.' },
  { id: 'hydrocarbon-rich-basins', n: 225, name: 'Hydrocarbon-Rich Basins', category: 'Resources & Geochemical Wealth', description: 'Natural fuels and organic deposits are abundant.' },
  { id: 'gemstone-abundance', n: 226, name: 'Gemstone Abundance', category: 'Resources & Geochemical Wealth', description: 'Valuable crystalline deposits are widespread.' },
  { id: 'radioactive-mineral-wealth', n: 227, name: 'Radioactive Mineral Wealth', category: 'Resources & Geochemical Wealth', description: 'Fissionable materials occur in rich deposits.' },
  { id: 'geothermal-energy-rich', n: 228, name: 'Geothermal Energy Rich', category: 'Resources & Geochemical Wealth', description: 'Heat energy is easy to exploit.' },
  { id: 'wind-energy-rich', n: 229, name: 'Wind-Energy Rich', category: 'Resources & Geochemical Wealth', description: 'Persistent winds favor power generation.' },
  { id: 'solar-energy-rich', n: 230, name: 'Solar-Energy Rich', category: 'Resources & Geochemical Wealth', description: 'Surface illumination strongly favors solar collection.' },
  { id: 'hydroelectric-potential', n: 231, name: 'Hydroelectric Potential', category: 'Resources & Geochemical Wealth', description: 'Rivers and elevation changes make water power easy.' },
  { id: 'freshwater-scarcity', n: 232, name: 'Freshwater Scarcity', category: 'Resources & Geochemical Wealth', description: 'Clean water is a strategic resource.' },
  { id: 'freshwater-abundance', n: 233, name: 'Freshwater Abundance', category: 'Resources & Geochemical Wealth', description: 'Potable water is easy to obtain.' },
  { id: 'fertile-soils', n: 234, name: 'Fertile Soils', category: 'Resources & Geochemical Wealth', description: 'Agriculture requires relatively little intervention.' },
  { id: 'poor-soils', n: 235, name: 'Poor Soils', category: 'Resources & Geochemical Wealth', description: 'Farming depends on treatment, imports, or hydroponics.' },
  { id: 'highly-productive-seas', n: 236, name: 'Highly Productive Seas', category: 'Resources & Geochemical Wealth', description: 'Fisheries and marine agriculture are exceptionally strong.' },
  { id: 'low-nutrient-seas', n: 237, name: 'Low-Nutrient Seas', category: 'Resources & Geochemical Wealth', description: 'Ocean ecosystems support limited biomass.' },
  { id: 'industrial-salt-abundance', n: 238, name: 'Industrial Salt Abundance', category: 'Resources & Geochemical Wealth', description: 'Useful salts/minerals are easy to extract.' },
  { id: 'silica-abundance', n: 239, name: 'Silica Abundance', category: 'Resources & Geochemical Wealth', description: 'Glass/ceramic materials are especially accessible.' },
  { id: 'strategic-resource-hotspots', n: 240, name: 'Strategic Resource Hotspots', category: 'Resources & Geochemical Wealth', description: 'A few regions contain disproportionately valuable deposits.' },
  { id: 'extremely-rugged-terrain', n: 241, name: 'Extremely Rugged Terrain', category: 'Terrain & Surface Navigation', description: 'Overland routes are slow and difficult.' },
  { id: 'broad-flatlands', n: 242, name: 'Broad Flatlands', category: 'Terrain & Surface Navigation', description: 'Ground vehicles can travel long distances easily.' },
  { id: 'broken-ridge-country', n: 243, name: 'Broken Ridge Country', category: 'Terrain & Surface Navigation', description: 'Repeated ridges and valleys complicate direct travel.' },
  { id: 'frequent-cliffs', n: 244, name: 'Frequent Cliffs', category: 'Terrain & Surface Navigation', description: 'Vertical terrain barriers are common.' },
  { id: 'deep-ravines', n: 245, name: 'Deep Ravines', category: 'Terrain & Surface Navigation', description: 'Surface routes must cross or detour around major cuts.' },
  { id: 'natural-land-bridges', n: 246, name: 'Natural Land Bridges', category: 'Terrain & Surface Navigation', description: 'Erosion creates useful elevated crossings.' },
  { id: 'extensive-cave-entrances', n: 247, name: 'Extensive Cave Entrances', category: 'Terrain & Surface Navigation', description: 'Underground routes are easily accessible.' },
  { id: 'unstable-scree-slopes', n: 248, name: 'Unstable Scree Slopes', category: 'Terrain & Surface Navigation', description: 'Loose rock makes climbing hazardous.' },
  { id: 'soft-mud-terrain', n: 249, name: 'Soft Mud Terrain', category: 'Terrain & Surface Navigation', description: 'Heavy vehicles can become bogged down.' },
  { id: 'hardpan-surface', n: 250, name: 'Hardpan Surface', category: 'Terrain & Surface Navigation', description: 'Dry compact ground supports easy vehicle travel.' },
  { id: 'loose-dune-terrain', n: 251, name: 'Loose Dune Terrain', category: 'Terrain & Surface Navigation', description: 'Fine sand makes traction difficult.' },
  { id: 'sharp-rock-fields', n: 252, name: 'Sharp Rock Fields', category: 'Terrain & Surface Navigation', description: 'Foot and tire damage are common without protection.' },
  { id: 'thick-ground-vegetation', n: 253, name: 'Thick Ground Vegetation', category: 'Terrain & Surface Navigation', description: 'Travel speed is reduced without cleared routes.' },
  { id: 'natural-road-corridors', n: 254, name: 'Natural Road Corridors', category: 'Terrain & Surface Navigation', description: 'Long valleys/plains provide easy movement.' },
  { id: 'seasonal-impassability', n: 255, name: 'Seasonal Impassability', category: 'Terrain & Surface Navigation', description: 'Some routes disappear during weather cycles.' },
  { id: 'frequent-sinkholes', n: 256, name: 'Frequent Sinkholes', category: 'Terrain & Surface Navigation', description: 'Hidden ground collapse threatens travel.' },
  { id: 'floating-ice-hazards', n: 257, name: 'Floating Ice Hazards', category: 'Terrain & Surface Navigation', description: 'Water routes change as ice shifts.' },
  { id: 'shallow-water-travel', n: 258, name: 'Shallow-Water Travel', category: 'Terrain & Surface Navigation', description: 'Boats and amphibious vehicles outperform roads.' },
  { id: 'vertical-settlement-geography', n: 259, name: 'Vertical Settlement Geography', category: 'Terrain & Surface Navigation', description: 'Important sites are separated by major elevation.' },
  { id: 'island-hopping-geography', n: 260, name: 'Island-Hopping Geography', category: 'Terrain & Surface Navigation', description: 'Short water crossings dominate regional travel.' },
  { id: 'bright-star', n: 261, name: 'Bright Star', category: 'Light, Orbit & Sky', description: 'Daylight is unusually intense.' },
  { id: 'dim-star', n: 262, name: 'Dim Star', category: 'Light, Orbit & Sky', description: 'Daylight remains muted even at noon.' },
  { id: 'red-tinted-sunlight', n: 263, name: 'Red-Tinted Sunlight', category: 'Light, Orbit & Sky', description: 'Stellar spectrum gives landscapes a warm cast.' },
  { id: 'blue-white-sunlight', n: 264, name: 'Blue-White Sunlight', category: 'Light, Orbit & Sky', description: 'Stellar spectrum produces harsh pale illumination.' },
  { id: 'multiple-suns-visible', n: 265, name: 'Multiple Suns Visible', category: 'Light, Orbit & Sky', description: 'The system has more than one prominent stellar light source.' },
  { id: 'frequent-eclipses', n: 266, name: 'Frequent Eclipses', category: 'Light, Orbit & Sky', description: 'Moon/orbit geometry produces regular eclipses.' },
  { id: 'long-twilight', n: 267, name: 'Long Twilight', category: 'Light, Orbit & Sky', description: 'Sunrise and sunset last unusually long.' },
  { id: 'very-dark-nights', n: 268, name: 'Very Dark Nights', category: 'Light, Orbit & Sky', description: 'Little moonlight or atmospheric glow exists.' },
  { id: 'bright-nights', n: 269, name: 'Bright Nights', category: 'Light, Orbit & Sky', description: 'Large moons or rings provide strong nighttime illumination.' },
  { id: 'visible-planetary-rings', n: 270, name: 'Visible Planetary Rings', category: 'Light, Orbit & Sky', description: 'Rings dominate portions of the sky.' },
  { id: 'ring-shadow-seasons', n: 271, name: 'Ring Shadow Seasons', category: 'Light, Orbit & Sky', description: 'Planetary rings periodically shade large regions.' },
  { id: 'large-nearby-moon', n: 272, name: 'Large Nearby Moon', category: 'Light, Orbit & Sky', description: 'A moon appears enormous in the sky.' },
  { id: 'multiple-visible-moons', n: 273, name: 'Multiple Visible Moons', category: 'Light, Orbit & Sky', description: 'Several moons are routinely visible at once.' },
  { id: 'frequent-meteor-showers', n: 274, name: 'Frequent Meteor Showers', category: 'Light, Orbit & Sky', description: 'Orbital debris creates regular meteor activity.' },
  { id: 'occasional-major-impacts', n: 275, name: 'Occasional Major Impacts', category: 'Light, Orbit & Sky', description: 'Small-to-medium impacts are a recognized natural hazard.' },
  { id: 'dense-orbital-debris', n: 276, name: 'Dense Orbital Debris', category: 'Light, Orbit & Sky', description: 'Natural or artificial debris complicates space operations.' },
  { id: 'stable-orbit-environment', n: 277, name: 'Stable Orbit Environment', category: 'Light, Orbit & Sky', description: 'Orbital hazards are unusually low.' },
  { id: 'long-year', n: 278, name: 'Long Year', category: 'Light, Orbit & Sky', description: 'Seasonal/orbital cycles take many standard years.' },
  { id: 'short-year', n: 279, name: 'Short Year', category: 'Light, Orbit & Sky', description: 'The planet completes its orbit quickly.' },
  { id: 'highly-eccentric-orbit', n: 280, name: 'Highly Eccentric Orbit', category: 'Light, Orbit & Sky', description: 'Distance from the star changes greatly through the year.' },
  { id: 'permanent-rainbow-halos', n: 281, name: 'Permanent Rainbow Halos', category: 'Unusual Natural Phenomena', description: 'Atmospheric crystals frequently produce colored arcs.' },
  { id: 'sound-carrying-atmosphere', n: 282, name: 'Sound-Carrying Atmosphere', category: 'Unusual Natural Phenomena', description: 'Voices and machinery can be heard unusually far away.' },
  { id: 'sound-dampening-atmosphere', n: 283, name: 'Sound-Dampening Atmosphere', category: 'Unusual Natural Phenomena', description: 'Natural conditions absorb sound quickly.' },
  { id: 'mirage-prone-air', n: 284, name: 'Mirage-Prone Air', category: 'Unusual Natural Phenomena', description: 'Refraction creates frequent visual distortions.' },
  { id: 'fata-morgana-zones', n: 285, name: 'Fata Morgana Zones', category: 'Unusual Natural Phenomena', description: 'Complex horizon mirages are common.' },
  { id: 'glow-fog', n: 286, name: 'Glow-Fog', category: 'Unusual Natural Phenomena', description: 'Mist contains naturally luminescent organisms or particles.' },
  { id: 'magnetic-sand', n: 287, name: 'Magnetic Sand', category: 'Unusual Natural Phenomena', description: 'Beaches/deserts visibly shift under strong magnetic fields.' },
  { id: 'singing-dunes', n: 288, name: 'Singing Dunes', category: 'Unusual Natural Phenomena', description: 'Wind-driven sand produces audible tones.' },
  { id: 'resonant-caves', n: 289, name: 'Resonant Caves', category: 'Unusual Natural Phenomena', description: 'Large cavern systems amplify and shape sound dramatically.' },
  { id: 'crystal-resonance', n: 290, name: 'Crystal Resonance', category: 'Unusual Natural Phenomena', description: 'Mineral formations vibrate audibly under wind or seismic stress.' },
  { id: 'natural-plasma-glows', n: 291, name: 'Natural Plasma Glows', category: 'Unusual Natural Phenomena', description: 'Upper-atmosphere plasma events are visible from the ground.' },
  { id: 'floating-pollen-clouds', n: 292, name: 'Floating Pollen Clouds', category: 'Unusual Natural Phenomena', description: 'Dense biological clouds drift like weather systems.' },
  { id: 'mineral-rain', n: 293, name: 'Mineral Rain', category: 'Unusual Natural Phenomena', description: 'Rare storms deposit fine crystalline particles.' },
  { id: 'colored-snow', n: 294, name: 'Colored Snow', category: 'Unusual Natural Phenomena', description: 'Pigments/minerals tint seasonal snowfields.' },
  { id: 'black-rain', n: 295, name: 'Black Rain', category: 'Unusual Natural Phenomena', description: 'Soot/mineral-rich precipitation occasionally occurs.' },
  { id: 'heat-lightning-nights', n: 296, name: 'Heat Lightning Nights', category: 'Unusual Natural Phenomena', description: 'Distant electrical storms illuminate skies without local rain.' },
  { id: 'persistent-ground-glow', n: 297, name: 'Persistent Ground Glow', category: 'Unusual Natural Phenomena', description: 'Biochemistry or minerals create faint nighttime luminescence.' },
  { id: 'natural-compass-failure-zones', n: 298, name: 'Natural Compass Failure Zones', category: 'Unusual Natural Phenomena', description: 'Local geology overwhelms magnetic navigation.' },
  { id: 'gravity-defying-visual-illusions', n: 299, name: 'Gravity-Defying Visual Illusions', category: 'Unusual Natural Phenomena', description: 'Terrain and atmosphere produce misleading slope/horizon perception.' },
  { id: 'periodic-sky-darkening', n: 300, name: 'Periodic Sky Darkening', category: 'Unusual Natural Phenomena', description: 'Orbital dust or biological blooms temporarily reduce daylight.' },
];

export const MODIFIER_CATEGORIES: ModifierCategory[] = [
  'Atmosphere & Air',
  'Weather & Storms',
  'Temperature & Climate',
  'Gravity & Physical Conditions',
  'Geology & Seismic Activity',
  'Magnetic, Electrical & Radiation',
  'Water & Hydrology',
  'Ecology & Biosphere',
  'Flora & Vegetation',
  'Fauna & Animal Hazards',
  'Biological & Health Hazards',
  'Resources & Geochemical Wealth',
  'Terrain & Surface Navigation',
  'Light, Orbit & Sky',
  'Unusual Natural Phenomena',
];
