/**
 * PROFESSIONS — pure authored data, no logic.
 *
 * 250 working lives, each biasing three or four skills and three or four
 * attributes. A profession is a bias, never a class: two captains with the
 * same trade still roll very differently, because the bias only leans on the
 * ordinary exposure roll rather than replacing it.
 *
 * `minAge` keeps a life plausible — nobody is a chief engineer at nineteen.
 */

import type { AttributeKey, CharacterRole, SkillKey } from '../engine/types';

export type ProfessionCategory =
  | 'Medical & Care'
  | 'Engineering & Repair'
  | 'Spaceflight & Navigation'
  | 'Security & Law'
  | 'Military & Defense'
  | 'Education & Academia'
  | 'Science & Research'
  | 'Computing & Data'
  | 'Mining & Extraction'
  | 'Construction & Trades'
  | 'Agriculture & Food'
  | 'Trade & Commerce'
  | 'Finance & Administration'
  | 'Government & Civic'
  | 'Transportation & Logistics'
  | 'Hospitality & Service'
  | 'Media & Communication'
  | 'Arts & Performance'
  | 'Exploration & Fieldwork'
  | 'Salvage & Recovery'
  | 'Criminal & Underground'
  | 'Emergency & Disaster'
  | 'Manufacturing & Production'
  | 'Weapons & Combat Trades'
  | 'Faith, Counseling & Community';

export interface ProfessionEntry {
  id: string;
  name: string;
  category: ProfessionCategory;
  /** The shipboard role this trade most naturally becomes. */
  role: CharacterRole;
  /** Youngest age at which this life is plausible. */
  minAge: number;
  skillBias: Partial<Record<SkillKey, number>>;
  attributeBias: Partial<Record<AttributeKey, number>>;
}

export const PROFESSIONS: ProfessionEntry[] = [
  {
    id: 'field-medic',
    name: 'Field Medic',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'emergency-physician',
    name: 'Emergency Physician',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'trauma-surgeon',
    name: 'Trauma Surgeon',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'general-practitioner',
    name: 'General Practitioner',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'diagnostic-technician',
    name: 'Diagnostic Technician',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'medical-researcher',
    name: 'Medical Researcher',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'rural-clinician',
    name: 'Rural Clinician',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'surgical-assistant',
    name: 'Surgical Assistant',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'rehabilitation-specialist',
    name: 'Rehabilitation Specialist',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'community-health-worker',
    name: 'Community Health Worker',
    category: 'Medical & Care',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, medicalDiagnostics: 12, surgery: 9, medicalResearch: 7 },
    attributeBias: { learning: 3, reasoning: 2, steadiness: 2, socialAwareness: 1 },
  },
  {
    id: 'mechanical-engineer',
    name: 'Mechanical Engineer',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'electrical-engineer',
    name: 'Electrical Engineer',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'maintenance-technician',
    name: 'Maintenance Technician',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'industrial-mechanic',
    name: 'Industrial Mechanic',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'systems-repair-specialist',
    name: 'Systems Repair Specialist',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'power-grid-technician',
    name: 'Power-Grid Technician',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'factory-engineer',
    name: 'Factory Engineer',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'vehicle-mechanic',
    name: 'Vehicle Mechanic',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'instrumentation-technician',
    name: 'Instrumentation Technician',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'reliability-engineer',
    name: 'Reliability Engineer',
    category: 'Engineering & Repair',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, computers: 9 },
    attributeBias: { reasoning: 3, learning: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'orbital-pilot',
    name: 'Orbital Pilot',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'freight-pilot',
    name: 'Freight Pilot',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'shuttle-pilot',
    name: 'Shuttle Pilot',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'navigation-officer',
    name: 'Navigation Officer',
    category: 'Spaceflight & Navigation',
    role: 'navigator',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'flight-instructor',
    name: 'Flight Instructor',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'survey-pilot',
    name: 'Survey Pilot',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'rescue-pilot',
    name: 'Rescue Pilot',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'atmospheric-pilot',
    name: 'Atmospheric Pilot',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'docking-specialist',
    name: 'Docking Specialist',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'flight-dispatcher',
    name: 'Flight Dispatcher',
    category: 'Spaceflight & Navigation',
    role: 'pilot',
    minAge: 18,
    skillBias: { piloting: 16, navigation: 12, computers: 9 },
    attributeBias: { handEye: 3, perception: 2, decisionMaking: 2, composure: 1 },
  },
  {
    id: 'municipal-officer',
    name: 'Municipal Officer',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'transit-security-officer',
    name: 'Transit Security Officer',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'investigator',
    name: 'Investigator',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'corrections-officer',
    name: 'Corrections Officer',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'protective-detail-agent',
    name: 'Protective Detail Agent',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'border-inspector',
    name: 'Border Inspector',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'court-bailiff',
    name: 'Court Bailiff',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'campus-security-officer',
    name: 'Campus Security Officer',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'fraud-investigator',
    name: 'Fraud Investigator',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'public-safety-supervisor',
    name: 'Public Safety Supervisor',
    category: 'Security & Law',
    role: 'gunner',
    minAge: 34,
    skillBias: { firearms: 16, closeQuarters: 12, persuasion: 9 },
    attributeBias: { perception: 3, decisionMaking: 2, composure: 2, leadership: 1 },
  },
  {
    id: 'infantry-soldier',
    name: 'Infantry Soldier',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'combat-engineer',
    name: 'Combat Engineer',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'ship-gunner',
    name: 'Ship Gunner',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'reconnaissance-scout',
    name: 'Reconnaissance Scout',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'military-medic',
    name: 'Military Medic',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'logistics-nco',
    name: 'Logistics NCO',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'armor-crewman',
    name: 'Armor Crewman',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'defense-instructor',
    name: 'Defense Instructor',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'base-operations-specialist',
    name: 'Base Operations Specialist',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 18,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'veteran-officer',
    name: 'Veteran Officer',
    category: 'Military & Defense',
    role: 'gunner',
    minAge: 34,
    skillBias: { firearms: 16, closeQuarters: 12, shipWeapons: 9, navigation: 7 },
    attributeBias: { discipline: 3, resilience: 2, decisionMaking: 2, leadership: 1 },
  },
  {
    id: 'district-teacher',
    name: 'District Teacher',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'university-lecturer',
    name: 'University Lecturer',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'technical-instructor',
    name: 'Technical Instructor',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'school-administrator',
    name: 'School Administrator',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 34,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'history-professor',
    name: 'History Professor',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 34,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'science-teacher',
    name: 'Science Teacher',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'vocational-trainer',
    name: 'Vocational Trainer',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'academic-researcher',
    name: 'Academic Researcher',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'archivist',
    name: 'Archivist',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'private-tutor',
    name: 'Private Tutor',
    category: 'Education & Academia',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, medicalResearch: 9 },
    attributeBias: { learning: 3, memory: 2, charisma: 2, discipline: 1 },
  },
  {
    id: 'planetary-scientist',
    name: 'Planetary Scientist',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'biologist',
    name: 'Biologist',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'chemist',
    name: 'Chemist',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'physicist',
    name: 'Physicist',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'geologist',
    name: 'Geologist',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'ecologist',
    name: 'Ecologist',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'atmospheric-researcher',
    name: 'Atmospheric Researcher',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'materials-scientist',
    name: 'Materials Scientist',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'field-researcher',
    name: 'Field Researcher',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'laboratory-analyst',
    name: 'Laboratory Analyst',
    category: 'Science & Research',
    role: 'technician',
    minAge: 18,
    skillBias: { medicalResearch: 16, computers: 12, exploration: 9, navigation: 7 },
    attributeBias: { learning: 3, reasoning: 2, memory: 2, evaluation: 1 },
  },
  {
    id: 'software-developer',
    name: 'Software Developer',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'network-administrator',
    name: 'Network Administrator',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 34,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'cybersecurity-analyst',
    name: 'Cybersecurity Analyst',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'database-administrator',
    name: 'Database Administrator',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 34,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'systems-architect',
    name: 'Systems Architect',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'automation-technician',
    name: 'Automation Technician',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'digital-forensics-analyst',
    name: 'Digital Forensics Analyst',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'communications-engineer',
    name: 'Communications Engineer',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'it-support-specialist',
    name: 'IT Support Specialist',
    category: 'Computing & Data',
    role: 'technician',
    minAge: 18,
    skillBias: { computers: 16, electricalEngineering: 12, lockpicking: 9 },
    attributeBias: { reasoning: 3, learning: 2, memory: 2, discipline: 1 },
  },
  {
    id: 'deep-shaft-miner',
    name: 'Deep-Shaft Miner',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'surface-miner',
    name: 'Surface Miner',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'drilling-operator',
    name: 'Drilling Operator',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'blasting-technician',
    name: 'Blasting Technician',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'ore-surveyor',
    name: 'Ore Surveyor',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'quarry-foreman',
    name: 'Quarry Foreman',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 34,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'extraction-engineer',
    name: 'Extraction Engineer',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'tunnel-worker',
    name: 'Tunnel Worker',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'mineral-prospector',
    name: 'Mineral Prospector',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'mine-safety-inspector',
    name: 'Mine Safety Inspector',
    category: 'Mining & Extraction',
    role: 'scavenger',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, explosives: 12, scavenging: 9, exploration: 7 },
    attributeBias: { strength: 3, endurance: 2, perception: 2, discipline: 1 },
  },
  {
    id: 'carpenter',
    name: 'Carpenter',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'electrician',
    name: 'Electrician',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'plumber',
    name: 'Plumber',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'welder',
    name: 'Welder',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'heavy-equipment-operator',
    name: 'Heavy Equipment Operator',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'structural-technician',
    name: 'Structural Technician',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'rigger',
    name: 'Rigger',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'fabricator',
    name: 'Fabricator',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'building-inspector',
    name: 'Building Inspector',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'construction-foreman',
    name: 'Construction Foreman',
    category: 'Construction & Trades',
    role: 'engineer',
    minAge: 34,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, scavenging: 9 },
    attributeBias: { strength: 3, proprioception: 2, steadiness: 2, discipline: 1 },
  },
  {
    id: 'farmer',
    name: 'Farmer',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'hydroponics-grower',
    name: 'Hydroponics Grower',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'livestock-keeper',
    name: 'Livestock Keeper',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'agricultural-technician',
    name: 'Agricultural Technician',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'irrigation-specialist',
    name: 'Irrigation Specialist',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'food-processor',
    name: 'Food Processor',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'chef',
    name: 'Chef',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'baker',
    name: 'Baker',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'butcher',
    name: 'Butcher',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 18,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'agricultural-cooperative-manager',
    name: 'Agricultural Cooperative Manager',
    category: 'Agriculture & Food',
    role: 'crew',
    minAge: 34,
    skillBias: { cooking: 16, mechanicalEngineering: 12, scavenging: 9 },
    attributeBias: { endurance: 3, perception: 2, discipline: 2, memory: 1 },
  },
  {
    id: 'market-trader',
    name: 'Market Trader',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'import-broker',
    name: 'Import Broker',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'wholesale-buyer',
    name: 'Wholesale Buyer',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'shopkeeper',
    name: 'Shopkeeper',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'commercial-salesperson',
    name: 'Commercial Salesperson',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'procurement-officer',
    name: 'Procurement Officer',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'auctioneer',
    name: 'Auctioneer',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'commodity-broker',
    name: 'Commodity Broker',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'supply-contractor',
    name: 'Supply Contractor',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'merchant-representative',
    name: 'Merchant Representative',
    category: 'Trade & Commerce',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, persuasion: 12, computers: 9 },
    attributeBias: { charisma: 3, evaluation: 2, socialAwareness: 2, memory: 1 },
  },
  {
    id: 'accountant',
    name: 'Accountant',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'loan-officer',
    name: 'Loan Officer',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'budget-analyst',
    name: 'Budget Analyst',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'insurance-adjuster',
    name: 'Insurance Adjuster',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'payroll-administrator',
    name: 'Payroll Administrator',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 34,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'tax-examiner',
    name: 'Tax Examiner',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'bank-clerk',
    name: 'Bank Clerk',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'operations-administrator',
    name: 'Operations Administrator',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 34,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'compliance-officer',
    name: 'Compliance Officer',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'financial-planner',
    name: 'Financial Planner',
    category: 'Finance & Administration',
    role: 'crew',
    minAge: 18,
    skillBias: { negotiation: 16, computers: 12, persuasion: 9 },
    attributeBias: { reasoning: 3, memory: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'civil-administrator',
    name: 'Civil Administrator',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 34,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'permit-officer',
    name: 'Permit Officer',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'city-planner',
    name: 'City Planner',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'public-works-coordinator',
    name: 'Public Works Coordinator',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'diplomatic-aide',
    name: 'Diplomatic Aide',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'legislative-staffer',
    name: 'Legislative Staffer',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'records-officer',
    name: 'Records Officer',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'community-liaison',
    name: 'Community Liaison',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'emergency-manager',
    name: 'Emergency Manager',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 34,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'local-magistrate',
    name: 'Local Magistrate',
    category: 'Government & Civic',
    role: 'crew',
    minAge: 34,
    skillBias: { persuasion: 16, negotiation: 12, computers: 9 },
    attributeBias: { leadership: 3, charisma: 2, socialAwareness: 2, decisionMaking: 1 },
  },
  {
    id: 'freight-dispatcher',
    name: 'Freight Dispatcher',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'long-haul-driver',
    name: 'Long-Haul Driver',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'rail-operator',
    name: 'Rail Operator',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'port-coordinator',
    name: 'Port Coordinator',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'warehouse-supervisor',
    name: 'Warehouse Supervisor',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 34,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'courier',
    name: 'Courier',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'route-planner',
    name: 'Route Planner',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'cargo-handler',
    name: 'Cargo Handler',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'fleet-manager',
    name: 'Fleet Manager',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 34,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'transit-controller',
    name: 'Transit Controller',
    category: 'Transportation & Logistics',
    role: 'pilot',
    minAge: 18,
    skillBias: { navigation: 16, piloting: 12, mechanicalEngineering: 9 },
    attributeBias: { perception: 3, memory: 2, decisionMaking: 2, discipline: 1 },
  },
  {
    id: 'innkeeper',
    name: 'Innkeeper',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'restaurant-manager',
    name: 'Restaurant Manager',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 34,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'bartender',
    name: 'Bartender',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'server',
    name: 'Server',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'hotel-clerk',
    name: 'Hotel Clerk',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'concierge',
    name: 'Concierge',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'caterer',
    name: 'Caterer',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'event-coordinator',
    name: 'Event Coordinator',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'housekeeping-supervisor',
    name: 'Housekeeping Supervisor',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 34,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'tour-guide',
    name: 'Tour Guide',
    category: 'Hospitality & Service',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, cooking: 9 },
    attributeBias: { charisma: 3, socialAwareness: 2, composure: 2, memory: 1 },
  },
  {
    id: 'reporter',
    name: 'Reporter',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'broadcaster',
    name: 'Broadcaster',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'editor',
    name: 'Editor',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'photographer',
    name: 'Photographer',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'documentarian',
    name: 'Documentarian',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'public-relations-officer',
    name: 'Public Relations Officer',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'copywriter',
    name: 'Copywriter',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'community-radio-host',
    name: 'Community Radio Host',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'investigative-journalist',
    name: 'Investigative Journalist',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'translator',
    name: 'Translator',
    category: 'Media & Communication',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12, negotiation: 9 },
    attributeBias: { charisma: 3, perception: 2, memory: 2, socialAwareness: 1 },
  },
  {
    id: 'musician',
    name: 'Musician',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'actor',
    name: 'Actor',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'painter',
    name: 'Painter',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'sculptor',
    name: 'Sculptor',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'stage-technician',
    name: 'Stage Technician',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'dancer',
    name: 'Dancer',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'illustrator',
    name: 'Illustrator',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'writer',
    name: 'Writer',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'street-performer',
    name: 'Street Performer',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'art-conservator',
    name: 'Art Conservator',
    category: 'Arts & Performance',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, computers: 12 },
    attributeBias: { charisma: 3, handEye: 2, memory: 2, composure: 1 },
  },
  {
    id: 'wilderness-guide',
    name: 'Wilderness Guide',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'surveyor',
    name: 'Surveyor',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'expedition-scout',
    name: 'Expedition Scout',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'cartographer',
    name: 'Cartographer',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'search-and-rescue-worker',
    name: 'Search-and-Rescue Worker',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'ruin-explorer',
    name: 'Ruin Explorer',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'field-archaeologist',
    name: 'Field Archaeologist',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'environmental-surveyor',
    name: 'Environmental Surveyor',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'cave-explorer',
    name: 'Cave Explorer',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'remote-outpost-ranger',
    name: 'Remote Outpost Ranger',
    category: 'Exploration & Fieldwork',
    role: 'scavenger',
    minAge: 18,
    skillBias: { exploration: 16, scavenging: 12, navigation: 9, firstAid: 7 },
    attributeBias: { perception: 3, endurance: 2, evaluation: 2, resilience: 1 },
  },
  {
    id: 'salvage-worker',
    name: 'Salvage Worker',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'wreck-recovery-specialist',
    name: 'Wreck Recovery Specialist',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'scrap-dealer',
    name: 'Scrap Dealer',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'demolition-salvager',
    name: 'Demolition Salvager',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'recovery-diver',
    name: 'Recovery Diver',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'abandoned-site-picker',
    name: 'Abandoned-Site Picker',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'vehicle-recovery-operator',
    name: 'Vehicle Recovery Operator',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'industrial-recycler',
    name: 'Industrial Recycler',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'parts-reclaimer',
    name: 'Parts Reclaimer',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'hazardous-recovery-technician',
    name: 'Hazardous Recovery Technician',
    category: 'Salvage & Recovery',
    role: 'scavenger',
    minAge: 18,
    skillBias: { scavenging: 16, mechanicalEngineering: 12, lockpicking: 9, computers: 7 },
    attributeBias: { perception: 3, evaluation: 2, steadiness: 2, reasoning: 1 },
  },
  {
    id: 'smuggler',
    name: 'Smuggler',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'fence',
    name: 'Fence',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'burglar',
    name: 'Burglar',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'confidence-artist',
    name: 'Confidence Artist',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'black-market-courier',
    name: 'Black-Market Courier',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'gang-enforcer',
    name: 'Gang Enforcer',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'illegal-bookmaker',
    name: 'Illegal Bookmaker',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'safecracker',
    name: 'Safecracker',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'counterfeit-dealer',
    name: 'Counterfeit Dealer',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'underground-fixer',
    name: 'Underground Fixer',
    category: 'Criminal & Underground',
    role: 'crew',
    minAge: 18,
    skillBias: { stealth: 16, lockpicking: 12, negotiation: 9, closeQuarters: 7 },
    attributeBias: { perception: 3, socialAwareness: 2, agility: 2, composure: 1 },
  },
  {
    id: 'firefighter',
    name: 'Firefighter',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'paramedic',
    name: 'Paramedic',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'disaster-responder',
    name: 'Disaster Responder',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'rescue-technician',
    name: 'Rescue Technician',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'evacuation-coordinator',
    name: 'Evacuation Coordinator',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'hazardous-materials-responder',
    name: 'Hazardous Materials Responder',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'flood-rescue-worker',
    name: 'Flood Rescue Worker',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'mountain-rescue-worker',
    name: 'Mountain Rescue Worker',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'emergency-dispatcher',
    name: 'Emergency Dispatcher',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 18,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'incident-commander',
    name: 'Incident Commander',
    category: 'Emergency & Disaster',
    role: 'medic',
    minAge: 34,
    skillBias: { firstAid: 16, exploration: 12, mechanicalEngineering: 9, closeQuarters: 7 },
    attributeBias: { composure: 3, decisionMaking: 2, endurance: 2, leadership: 1 },
  },
  {
    id: 'machinist',
    name: 'Machinist',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'assembly-technician',
    name: 'Assembly Technician',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'quality-inspector',
    name: 'Quality Inspector',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'production-supervisor',
    name: 'Production Supervisor',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 34,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'toolmaker',
    name: 'Toolmaker',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'process-operator',
    name: 'Process Operator',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'robotics-technician',
    name: 'Robotics Technician',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'foundry-worker',
    name: 'Foundry Worker',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'precision-fabricator',
    name: 'Precision Fabricator',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 18,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'plant-manager',
    name: 'Plant Manager',
    category: 'Manufacturing & Production',
    role: 'technician',
    minAge: 34,
    skillBias: { mechanicalEngineering: 16, electricalEngineering: 12, weaponsmithing: 9 },
    attributeBias: { steadiness: 3, discipline: 2, handEye: 2, reasoning: 1 },
  },
  {
    id: 'armorer',
    name: 'Armorer',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'gunsmith',
    name: 'Gunsmith',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'weapons-technician',
    name: 'Weapons Technician',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'range-instructor',
    name: 'Range Instructor',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'security-contractor',
    name: 'Security Contractor',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'combat-sports-coach',
    name: 'Combat Sports Coach',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'blade-smith',
    name: 'Blade Smith',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'energy-weapons-technician',
    name: 'Energy-Weapons Technician',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'ballistics-examiner',
    name: 'Ballistics Examiner',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'ordnance-specialist',
    name: 'Ordnance Specialist',
    category: 'Weapons & Combat Trades',
    role: 'gunner',
    minAge: 18,
    skillBias: { weaponsmithing: 16, firearms: 12, energyWeapons: 9, meleeWeapons: 7 },
    attributeBias: { handEye: 3, steadiness: 2, evaluation: 2, discipline: 1 },
  },
  {
    id: 'clergy-member',
    name: 'Clergy Member',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'counselor',
    name: 'Counselor',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'mediator',
    name: 'Mediator',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'social-worker',
    name: 'Social Worker',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'youth-mentor',
    name: 'Youth Mentor',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'grief-counselor',
    name: 'Grief Counselor',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'community-organizer',
    name: 'Community Organizer',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'chaplain',
    name: 'Chaplain',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'marriage-counselor',
    name: 'Marriage Counselor',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
  {
    id: 'shelter-coordinator',
    name: 'Shelter Coordinator',
    category: 'Faith, Counseling & Community',
    role: 'crew',
    minAge: 18,
    skillBias: { persuasion: 16, negotiation: 12, firstAid: 9 },
    attributeBias: { socialAwareness: 3, charisma: 2, composure: 2, memory: 1 },
  },
];

/**
 * How a working life is said out loud, in the voice the rest of the life
 * history uses: a lowercase fragment, one per category, with the trade
 * dropped into it. Four per category, so the same profession does not always
 * produce the same sentence.
 */
export const PROFESSION_TEXT: Record<ProfessionCategory, string[]> = {
  'Medical & Care': [
    'worked as {p} somewhere that never had enough of anything',
    'spent years as {p} and stopped counting after the first bad winter',
    'trained as {p}, and learned to keep a level voice while doing it',
    'was {p} long enough to know which shortage kills people first',
  ],
  'Engineering & Repair': [
    'worked as {p}, keeping tired machinery honest past the point it deserved',
    'spent years as {p} with a hand light between their teeth',
    'was {p} on equipment nobody had made parts for in a decade',
    'learned the trade as {p}, mostly by being handed the jobs nobody else wanted',
  ],
  'Spaceflight & Navigation': [
    'flew as {p} on routes that were only legal in the sense that nobody checked',
    'worked as {p}, and can still feel a bad burn before the instruments say so',
    'spent years as {p} watching the same three stars from a different angle',
    'was {p} on hulls that should have been scrapped two owners ago',
  ],
  'Security & Law': [
    'worked as {p}, mostly standing between people who had already decided',
    'spent years as {p} learning which arguments end in a hand going somewhere',
    'was {p} in a district where the law arrived after everything important',
    'did the work of {p} long enough to stop expecting thanks for it',
  ],
  'Military & Defense': [
    'served as {p}, and does not tell the stories from it',
    'spent years as {p} being moved where the shortage was worst',
    'was {p} in a unit that came home smaller than it left',
    'did their service as {p}, and kept the habits afterwards',
  ],
  'Education & Academia': [
    'worked as {p}, explaining the same thing until it finally landed',
    'spent years as {p} in a building the district kept threatening to close',
    'was {p} to people who mostly could not afford to be there',
    'taught as {p}, and still counts a few of them as the best thing they did',
  ],
  'Science & Research': [
    'worked as {p} on funding that arrived late and left early',
    'spent years as {p} being right about something nobody wanted to hear',
    'was {p} in a lab that measured its budget in surviving equipment',
    'did the work of {p}, which is mostly repeating yourself carefully',
  ],
  'Computing & Data': [
    'worked as {p} on systems older than the people running them',
    'spent years as {p}, and learned how much a badly kept record costs',
    'was {p} for an outfit that never once said what the data was for',
    'did the work of {p} in a room with no window and excellent cooling',
  ],
  'Mining & Extraction': [
    'worked as {p}, underground, on a shift pattern designed by nobody who did it',
    'spent years as {p} and signed for every body that went down and came back',
    'was {p} in a seam everybody knew was finished two years before it closed',
    'did the work of {p} until the dust made the decision for them',
  ],
  'Construction & Trades': [
    'worked as {p} on buildings that were needed the month before they started',
    'spent years as {p} making other people\'s drawings survive contact with weather',
    'was {p} on sites where the safety brief was a shrug',
    'did the work of {p}, and can still tell a bad joint at ten paces',
  ],
  'Agriculture & Food': [
    'worked as {p} against soil that was quietly giving up',
    'spent years as {p} feeding more people than the numbers allowed for',
    'was {p} through three bad harvests and one that nearly made up for them',
    'did the work of {p}, which is mostly patience and weather',
  ],
  'Trade & Commerce': [
    'worked as {p}, and knows exactly what a friendly price actually costs',
    'spent years as {p} on margins that only worked if nothing went wrong',
    'was {p} in a market where the scarcity was manufactured upstairs',
    'did the work of {p} and can read a room by what people are not asking for',
  ],
  'Finance & Administration': [
    'worked as {p}, watching money leave in ways that were technically correct',
    'spent years as {p} making bad numbers look survivable on paper',
    'was {p} for people who preferred not to know the details',
    'did the work of {p}, and still cannot leave a discrepancy alone',
  ],
  'Government & Civic': [
    'worked as {p} inside a system that mostly worked by exception',
    'spent years as {p} explaining a policy they did not believe in',
    'was {p} when the district stopped being able to afford itself',
    'did the work of {p}, which was mostly deciding who waits',
  ],
  'Transportation & Logistics': [
    'worked as {p} on schedules built by somebody who had never made the run',
    'spent years as {p} moving other people\'s urgent things',
    'was {p} on a route where the last third was always the problem',
    'did the work of {p}, and can still estimate a load by eye',
  ],
  'Hospitality & Service': [
    'worked as {p}, and heard everything said at that table',
    'spent years as {p} being invisible to people who talked freely',
    'was {p} somewhere that stayed open because closing was worse',
    'did the work of {p}, which teaches you faces very fast',
  ],
  'Media & Communication': [
    'worked as {p}, filing stories that were true and inconvenient',
    'spent years as {p} learning what gets cut and by whom',
    'was {p} for an outlet that lost its nerve at the wrong moment',
    'did the work of {p}, which is mostly getting people to keep talking',
  ],
  'Arts & Performance': [
    'worked as {p} for rooms that were half full and entirely honest',
    'spent years as {p}, and can hold a crowd without raising their voice',
    'was {p} on the circuit until the circuit stopped running',
    'did the work of {p}, which nobody at home ever quite counted as work',
  ],
  'Exploration & Fieldwork': [
    'worked as {p} in country that had eaten the last two surveys',
    'spent years as {p} a long way from anyone who could help',
    'was {p} on ground nobody had mapped honestly',
    'did the work of {p}, and still walks into a room checking the exits',
  ],
  'Salvage & Recovery': [
    'worked as {p}, pulling value out of things that had already killed somebody',
    'spent years as {p} in hulls that were still cooling',
    'was {p} on wrecks the insurers had already written off',
    'did the work of {p}, and knows precisely what a floor sounds like before it goes',
  ],
  'Criminal & Underground': [
    'worked as {p}, which is a thing they do not put on a manifest',
    'spent years as {p} keeping arrangements that only worked on trust',
    'was {p} for people who settled accounts personally',
    'did the work of {p}, and got out before the arithmetic caught up',
  ],
  'Emergency & Disaster': [
    'worked as {p}, arriving after the worst of it and before the help',
    'spent years as {p} deciding who gets the next hour',
    'was {p} through two events the district still does not talk about',
    'did the work of {p}, which is mostly triage dressed as rescue',
  ],
  'Manufacturing & Production': [
    'worked as {p} on a line that ran whether or not it should have',
    'spent years as {p} holding a tolerance nobody inspected but them',
    'was {p} in a plant that was three years past its refit',
    'did the work of {p}, and cannot watch a machine run badly without fixing it',
  ],
  'Weapons & Combat Trades': [
    'worked as {p}, and treats every weapon as loaded because one was',
    'spent years as {p} making other people\'s tools reliable',
    'was {p} for buyers who did not explain themselves',
    'did the work of {p}, which teaches respect faster than any lecture',
  ],
  'Faith, Counseling & Community': [
    'worked as {p}, sitting with people on the worst day they had',
    'spent years as {p} holding a community together with very little',
    'was {p} where the nearest help was three days away',
    'did the work of {p}, and still cannot walk past somebody who is struggling',
  ],
};
