/**
 * Ship names — curated pools, not a dictionary.
 *
 * Straight from the ship generation library. Two templates plus an optional
 * series suffix: a standalone authored name, or an adjective and a noun. 'The'
 * is applied where it sounds natural rather than forced onto every hull, and
 * the same full name is never issued twice in one universe.
 *
 * Manufacturer, model and vessel name are three separate things. An NPC can
 * recognise a famous builder, a notorious model, or one particular ship.
 */

export interface StandaloneName {
  name: string;
  /** True where the library wrote the name with its article: 'The Riveter'. */
  definite: boolean;
}

/** 150 authored names. Roughly 70% of hulls draw from here. */
export const SHIP_NAMES_STANDALONE: StandaloneName[] = [
  { name: 'Riveter', definite: true },
  { name: 'Wayfarer', definite: false },
  { name: 'Drifter', definite: false },
  { name: 'Pilgrim', definite: false },
  { name: 'Courier', definite: false },
  { name: 'Mule', definite: false },
  { name: 'Nomad', definite: false },
  { name: 'Vagrant', definite: false },
  { name: 'Roamer', definite: false },
  { name: 'Wanderer', definite: false },
  { name: 'Trailblazer', definite: false },
  { name: 'Pathfinder', definite: false },
  { name: 'Pioneer', definite: false },
  { name: 'Prospector', definite: false },
  { name: 'Surveyor', definite: false },
  { name: 'Harvester', definite: false },
  { name: 'Scavenger', definite: false },
  { name: 'Tinker', definite: false },
  { name: 'Patchwork', definite: false },
  { name: 'Rivet', definite: false },
  { name: 'Spanner', definite: false },
  { name: 'Sprocket', definite: false },
  { name: 'Ratchet', definite: false },
  { name: 'Gasket', definite: false },
  { name: 'Flywheel', definite: false },
  { name: 'Keel', definite: false },
  { name: 'Ballast', definite: false },
  { name: 'Bulkhead', definite: false },
  { name: 'Crossbeam', definite: false },
  { name: 'Longhaul', definite: false },
  { name: 'Shortfall', definite: false },
  { name: 'Waymark', definite: false },
  { name: 'Waypoint', definite: false },
  { name: 'Farpoint', definite: false },
  { name: 'Outrider', definite: false },
  { name: 'Outpost', definite: false },
  { name: 'Relay', definite: false },
  { name: 'Beacon', definite: false },
  { name: 'Lantern', definite: false },
  { name: 'Lamplight', definite: false },
  { name: 'Torch', definite: false },
  { name: 'Ember', definite: false },
  { name: 'Cinder', definite: false },
  { name: 'Ashfall', definite: false },
  { name: 'Firefly', definite: false },
  { name: 'Glowworm', definite: false },
  { name: 'Starlight', definite: false },
  { name: 'Daybreak', definite: false },
  { name: 'Nightfall', definite: false },
  { name: 'Sunward', definite: false },
  { name: 'Moonward', definite: false },
  { name: 'Starward', definite: false },
  { name: 'Skyward', definite: false },
  { name: 'Homeward', definite: false },
  { name: 'Outbound', definite: false },
  { name: 'Inbound', definite: false },
  { name: 'Lifeline', definite: false },
  { name: 'Lastlight', definite: false },
  { name: 'Firstlight', definite: false },
  { name: 'Afterglow', definite: false },
  { name: 'Undertow', definite: false },
  { name: 'Crosswind', definite: false },
  { name: 'Tailwind', definite: false },
  { name: 'Headwind', definite: false },
  { name: 'Slipstream', definite: false },
  { name: 'Wake', definite: false },
  { name: 'Riptide', definite: false },
  { name: 'Current', definite: false },
  { name: 'Driftwood', definite: false },
  { name: 'Anchor', definite: false },
  { name: 'Compass', definite: false },
  { name: 'Northstar', definite: false },
  { name: 'Polestar', definite: false },
  { name: 'Meridian', definite: false },
  { name: 'Horizon', definite: false },
  { name: 'Frontier', definite: false },
  { name: 'Threshold', definite: false },
  { name: 'Crossing', definite: false },
  { name: 'Passage', definite: false },
  { name: 'Bridge', definite: false },
  { name: 'Gate', definite: false },
  { name: 'Gateway', definite: false },
  { name: 'Switchback', definite: false },
  { name: 'Detour', definite: false },
  { name: 'Shortcut', definite: false },
  { name: 'Backroad', definite: false },
  { name: 'Causeway', definite: false },
  { name: 'Spur', definite: false },
  { name: 'Sidetrack', definite: false },
  { name: 'Junction', definite: false },
  { name: 'Terminus', definite: false },
  { name: 'Layover', definite: false },
  { name: 'Secondhand', definite: false },
  { name: 'Hand-Me-Down', definite: false },
  { name: 'Keepsake', definite: false },
  { name: 'Relic', definite: false },
  { name: 'Oddity', definite: false },
  { name: 'Misfit', definite: false },
  { name: 'Rascal', definite: false },
  { name: 'Troublemaker', definite: false },
  { name: 'Lucky', definite: false },
  { name: 'Fortune', definite: false },
  { name: 'Providence', definite: false },
  { name: 'Chance', definite: false },
  { name: 'Gambit', definite: false },
  { name: 'Longshot', definite: false },
  { name: 'Payday', definite: false },
  { name: 'Windfall', definite: false },
  { name: 'Jackpot', definite: false },
  { name: 'Ledger', definite: false },
  { name: 'Copper', definite: false },
  { name: 'Iron', definite: false },
  { name: 'Steel', definite: false },
  { name: 'Brass', definite: false },
  { name: 'Silver', definite: false },
  { name: 'Goldleaf', definite: false },
  { name: 'Rustbucket', definite: false },
  { name: 'Scrapper', definite: false },
  { name: 'Clunker', definite: false },
  { name: 'Workhorse', definite: false },
  { name: 'Packhorse', definite: false },
  { name: 'Stubborn', definite: false },
  { name: 'Steady', definite: false },
  { name: 'Faithful', definite: false },
  { name: 'Reliable', definite: false },
  { name: 'Oldtimer', definite: false },
  { name: 'Veteran', definite: false },
  { name: 'Survivor', definite: false },
  { name: 'Holdout', definite: false },
  { name: 'Underdog', definite: false },
  { name: 'Ringer', definite: false },
  { name: 'Ace', definite: false },
  { name: 'Wildcard', definite: false },
  { name: 'Maverick', definite: false },
  { name: 'Renegade', definite: false },
  { name: 'Bandit', definite: false },
  { name: 'Smuggler', definite: false },
  { name: 'Ghost', definite: false },
  { name: 'Shadow', definite: false },
  { name: 'Whisper', definite: false },
  { name: 'Echo', definite: false },
  { name: 'Rumor', definite: false },
  { name: 'Secret', definite: false },
  { name: 'Promise', definite: false },
  { name: 'Oath', definite: false },
  { name: 'Witness', definite: false },
  { name: 'Messenger', definite: false },
  { name: 'Herald', definite: false },
  { name: 'Salutation', definite: false },
  { name: 'Whetstone', definite: false },
];

/** 50 x 50 = 2,500 raw compound names before article and suffix. */
export const SHIP_NAME_ADJECTIVES: string[] = [
  'Wobbly',
  'Quiet',
  'Rusty',
  'Lucky',
  'Crooked',
  'Stubborn',
  'Little',
  'Old',
  'Young',
  'Last',
  'First',
  'Hidden',
  'Loose',
  'Bright',
  'Dim',
  'Red',
  'Blue',
  'Silver',
  'Golden',
  'Black',
  'White',
  'Broken',
  'Mended',
  'Patchwork',
  'Wayward',
  'Lonesome',
  'Faithful',
  'Reckless',
  'Patient',
  'Restless',
  'Slow',
  'Quick',
  'Heavy',
  'Light',
  'Long',
  'Short',
  'Dusty',
  'Burnt',
  'Cold',
  'Warm',
  'Hollow',
  'Solid',
  'Bent',
  'Grinning',
  'Sly',
  'Honest',
  'Borrowed',
  'Secondhand',
  'Stray',
  'Wild',
];

export const SHIP_NAME_NOUNS: string[] = [
  'Sprocket',
  'Lantern',
  'Rivet',
  'Compass',
  'Mule',
  'Hammer',
  'Needle',
  'Kettle',
  'Boot',
  'Coin',
  'Anchor',
  'Beacon',
  'Switch',
  'Gasket',
  'Flywheel',
  'Piston',
  'Wrench',
  'Bolt',
  'Nail',
  'Keel',
  'Saddle',
  'Hitch',
  'Bucket',
  'Bell',
  'Drum',
  'Whistle',
  'Candle',
  'Match',
  'Ember',
  'Cinder',
  'Comet',
  'Meteor',
  'Moon',
  'Star',
  'Horizon',
  'Crossing',
  'Detour',
  'Junction',
  'Waypoint',
  'Trail',
  'Spur',
  'Relay',
  'Courier',
  'Pilgrim',
  'Prospector',
  'Rascal',
  'Bandit',
  'Ghost',
  'Echo',
  'Promise',
];

// ---------------------------------------------------------------------------
// Manufacturers and models
// ---------------------------------------------------------------------------

export interface ShipManufacturer {
  id: string;
  name: string;
  /** Weight in the ordinary build pool. */
  weight: number;
  /** What people say about their hulls, when anyone recognises the name. */
  reputation?: string;
}

/**
 * Who built it. Starzan is locked authored identity: the builder people name
 * when a hull comes home with a hole in it. The rest are ordinary yards, there
 * so Starzan means something by comparison.
 */
export const SHIP_MANUFACTURERS: ShipManufacturer[] = [
  {
    id: 'starzan',
    name: 'Starzan',
    weight: 8,
    reputation: 'Starzan hulls come home. People will tell you stories about that.',
  },
  { id: 'coleman-brandt', name: 'Coleman-Brandt', weight: 16 },
  { id: 'hallow-yards', name: 'Hallow Yards', weight: 15 },
  { id: 'tessik', name: 'Tessik Assembly', weight: 14 },
  { id: 'ordway', name: 'Ordway Fabrication', weight: 13 },
  { id: 'meridian-works', name: 'Meridian Works', weight: 12 },
  { id: 'kestrel-line', name: 'Kestrel Line', weight: 11 },
  { id: 'boughton', name: 'Boughton & Sons', weight: 10 },
  { id: 'harrowgate', name: 'Harrowgate Shipbuilding', weight: 9 },
  { id: 'lund-vance', name: 'Lund-Vance', weight: 8 },
  { id: 'penny-marine', name: 'Penny Marine', weight: 7 },
  { id: 'ashcroft', name: 'Ashcroft Hulls', weight: 6 },
];

export interface ShipModel {
  id: string;
  name: string;
  weight: number;
  /** Only these classes are built under this model line. */
  sizes?: string[];
  /** Set on the one model line people warn each other about. */
  notoriousFor?: 'engineStall';
  note?: string;
}

/**
 * The product family. The Corva 40 is the authored notorious line — it stalls,
 * it cools, it reboots, and it usually carries on. Everyone in a dock bar has
 * an opinion about whether that matters.
 */
export const SHIP_MODELS: ShipModel[] = [
  {
    id: 'corva-40',
    name: 'Corva 40',
    weight: 6,
    notoriousFor: 'engineStall',
    note: 'The Corva 40 stalls. Ask anyone. It usually comes back up.',
  },
  { id: 'tern', name: 'Tern', weight: 14 },
  { id: 'brace-2', name: 'Brace II', weight: 13 },
  { id: 'harbourman', name: 'Harbourman', weight: 12 },
  { id: 'dray', name: 'Dray', weight: 12 },
  { id: 'stub-7', name: 'Stub 7', weight: 11 },
  { id: 'cartwright', name: 'Cartwright', weight: 10 },
  { id: 'lowline', name: 'Lowline', weight: 10 },
  { id: 'ferryman', name: 'Ferryman', weight: 9 },
  { id: 'kestrel-9', name: 'Kestrel 9', weight: 9 },
  { id: 'oxbow', name: 'Oxbow', weight: 8 },
  { id: 'pennant', name: 'Pennant', weight: 8 },
  { id: 'grange', name: 'Grange', weight: 7 },
  { id: 'sandpiper', name: 'Sandpiper', weight: 7 },
  { id: 'mallet', name: 'Mallet', weight: 6 },
];
